### ISSUE TITLE
Can't recognize as styled-component

### ISSUE THREAD

**Issue by rohmanhm** [styled-components/vscode-styled-components#10]
Can't recognize `styled-components` when define `styled-components` as `Styled` but when using  `styled`  it recognized.

my custom name.
![image](https://cloud.githubusercontent.com/assets/7524911/22397128/36ff49c4-e59d-11e6-8955-2aa5ee712a72.png)

default
![image](https://cloud.githubusercontent.com/assets/7524911/22397113/f6278fe2-e59c-11e6-9e0f-2952b1f320d9.png)

**Comment by julienp** [comment]
Thanks for the report! Right now the extension looks for exactly `styled`. I think I'll make it case-insensitive in the next version.

**Comment by rohmanhm** [comment]
Thanks for your response @julienp ,
I always defined with Capitalize word for importing variable. 
This means a lot for me.
Waiting for next update. 😬

**Comment by Epikem** [comment]
What about providing a configuration for this? Then we could use like `s.div`.

```ts
import * as vscode from 'vscode';
import * as fs from 'fs';
import * as jv from 'json-variables';

// const content = fs.readFileSync('/syntaxes/styled-components.source.json'); //does not work
const content = fs.readFileSync('E:/dev/vscode-styled-components/syntaxes/styled-components.source.json');
const txt = content.toString();
const stobj = JSON.parse(txt);
stobj['var1'] = 's';
const jvd = jv(stobj,
	{
	  heads: "${",
	  tails: "}"
	});
console.log(jvd);
fs.writeFileSync('E:/dev/vscode-styled-components/syntaxes/styled-components.json', JSON.stringify(jvd));
```
(https://github.com/Epikem/vscode-styled-components/tree/test)
I replaced `[sS][tT][yY][lL][eE][dD]` with `s` and it works after reload. I wonder is there a better way to use vscode settings configuration on json file directly or access vscode extension project using relative path.
