### ISSUE TITLE
Support new TypeScript type-check syntax

### ISSUE THREAD

**Issue by sandervspl** [styled-components/vscode-styled-components#100]
TypeScript added support for styled-components type-checking. This looks like:

```typescript
styled.button<ButtonProps>`
	color: ${props => props.color};
`
```

When you add `<ButtonProps>` it breaks the highlighting.

**Comment by Cu3PO42** [comment]
We are aware of this issue and are tracking it in #81. Unfortunately I can't work on that issue at this time, but we would certainly welcome pull requests on it.
