### ISSUE TITLE
Order css rules alphabetically

### ISSUE THREAD

**Issue by theonelucas** [styled-components/vscode-styled-components#102]
What do you guys think about a shortcut to order the CSS rules alphabetically?

**Comment by jasonwilliams** [comment]
@theonelucas its a low priority (nice to have) issue for me right now as there's quite a few bugs and other issues that need working on. However feel free to have a go at this yourself.

https://github.com/styled-components/vscode-styled-components/blob/master/CONTRIBUTING.md

**Comment by jasonwilliams** [comment]
due to lack of interest in take up im going to close this
