### ISSUE TITLE
Version 0.0.18 and 0.0.19 potentially malicious?

### ISSUE THREAD

**Issue by levrik** [styled-components/vscode-styled-components#103]
Neither version 0.0.18 nor 0.0.19 was pushed to GitHub. Could these versions include malicious code? I don't want to update! Version 0.0.19 is also missing release notes in VS Code.

**Comment by levrik** [comment]
Okay. Thanks for the information 🙂

**Comment by julienp** [comment]
The release commits for 0.0.18 and 0.0.19 are pushed to GitHub and I also published and pushed 0.0.20.
