### ISSUE TITLE
Feature Request: Highlight colours

### ISSUE THREAD

**Issue by jameslnewell** [styled-components/vscode-styled-components#11]
e.g. [Color Picker for VSCode](https://marketplace.visualstudio.com/items?itemName=anseki.vscode-color) but for CSS in `styled-components`

**Comment by geddski** [comment]
yes I miss this from regular CSS files

**Comment by TrevorSayre** [comment]
![image](https://cloud.githubusercontent.com/assets/421548/24007461/0a661bb4-0a45-11e7-86f9-4047b3ec86bf.png)

**Comment by ekfuhrmann** [comment]
As a temporary work around, [Color Highlight](https://github.com/sergiirocks/vscode-ext-color-highlight) does work within styled components:

![image](https://user-images.githubusercontent.com/8878152/38097025-47a73482-3342-11e8-87e6-3a6bb826cedf.png)

**Comment by jasonwilliams** [comment]
duplicate of https://github.com/styled-components/vscode-styled-components/issues/95
