### ISSUE TITLE
Add a refactor action to extract styled-component definitions

### ISSUE THREAD

**Issue by mquandalle** [styled-components/vscode-styled-components#115]
VSCode supports some contextual code refactoring actions as described in https://code.visualstudio.com/docs/editor/refactoring.

The idea would be to create a styled-component refactor action to extract an inlined `style` attribute into it's own definition:

```jsx
const MyComponent = () =>
  <span style={{backgroundColor: "blue", borderRadius: 4}}>Hello world</span>;
```

When the `span` component is hovered an action to “Create a styled-component definition” should be presented that would transform the above code into:

```jsx
import styled from "styled-components";

const $Var = styled.span`
  background-color: blue;
  border-radius: 4px;
`;

const MyComponent = () =>
  <$Var>Hello world</$Var>;
```

Where `$Var` is selected by default and can be edited directly.

**Comment by jasonwilliams** [comment]
Sorry this is something that’s unlikely to be picked up. However if you’re happy to work on this a PR would be accepted

**Comment by mon-jai** [comment]
I created a codemod to migrate style attributes into styled-components. Hope it helps.

https://github.com/mon-jai/style-attribute-to-styled-component-codemod
