### ISSUE TITLE
`ts-styled-plugin` error on valid referred component template literal curly brace

### ISSUE THREAD

**Issue by awwong1** [styled-components/vscode-styled-components#117]
Hello, I'm seeing `ts-styled-plugin` errors while using this plugin (version `0.0.21`) and referred components in my application.

I have verified that my code compiles and renders in the browser without issues.

I see the following errors around the two curly braces after the referred component selector.
```typescript
const ListNoteTitle = styled.span`
  font-weight: bold;
  color: ${props => props.theme.primaryColor};
  ${ListNoteItem}:hover & {
    text-decoration: underline;
  }
`;
```
![screenshot from 2018-07-13 16-49-20](https://user-images.githubusercontent.com/2760111/42717230-c788e3b2-86bc-11e8-9f75-df0bba6c9147.png)

*  `[ts-styled-plugin] semi-colon expected` on the first curly brace
* `[ts-styled-plugin] at-rule or selector expected` on the second curly brace

I think this is a plugin issue. My relevant source code can be found here:
* [View Component](https://github.com/udia-software/udia-client/blob/c01b4c5d3219e350b6392788c1274f5dc7f3a0c5/src/Components/Notes/ListNotesView.tsx#L41)
* [Styled Theme](https://github.com/udia-software/udia-client/blob/c01b4c5d3219e350b6392788c1274f5dc7f3a0c5/src/Components/AppStyles.ts)

**Comment by leemun1** [comment]
I got this issue too while trying to refer to a different styled component.
Did this get fixed yet?

```javascript
const SomeStyledComponent = styled.div`
  background: red;
${SomeOtherStyledComponent}:hover & { // error on the curly braces from this line
  background: blue;
} // and here
`
```

**Comment by olhapi** [comment]
Still have this issue, but only on opening brace.
![screen shot 2018-09-17 at 17 35 11](https://user-images.githubusercontent.com/4780263/45630503-7fb6fd80-baa1-11e8-8ccd-556b43a02bfe.png)

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/typescript-styled-plugin#74

**Comment by ungarson** [comment]
I had the same `ts-styled-plugin` problem, it turned out that i had forgotten to add semicolon to the end of a line, so for anyone who is coming from google - check this

**Comment by 1mayur** [comment]
```
@page {
    margin: 2mm;
}
```

throws error

**Comment by lsnch** [comment]
Ran into a similar issue with styled. This here is working code which gets compiled and displayed properly. Turned out I had a stray space :-)

![Screen Shot 2019-06-02 at 01 24 15](https://user-images.githubusercontent.com/20382674/58754271-309ce580-84d5-11e9-8156-49e9fff00573.png)

**Comment by michchan** [comment]
Same here

**Comment by AndersonSantanna** [comment]
Any solution for that?

**Comment by assainov** [comment]
I've been using css @supports query and had the same issue. Resolved it by putting the code into css string interpolation like so:
```
export const SelectButton = styled.select`
  ${css`
    @media not all and (min-resolution: 0.001dpcm) {
      @supports (-webkit-appearance: none) {
        display: block;
        height: 60px;
        margin-left: 10%;
        margin-right: 10%;
        margin-top: 10px;
        min-height: 60px;
        width: 200px;
        text-indent: 40px;
      }  
  `}
`;
```

**Comment by ericwhitefield** [comment]
I have same issue as @lsnch

**Comment by williammustaffa** [comment]
I was f* struggling with this error, than I found out that I had an extra curly bracket in the end of one styled component:
```
export const ErrorMessage = styled.div`
  display: 'block';
  @media (max-width: ...) {
    // query code
  }
} <--- this little guy here
`
```
In short, I messed up hehe

**Comment by ricardobossan** [comment]
https://gitmemory.com/issue/microsoft/typescript-styled-plugin/100/572014717 this solved it for me.
