### ISSUE TITLE
plugin not working

### ISSUE THREAD

**Issue by drstonebraker** [styled-components/vscode-styled-components#118]
I've installed vscode-styled-components and restarted VS Code, but I do not see any of the features on my styled component definitions.  I see neither syntax highlighting nor intellisense.  How can I troubleshoot?

**Comment by drstonebraker** [comment]
Happy to share any more info; just not sure what to share.  As far as I know, my code is just standard styled-components, e.g.:

```
import styled from 'styled-components';

export const ProductTile = styled.div`
  min-height: 142px;
  line-height: 1rem;
  background: #fff;
  padding: 16px 16px 16px 32px;
  border-radius: 2px;
  border: solid 1px #ccc;
`;
```

**Comment by mjbvz** [comment]
Do you have any other extensions installed (such as language-babel)? What is the language mode of the file? This is shown in the lower right corner of the  status bar

**Comment by drstonebraker** [comment]
Ah yes, I disabled dzannotti.vscode-babel-coloring (Babel ES6/ES7) and now vscode-styled-components is working.  Thank you!  Do you know if it is possible to have both enabled and still have vscode-styled-components working as expected?

**Comment by mjbvz** [comment]
Thanks. That's tracked by #23. Not sure if there are any arounds currently

**Comment by Malichenko** [comment]
https://prnt.sc/rq9stz 
Hello, i disabled all extensions, but it doesnt work as well

**Comment by zzan1** [comment]
> https://prnt.sc/rq9stz
> Hello, i disabled all extensions, but it doesnt work as well

The same problem as me. And I also found that trick thing depicted as following picture
![image](https://user-images.githubusercontent.com/47623989/92302450-da9fd300-ef9e-11ea-9d79-f6a6b6f06e68.png)

**Comment by zTaaso** [comment]
I've discovered the reason for this. At least for me, syntax highlighting and intellisense wasn't working because of the name of the variable that I was importing styled-components. I just switched the name of it to 'styled' and it works fine. 
(by the way, you can observe this behaviour in the screenshot above)

**Comment by jasonwilliams** [comment]
@zTaaso yep that’s correct, the name needs to be `styled` for the highlighting to work properly.

same goes for you @zzan1, you’re using `style` instead of `styled` in your screen shot

**Comment by harshmalviya** [comment]
![image](https://user-images.githubusercontent.com/73441485/120223756-b76d3000-c25f-11eb-8540-d664f2762f1b.png)
Styled components not working despite not using 'style'. Image has been attached.

**Comment by jasonwilliams** [comment]
@harshmalviya rather than bumping a 3 year old issue which isn’t even the same problem as you have, could you make a new one?

**Comment by harshmalviya** [comment]
@jasonwilliams Sorry but I didn't understood what you meant. I am getting this problem while using VS Code styled components hence I objected. Its okay if you don't have solution for it. I'll try to not focus on that.

**Comment by jasonwilliams** [comment]
> @jasonwilliams Sorry but I didn't understood what you meant. I am getting this problem while using VS Code styled components hence I objected. Its okay if you don't have solution for it. I'll try to not focus on that.

Bumping this thread can make it difficult for me to know what the issue is. The new issues request more information (version, how to reproduce etc). So it’s easier for us to diagnose.

**Comment by Madhukanth** [comment]
I am getting html auto complete instead of css autocomplete.Any suggestions?? Not sure what to disable

**Comment by jasonwilliams** [comment]
@Madhukanth can you open a new thread with a video plus your settings please? Be sure to fill out the template thanks

**Comment by findmomin** [comment]
Dude, I'm getting Emmet's HTML autocompletion inside of styled.div``. This issue needs an immediate fix.

**Comment by jasonwilliams** [comment]
@findmomin I’ve just asked to raise a new issue and follow the template. And include a video/gif. If you want this fixed badly enough it can’t be that hard to do that.

I’m locking this issue now, as bumping a 2018 unrelated issue is not helpful.
