### ISSUE TITLE
CSS functions do not syntax highlight string interpolations inside of them

### ISSUE THREAD

**Issue by mattdarveniza** [styled-components/vscode-styled-components#122]
Any css functions, such as `calc()`, `rgba()` or any of the filter functions like `blur()`, will not render the syntax colors of string interpolations using `${}`. See screenshot

![screen shot 2018-08-10 at 4 33 01 pm](https://user-images.githubusercontent.com/946261/43942384-1fcdd442-9cbb-11e8-89fe-9e236e7b7824.png)

**Comment by jetpacmonkey** [comment]
I just came across this as well. Is there anything I can do to help, or any known way to get those interpolations rendering correctly?

**Comment by jasonwilliams** [comment]
This seems to work in 1.0.0
