### ISSUE TITLE
support highlighting for composed elements inside styled function

### ISSUE THREAD

**Issue by alidlorenzo** [styled-components/vscode-styled-components#124]
Right now highlighting for inline elements isn't supported

e.g.
```
styled(({ className, children }: any)=> (
  <div className={className}>
    <p>{children}</p>
  </div>
))`
 // styles
`
```

it seems uncessary to declare multiple different elements for simple styles so would love to have support for this

**Comment by rstaib** [comment]
Also you need this highlighting due to `extend` is deprecated and will be removed from version 4.0 the warning says.

This is the new way to extend.

```javascript
const Title = styled.h1`
  color: grey;
  font-size: 2em;
`

const RedTitle = styled(Title)`
  color: red;
`
```

**Comment by sedx** [comment]
Yet another test case for check.
At this moment highliting doesn't work for this:
```javascript
export default styled(connect(stateToProps)(EventHeader))`
  margin-top: 1.5rem;
  h3 {
    margin: 0;
    font-size: 1em;
    font-weight: normal;
  }
  .date{
    display: block;
    color: ${({ theme: { colors } }) => colors.gray};
  }
`;
```

**Comment by jasonwilliams** [comment]
Same as https://github.com/styled-components/vscode-styled-components/issues/169
