### ISSUE TITLE
JS autocomplete duplicates 'this'

### ISSUE THREAD

**Issue by franky47** [styled-components/vscode-styled-components#132]
I've chased this bug down to this extension (does not appear when it's disabled, and appears when only `vscode-styled-components` is active). It's weird because it has nothing to do with styled-components..

Take a class declaration in JavaScript:
```js
class Foo {
  state = {
    bar: 42
  }
  baz() {
    // Type here
  }
}
```
1. In the body of the baz method, start typing `this.sta`
2. autocomplete suggests `state` correctly
3. upon validating (Tab or Enter), the result is `this.this.state`.

I also have had very weird suggestions recently in my intellisense, but I can't yet pin it down to a specific extension or VSCode issue until I do more research.

**Comment by franky47** [comment]
I was able to confirm that the extension wreaks havoc in the autocomplete suggestions, examples:
- `console.lo` suggests localStorage and a few other irrelevant things starting with `lo` until `log` shows up at rank 7
- `{...` for object spread/rest randomly inserts nonsense between the dots

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/typescript-styled-plugin#73
