### ISSUE TITLE
No highlight when there's a space between = and styled (formatted by prettier)

### ISSUE THREAD

**Issue by Shimon1981** [styled-components/vscode-styled-components#137]
Not working (formatted using prettier)
![image](https://user-images.githubusercontent.com/2886102/45948454-bb514a80-c000-11e8-8cf4-a9de8c88b450.png)

Working without a space near assignment operator.
![image](https://user-images.githubusercontent.com/2886102/45948472-cc01c080-c000-11e8-9956-5c6d45a90413.png)

Suggestions?

**Comment by TJHdev** [comment]
Having the same issue. If I change the file extension to .ts from .js it highlights correctly..

**Comment by jbm1991** [comment]
I have a PR #143 open which fixes this issue. Who are the reviewers?
