### ISSUE TITLE
apparent memory leak causing high cpu usage in macos

### ISSUE THREAD

**Issue by byrondevonwall** [styled-components/vscode-styled-components#139]
os: macOS 10.13.6
node version: 6.14.4
vscode version: 1.27.2
vscode-styled-components version: 0.0.22

In mac OS, vscode's `Code Helper` process will intermittently start a thread that uses 100% of a cpu core.  When I run `ps aux | grep <pid>`, this is the output:
```
1165 100.0  1.0  5435340 330028   ??  R    Mon09AM   9:22.39 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js --useInferredProjectPerProjectRoot --enableTelemetry --cancellationPipeName /var/folders/5q/n8nnvfxn0x11nxk6jf02m57c0000gn/T/vscode-typescript/tscancellation-3d6fc7cfe1e6f121d79a.tmp* --globalPlugins typescript-styled-plugin --pluginProbeLocations /Users/byronwall/.vscode/extensions/jpoissonnier.vscode-styled-components-0.0.22 --locale en --noGetErrOnBackgroundUpdate
```

I have disabled all extensions except `vscode-styled-components` to make sure that the issue is specific to this extension.

I am able to kill the thread and continue to use vscode/this extension, but I figured I'd submit an issue as well.  Please let me know if there is anything more that could be helpful re:debugging.

**Comment by victorDecroix** [comment]
Same here for ArchLinux

os : 4.18.16-arch1-1-ARCH
node v: 11.1.0
vscode : 1.28.2
vscode-styled-components version: 0.0.25

for the same task

**Comment by UnbearableBear** [comment]
I can confirm I have the same issue here. Some process in this extension is melting my cpu to death

**Comment by jasonwilliams** [comment]
@byrondevonwall @victorDecroix can you open a new issue if this problem still persists? I haven’t been able to replicate this issue on the latest version
