### ISSUE TITLE
use of css`` helper function breaks syntax highlighting

### ISSUE THREAD

**Issue by skywinston** [styled-components/vscode-styled-components#140]
From my `package.json`:
`    "styled-components": "4.0.0-beta.9",`

When using the `css` helper function for styling partials, syntax highlighting breaks below where the the css helper function is being called:

![image](https://user-images.githubusercontent.com/700803/46505523-90c87400-c7ee-11e8-974d-a4d71da0820a.png)

**Comment by gaoxiaoliangz** [comment]
Same problem here

**Comment by yahooshiken** [comment]
Me, too.

**Comment by comerc** [comment]
But prettier formats my code without space :)

**Comment by pantharshit00** [comment]
It is quite pathetic here...

![image](https://user-images.githubusercontent.com/22195362/50726063-9efb9880-112d-11e9-8525-e85dff28e328.png)

**Comment by Ovyerus** [comment]
Getting same issue :/
![img](https://erisa.is-a-good-waifu.com/3fqSr8B.png)

**Comment by farskid** [comment]
Had the same problem with styled components v4.1.3 on vscode. disabling `vscode-styled-components`extension brought back syntax highlighting.

**Comment by CodingDive** [comment]
I also have no IntelliSense and syntax highlighting for the css inline prop when using `styled-components/macro`.

E.g 
```jsx
<div
  css={`
    border: 1px solid red;
  `}
/>
```

looks just like on GitHub.

**Comment by miyamoto-san** [comment]
I'm having the same issue!

**Comment by xeladejo** [comment]
Maybe https://github.com/styled-components/vscode-styled-components/issues/222#issuecomment-640054028 can help?

**Comment by jasonwilliams** [comment]
Yeah im sure this is fixed, please raise again if there's still an issue
