### ISSUE TITLE
Highlight it's just not working for me

### ISSUE THREAD

**Issue by Jossdz** [styled-components/vscode-styled-components#142]
Hi there, 

I'm having this problem with vscode(1.28.1).
I already restarted vscode after install and I tried re-install the extension and nothing works.
[
<img width="893" alt="captura de pantalla 2018-10-16 a la s 18 01 59" src="https://user-images.githubusercontent.com/23535629/47052389-a6825580-d16d-11e8-9f40-5d4db6d05b65.png">
](url)

**Comment by jbm1991** [comment]
Hi, the reason is likely to be because of #137 looking at your screenshot. I am having the same issue.

**Comment by gigamesh** [comment]
I'm having the same problem but the fix in #137 didn't work. I also tried disabling several other extensions to check if there was a conflict, but no dice (I only have about a dozen extensions installed).

**Comment by dmsps** [comment]
Maybe other Babel highliting plugin brokes it. In my case it was Babel JavaScript by Michael McDermott, after deactivating all Babel plugins vscode-styled-components works!

**Comment by Jossdz** [comment]
remove the babel ES6 / ES7 package and it worked
