### ISSUE TITLE
Get lint error when use template placeholder with pseudo-elements. 

### ISSUE THREAD

**Issue by haeguri** [styled-components/vscode-styled-components#147]
Hi.
I'm getting error when use template placeholder with pseudo-elements.

<img width="290" alt="screen shot 2018-12-11 at 9 02 08 pm" src="https://user-images.githubusercontent.com/6239742/49800752-b2644f80-fd8b-11e8-895f-c16b0368439f.png">

I think It's a bug.

**Comment by mjbvz** [comment]
Please file this issue [upstream](https://github.com/Microsoft/typescript-styled-plugin/issues).

Include example code (as text, not a screenshot)
