### ISSUE TITLE
Turn off linting?

### ISSUE THREAD

**Issue by ghost** [styled-components/vscode-styled-components#148]
Is it possible to de-activate linting in the vsCode extension version?

I have looked here and on https://github.com/Microsoft/typescript-styled-plugin and found no methods for this.

Thanks

UPDATE: Found the root of my issue, so don't really need this option now, but would be a nice option for others who may experience conflicts with other extensions and do not want to lose any functionality of those extensions.

I found that my issue was between this extension and https://marketplace.visualstudio.com/items?itemName=kamikillerto.vscode-colorize

The two do not play well together.

UPDATE: After spending more time with this as a plugin for vsCode, the linting definitely has some issues, would be great to have the ability to just turn it off.

**Comment by mjbvz** [comment]
See https://github.com/Microsoft/typescript-styled-plugin#linting. In you jsconfig or tsconfig, to disable linting just set:

```json
{
  "compilerOptions": {
    "plugins": [
      {
        "name": "typescript-styled-plugin",
        "validate": false
      }
    ]
  }
}
```
