### ISSUE TITLE
Autosuggest is not shown

### ISSUE THREAD

**Issue by hugonasciutti** [styled-components/vscode-styled-components#151]
Autosuggest do not open when writing a styled-component.

![image](https://user-images.githubusercontent.com/14843959/50690092-446e1980-1013-11e9-8701-da281c1b55a0.png)

Expected to show:
![screenshot from 2019-01-04 11-16-082](https://user-images.githubusercontent.com/14843959/50689921-b003b700-1012-11e9-9439-f0dfbeb4af29.png)

**Comment by mjbvz** [comment]
Can you manually trigger suggestions using ctrl+space?

**Comment by hugonasciutti** [comment]
It only shows the word grid when I press ctrl+space.

**Comment by esetnik** [comment]
@hugonasciutti I found the same issue, but was ultimately able to get it working. I am using workspace override for typescript version which requires some manual configuration that I didn't know about. Check https://github.com/Microsoft/typescript-styled-plugin#with-vs-code and see if it applies for you as well.

**Comment by hugonasciutti** [comment]
Thank you @esetnik, now that you mentioned typescript I remembered that I had turned off because it was having some problems with it. I disabled `TypeScript and JavaScript Language Features`[`vscode.typescript-language-features`] a built-in extension, I turned it on again and now the suggestions work, but I did not need to install these libs and add this config file.

**Comment by hugonasciutti** [comment]
For anyone who wants to check if the module is enabled, in `Extensions` use this search `@builtin typescript`.
