### ISSUE TITLE
Add support for css prop

### ISSUE THREAD

**Issue by vpicone** [styled-components/vscode-styled-components#152]
This was discussed in #48 but now that the `css` prop is here [via v4](https://www.styled-components.com/docs/api#css-prop), could we add support?

**Comment by eddiewang** [comment]
love this plugin. would love to see this supported as well :)

**Comment by vpicone** [comment]
I would add this myself, but can't make heads or tails of the regex

**Comment by KamaKAzii** [comment]
Also would love to see this supported! 👍

**Comment by njdancer** [comment]
Have made an update that supports highlighting of template strings inside css prop. Would appreciate any support available in getting double quoted strings working as well.

Here's a build for anyone who'd like to test this in the meantime.
https://github.com/njdancer/vscode-styled-components/releases/edit/0.0.26.pre1

**Comment by cahbb** [comment]
How far is this? Is it merged and live?
