### ISSUE TITLE
Syntax Highlighting not working when using Bracket notation

### ISSUE THREAD

**Issue by penovi17** [styled-components/vscode-styled-components#154]
![image](https://user-images.githubusercontent.com/20292647/51994680-1653ec00-2490-11e9-8ffc-d8632ba25972.png)

The title and the screen capture are pretty self-explanatory.

**Comment by alazzawimahmoud** [comment]
I found this workaround 🤓 
![image](https://user-images.githubusercontent.com/11873646/53588098-7079c700-3b8c-11e9-81a5-f081084cdb4f.png)

**Comment by jasonwilliams** [comment]
Related to https://github.com/styled-components/vscode-styled-components/issues/169
