### ISSUE TITLE
Highlighting Broken when using withComponent in styled()

### ISSUE THREAD

**Issue by esamattis** [styled-components/vscode-styled-components#158]
Very similar as

https://github.com/styled-components/vscode-styled-components/issues/75 

but it seems to happen when `withComponent` is passed to styled():

![image](https://user-images.githubusercontent.com/225712/53623866-018d8400-3c07-11e9-8b0e-93cd07d1a4e2.png)

**Comment by umanghome** [comment]
Fixed in #237
