### ISSUE TITLE
Not working for *.js files, only *.jsx

### ISSUE THREAD

**Issue by mmkal** [styled-components/vscode-styled-components#16]
Is there something I need to do to enable syntax highlighting for js files?

![image](https://cloud.githubusercontent.com/assets/15040698/23969729/d6115448-099d-11e7-8049-d770bc34c2ef.png)

It does work if I rename the file to `Button.jsx` - so the extension has properly loaded.

**Comment by julienp** [comment]
Do you have some other plugins installed that add a grammar for javascript files? It might be overriding this plugin or not provide the correct hook where this plugin injects the CSS grammar

**Comment by mmkal** [comment]
Ah, it was [vscode-flow](https://github.com/flowtype/flow-for-vscode). I don't know if this is a bug in vscode-styled-components, vscode-flow, vscode, all of the above or none of the above. I've turned off vscode-flow as I'm not using it right now.
