### ISSUE TITLE
Intellisense not working when using styled snippet

### ISSUE THREAD

**Issue by tiagosalema** [styled-components/vscode-styled-components#160]
I created the following user snippet for jsx:

```
"Styled Component": {
  "prefix": "styled",
  "body": ["const $1 = styled.${2:div}`", "  $3", "`;", ""]
}
```

If I use it, however, Intellisense is not available.

**Comment by mjbvz** [comment]
Where are you trying to trigger intellisense? For `styled.` or inside the styled template string?

**Comment by tiagosalema** [comment]
I am trying to trigger it inside the template literals of the `styled.` variable.

**Comment by mjbvz** [comment]
Try setting `"editor.suggest.snippetsPreventQuickSuggestions": false` to enable suggestions in snippets

**Comment by tiagosalema** [comment]
It worked like a charm. Thank you!

**Comment by DennisJunior247** [comment]
how do i find ` "editor.suggest.snippetsPreventQuickSuggestions": false` in vscode?

**Comment by DennisJunior247** [comment]
> Try setting `"editor.suggest.snippetsPreventQuickSuggestions": false` to enable suggestions in snippets
where do i  paste `"editor.suggest.snippetsPreventQuickSuggestions": false` in my vscode settings? i mean how do i get to the file where i would paste the above code?
