### ISSUE TITLE
Syntax highlighting not working when using inline function as an argument(`styled(() => <Foo />)`)

### ISSUE THREAD

**Issue by chayeoi** [styled-components/vscode-styled-components#162]
To avoid warning "Received `true` for non-boolean attribute XXX", I'm passing inline function as an argument to `styled` function.

```jsx
const StyledLink = styled(({ primary, ...otherProps }) => <Link {...otherProps} />)`
  /* styles */
` 
```
This pattern is useful for avoiding some warnings. (see [styled-components #1198](https://github.com/styled-components/styled-components/issues/1198) and discussion.)
However, when applying this pattern, syntax highlighting is not supported.

<img width="617" alt="syntax highlighting not supported in inline function argument" src="https://user-images.githubusercontent.com/17597549/54762035-ac0d2b80-4c36-11e9-8b59-def2f32429f4.png">

Also, I could assign inline function to variable for syntax highlighting.

```jsx
const StylableLink = ({ primary, ...otherProps }) => <Link {...otherProps} />
const StyledLink = styled(StylableLink)`
  /* styles */
`
```

<img width="569" alt="syntax highlighting supported in variable argument" src="https://user-images.githubusercontent.com/17597549/54762154-e080e780-4c36-11e9-9b4b-7a6230d13709.png">

But, doing so is both costly and cumbersome.
It would be great if you'll support syntax highlighting for this.

**Comment by th0th** [comment]
Isn't this a very common use case? I am surprised it isn't supported.

Or are we using `styled-components` wrong? 🤔🙂

**Comment by joeytwiddle** [comment]
I created [a small bounty](https://www.bountysource.com/issues/71715113-syntax-highlighting-not-working-when-using-inline-function-as-an-argument-styled-foo) for this issue (~21 USD).

**Comment by riongull** [comment]
I'll double @joeytwiddle 's bounty.  Bitcoin cash or Dash to whoever fixes this.  Seems like a common pattern that should be supported.

**Comment by adamcbrewer** [comment]
Have a little workaround:

```jsx
export const Component = styled((props) => (
  <div {...props} /
))(css`
  color: red;
`)
```

**Comment by kyleknighted** [comment]
We have a very similar problem with syntax highlighting no longer working while using theme context

![image](https://user-images.githubusercontent.com/122591/80111471-8ba05680-8545-11ea-91b3-3057b2ffbfab.png)

**Comment by umanghome** [comment]
With changes in #237, the issue in @chayeoi's original message works.

However, if the function declaration spans multiple lines, that doesn't work as TextMate Grammar does not support multiline matching. https://github.com/microsoft/vscode-textmate/issues/32

We could potentially by matching only a part of the function body, but I'm not very comfortable with TextMate Grammar and its regex to be able to tell if this will work.

**Comment by jasonwilliams** [comment]
@umanghome my advice would be we close this and have a new issue around multi line-inline functions so that’s it’s clear what doesn’t work. I think it’s possible to fix and I can also take a look.
