### ISSUE TITLE
Emmet no longer working with Visual Studio Code March release

### ISSUE THREAD

**Issue by spacecakes** [styled-components/vscode-styled-components#167]
After restarting Visual Studio Code this morning I lost my Emmet suggestions while typing CSS in a styled components. I no longer get suggestions to expand `gtc` to `grid-template-columns` for example. Not sure what causes this. 

Any ideas how I can fix it?

**Comment by dontsave** [comment]
I'm also having this same issue but in the following specific circumstance:

```

const TestDiv = styled.div`
  /*emmet working here */
  a {
    /* emmet working here */
  } 
  /* emmet not working here */
```
