### ISSUE TITLE
Go to definition, auto complete, very slow in VSC March 2019 release w/ Styled Components

### ISSUE THREAD

**Issue by johnculviner** [styled-components/vscode-styled-components#168]
I'm not sure where this belongs but it does appear to be an issue of interaction between vscode-styled-components and the latest "March 2019" release of VSC.

Here are some examples:

Go to definition triggers the file header loading bar for 2-3 seconds before yielding the go-to-definition "pop-up" screen. Reverting to February makes everything snappy again (millseconds):

![image](https://user-images.githubusercontent.com/1644353/56084661-c54f6500-5dfb-11e9-945c-fb6e7338e008.png)

Auto complete takes a few seconds of "Loading..." in March release while typing attributes inside of a styled component's JSX.  After reverting to February release everything take milliseconds again.

![image](https://user-images.githubusercontent.com/1644353/56084630-49edb380-5dfb-11e9-849d-4dee4d602229.png)

Am I doing something wrong? Any ideas? More info needed?

I tried doing verbose logging around `electron_node tsserver.js` which is showing the high CPU when this happens (I followed the guide here: https://github.com/Microsoft/vscode/issues/63630#issuecomment-442690063) but as not seeing any errors. The logs did confirm that things were taking multiple seconds to come back from tsserver during the above 2 situations (and NOT on older versions of VSC).

**Comment by mjbvz** [comment]
Possibly https://github.com/DefinitelyTyped/DefinitelyTyped/issues/34391

@johnculviner Do you see this on VS Code 1.33.1?

**Comment by johnculviner** [comment]
Hey thanks, glad to see it isn't just me. Hopefully this will get fixed soon in VSC. I say we leave this open until it is just so people see it?

**Comment by johnculviner** [comment]
@mjbvz Yes, the latest just auto-updated and I was like WTF?!  https://code.visualstudio.com/updates/v1_33  I just switched from IntelliJ to speed things up what is going on now! 😄

**Comment by mjbvz** [comment]
@johnculviner So did that fix the problem?

**Comment by johnculviner** [comment]
@mjbvz Switching to an older version of VSC did fix the problem: https://code.visualstudio.com/updates/v1_32 Would you like me to try downgrading typescript/definitely typed versions as you mentioned in latest 1.33.1 VSC?

**Comment by andy-hook** [comment]
Same issues here. Clearly noticeable when working with files that use styled components. Rolled back to an older version solved it for now.

**Comment by mjbvz** [comment]
@johnculviner Yes make sure you have the latest @types/styled components installed locally

**Comment by Jaymun723** [comment]
I experience lag with styled component and found that `@types/styled-component` depends on `@types/react-native` which makes conflicts with the "dom" lib in typescript. The lag was gone when I uninstall `@types/styled-component` and replace it with a simple module declaration (`declare module 'styled-component'`).

**Comment by mjbvz** [comment]
This is not an issue with this project. See https://github.com/microsoft/TypeScript/issues/31302 and the other linked issues

**Comment by oeed** [comment]
This does seem to still be the case, unfortunately, even though the linked issues were merged mid-last year. Is there perhaps something else at play? The author of #205 [created an extension](https://github.com/robertontiu/vscode-styled-components/commit/0f4c416561cc52d3a53365b80adbf09f4c90d78d) that disables autocomplete and the performance difference is very striking.
