### ISSUE TITLE
Highlighting problem when using with Material-UI 

### ISSUE THREAD

**Issue by yuuta1999** [styled-components/vscode-styled-components#169]
I love using `styled-components` and `Material-UI` together, and this is even better when using with this plugin. But I have a problem with the highlighting when the syntax gets messy (I took from the original Material-UI itself).
Simple:
![Screenshot from 2019-04-21 18-27-40](https://user-images.githubusercontent.com/30456893/56469416-ce77ac00-6463-11e9-8857-3bd8cdb82eed.png)
Messy:
![Screenshot from 2019-04-21 18-23-58](https://user-images.githubusercontent.com/30456893/56469415-c91a6180-6463-11e9-8fb4-074cccce49c7.png)

Is there any ways to fix this problem? Every comments is very appreciated.

**Comment by ZYinMD** [comment]
I experience the same issue.

Official example code can be taken from [here](https://material-ui.com/guides/interoperability/#deeper-elements).

**Comment by transfer1992** [comment]
+1
We need the complicated example to filter out unneeded props.

**Comment by alikadir** [comment]
+1

**Comment by jasonwilliams** [comment]
Is this still an issue?

**Comment by richardnguyen99** [comment]
I think it should be considered an issue since it's supposed to be a feature using this extension.
