### ISSUE TITLE
Add colon on css property completion?

### ISSUE THREAD

**Issue by vhflat** [styled-components/vscode-styled-components#172]
When completing a css property with intellisense it doesn't add a colon.

Is this a bug or a feature?

**Comment by simpleshadow** [comment]
Ya, wish this was here too… Also, I'm not getting value suggestions.

**Comment by Bat1sta** [comment]
This really is a complicated problem, it sounds silly, but it makes development much more laborious.

**Comment by theonlydaleking** [comment]
Do we know if this ever will be implemented or no?

**Comment by dilincoln** [comment]
Any solution?

**Comment by dilincoln** [comment]
> This really is a complicated problem, it sounds silly, but it makes development much more laborious.

take a look

https://marketplace.visualstudio.com/items?itemName=diegolincoln.vscode-styled-components

**Comment by jasonwilliams** [comment]
@dilincoln is this something you'd be happy PRing here?

**Comment by dilincoln** [comment]
Hey @jasonwilliams ! I'm testing this version forked by me to ensure that works perfectly but i pretend to make a PR soon =)

**Comment by jasonwilliams** [comment]
closing as a dupe of https://github.com/styled-components/vscode-styled-components/issues/220 continuing there

**Comment by jasonwilliams** [comment]
> > This really is a complicated problem, it sounds silly, but it makes development much more laborious.
> 
> take a look
> 
> https://marketplace.visualstudio.com/items?itemName=diegolincoln.vscode-styled-components

Thanks for making that fork @dilincoln 

That code is now upstream in this repo, the only difference is instead of a hardcoded list of CSS properties we utilies the css language service. Will be released in v1.6.0
