### ISSUE TITLE
`ts-styled-plugin` error on valid syntax with 2 interpolation strings

### ISSUE THREAD

**Issue by DavidDeprost** [styled-components/vscode-styled-components#176]
The error occurs in this code in a css prop:
```
${this.props.whichSide}: ${this.state.isActive ? 0 : '-90vw' };
```
It looks kinda weird, but it's for a sidebar component that can be either left or right (this.props.whichSide). This code works and results in `left/right: 0/-90vw;` to conditionally activate/deactivate the sidebar on the left/right.

The only problem is that the vscode plugin gives an error on the first `$` sign:
`} expected ts-styled-plugin(9999)`
and later on closing the css prop with ``` `}>```:
`at-rule or selector expected ts-styled-plugin(9999)`

There seem to be a plethora of issues with similar, rather uncommon use cases of string interpolation.
Many also in the typescript plugin (which, as I understand it, is used by this plugin):   
microsoft/typescript-styled-plugin#71, microsoft/typescript-styled-plugin#74, microsoft/typescript-styled-plugin#88 and microsoft/typescript-styled-plugin#89. (I'm not using typescript, so I don't understand why I'm getting the typescript `ts-styled-plugin` error.)

Is this being addressed? Even a stopgap solution like an `// eslint-disable-next-line` would be helpful, does that exist?

**Comment by AlicePorton** [comment]
The following syntax in a styled component template literal also triggers errors 
```css
margin-${props => (props.vertical ? 'left' : 'top')}: -${props => 
    (props.sliderHandleWidth - props.theme.sliderBarHeight) / 2}px;
```
![image](https://user-images.githubusercontent.com/46804476/60475180-a947bb00-9ca8-11e9-91d0-ffca2a578645.png)

first `$` sign: `colon expected`
and the next with `-${`: `semi-colon expected`

**Comment by mjbvz** [comment]
This is indeed an issue with [typescript-styled-plugin](https://github.com/Microsoft/typescript-styled-plugin/issues). Please reopen this upstream (and consider submitting a PR with a fix)

**Comment by bogdanq** [comment]
![image](https://user-images.githubusercontent.com/43848668/71621684-cb7fae80-2be1-11ea-89a1-7bd036edec34.png)

**Comment by breadadams** [comment]
@bogdanq I've just ran into a similar thing and it was due to a missing semicolon after the value - looks like it could be your case too.

**Comment by sumbad** [comment]
I've got this error with inline-style (just wanted to send a dynamic string to `style` attribute).
![image](https://user-images.githubusercontent.com/10432330/73048041-c517e600-3eb2-11ea-8d81-d35efb38bdf0.png)

Maybe it's not related to this issue. If so, then I apologize.

**Comment by breadadams** [comment]
@sumbad might it be that you're missing a set of curly brackets (eg. `style=${{ opacity: 1 }}`)?

I'm not to familiar with the syntax you're using though, so I could be wrong.

**Comment by sumbad** [comment]
@breadadams, unfortunately, a set of curly brackets doesn't fix the error. Additionally, I've gotten a new error:
![image](https://user-images.githubusercontent.com/10432330/73123815-0a313a80-3fcf-11ea-82bb-10a80571ffab.png)

_I use [lit-html](https://github.com/Polymer/lit-html)._

**Comment by ricardobossan** [comment]
https://gitmemory.com/issue/microsoft/typescript-styled-plugin/100/572014717 this solved it for me.

**Comment by normancarcamo** [comment]
@ricardobossan in that case it works fine, but not when you have a case like this:
<img width="947" alt="Screen Shot 2020-11-04 at 18 32 50" src="https://user-images.githubusercontent.com/2402579/98182760-2eaa3380-1ecc-11eb-9d05-c63715af2056.png">
