### ISSUE TITLE
Eslint - Flow - color issue

### ISSUE THREAD

**Issue by RobinHerzog** [styled-components/vscode-styled-components#178]
Hi,

I'm using eslint and flow.

Styled-components is broken even if I disable all plugins.

<img width="644" alt="Capture d’écran 2019-06-25 à 10 44 21" src="https://user-images.githubusercontent.com/4397570/60083638-60d34f00-9736-11e9-83e8-a3d75f410ab0.png">

**Comment by mjbvz** [comment]
This extension provides styled intellisense using a [typescript language service plugin](https://github.com/Microsoft/TypeScript/wiki/Writing-a-Language-Service-Plugin) so it will not work with the VS Code flow extension

This means we would need an entirely new flow specific solution, which I believe is out of scope
