### ISSUE TITLE
keyframes helper not highlighting in vscode

### ISSUE THREAD

**Issue by BlackFenix2** [styled-components/vscode-styled-components#179]
# Issue
When i attempt to use the keyframes helper from emotion i am getting no intellisense and the syntax highlighting is off compared to the @keyframes inside the css literal.

```js
import { keyframes, css } from '@emotion/core';

//bad highlight, no intellisense
const fadeInAnimation = keyframes`
      from {
        opacity: 0;
        transform: translateX(-50px);
      }
      to {
        opacity: 1;
        transform: translateX(0);
      }
`;
//good highlight and intellisense
const fadeInAnimation2 = css`
  @keyframes fade {
    from {
      opacity: 0;
      transform: translateX(-50px);
    }
    to {
      opacity: 1;
      transform: translateX(0);
    }
  }

  animation: 1s fade ease-in-out;
`;
//good highlight and intellisense
const fadeIn = css`
  @keyframes fade {
    from {
      opacity: 0;
      transform: translateX(-50px);
    }
    to {
      opacity: 1;
      transform: translateX(0);
    }
  }

  animation: 1s fade ease-in-out;
`;

export default fadeIn;
```

## Environment
React 16.8
Emotion 10

**Comment by tom-sherman** [comment]
Same problem here.

Screenshot: 
![image](https://user-images.githubusercontent.com/9257001/61223667-0ade3f80-a715-11e9-8b82-2ef3e3a6bcd4.png)

**Comment by lffg** [comment]
Same problem here:

![image](https://user-images.githubusercontent.com/23662020/62733848-d9981d00-b9fd-11e9-964f-d2d1c70c759c.png)

**Comment by jasonwilliams** [comment]
Syntax Highlighting has been address:
https://github.com/styled-components/vscode-styled-components/commit/d7b9e58ea6ec31d81219171c84008a0461d103fc

Intellisense is being looked at here:
https://github.com/microsoft/typescript-styled-plugin/pull/134

**Comment by jasonwilliams** [comment]
Keyframes syntax highlighting should be good now for intellisense id suggest raising in https://github.com/microsoft/typescript-styled-plugin
