### ISSUE TITLE
Syntax highlight fails if `.attrs` is provided a generic

### ISSUE THREAD

**Issue by Haaxor1689** [styled-components/vscode-styled-components#180]
Similar to issue #39 just happens when `.attrs` is specialized with the type of props in typescript like this:

```
type Props = { goo: boolean };
const Foo = styled.div.attrs<Props>(p => p.goo)<Props>`
    display: ${p => p.goo ? "block" : "none"};
`
```

Preview in VS Code:

![Preview](https://i.imgur.com/P5U2n0v.png)

**Comment by dilizarov** [comment]
Probably a bit different than #39 seeing as how that one was resolved, but this one is still happening.
