### ISSUE TITLE
When passing a component as a function, the css markup stops working.

### ISSUE THREAD

**Issue by ezvr** [styled-components/vscode-styled-components#182]
There are certain edge-cases where you must selectively pass props to the component you are styling. This happens, when you are using third party components, that freely forward everything to the dom. So in this case you cannot pass any prop you want to the component, as that results in an error.
The issue can be seen discussed here:
https://github.com/styled-components/styled-components/issues/135#issuecomment-256018643
https://github.com/couds/react-bulma-components/issues/187

The solution is as such:
`const ListElement = styled(({ active, ...rest }) => <Link {...rest} />)`

However this makes the markup not work.

Steps to reproduce:
Create a styled component const, and use the above code, see, the markup highlighting not work anymore.

![image](https://user-images.githubusercontent.com/11723882/62278528-8e539c80-b448-11e9-8a91-ae72190bffa5.png)

**Comment by NordlingDev** [comment]
I found a workaround:

```
const StyledBox = ((Wrapper) => styled(Wrapper)`
    flex: 0 0 180px;
    ...
`)(({ active, ...rest }) => (
    <Link {...rest} />
));
```

**Comment by XYShaoKang** [comment]
temporary solution, installation [vscode-language-babel](https://marketplace.visualstudio.com/items?itemName=mgmcdermott.vscode-language-babel)
then add before the template string `/* CSS */`

```js
const SearchWarp = styled(({ children, searchDisplay, ...otherProps }) => (
  <SearchBox pose={searchDisplay ? `show` : `hide`} {...otherProps}>
    {children}
  </SearchBox>
))/* CSS */ `
  display: block;
  padding: 6px;
  background: #fff;
  border-bottom: 1px solid rgba(0, 0, 0, 0.07);
  border-top: 1px solid rgba(0, 0, 0, 0.07);
`
```

![2019-10-07_10-10-54](https://user-images.githubusercontent.com/38753204/66280853-35dac880-e8eb-11e9-804b-0b740e2b32c5.png)

**Comment by hanvyj** [comment]
> temporary solution, installation [vscode-language-babel](https://marketplace.visualstudio.com/items?itemName=mgmcdermott.vscode-language-babel)
> then add before the template string `/* CSS */`
> 
> ```js
> const SearchWarp = styled(({ children, searchDisplay, ...otherProps }) => (
>   <SearchBox pose={searchDisplay ? `show` : `hide`} {...otherProps}>
>     {children}
>   </SearchBox>
> ))/* CSS */ `
>   display: block;
>   padding: 6px;
>   background: #fff;
>   border-bottom: 1px solid rgba(0, 0, 0, 0.07);
>   border-top: 1px solid rgba(0, 0, 0, 0.07);
> `
> ```
> 
> ![2019-10-07_10-10-54](https://user-images.githubusercontent.com/38753204/66280853-35dac880-e8eb-11e9-804b-0b740e2b32c5.png)

Doesn't work for Typescript, sadly.

**Comment by finnmerlett** [comment]
*bump* this issue please :)

I'm sure it's just a function of the regexs used to identify template literals to be highlighted - when there are linebreaks inside the text signifying css is following (in the example, that's `` styled(.*)` ``), it doesn't match the regex assigned to look for it any more.

I had a quick look into the code, but dear god those regexes are long and complicated. I would have no idea how to dive into fixing it...
