### ISSUE TITLE
Can you create an empty line on enter

### ISSUE THREAD

**Issue by linonetwo** [styled-components/vscode-styled-components#184]
Currently, when hitting "Enter" between ``` `` ```, it will go from:

```js
const Container = styled.div``
```

 to 

```js
const Container = styled.div`
`
```

But actually it is better to become 

```js
const Container = styled.div`

`
```

So there is no need to `Command + Shift + Enter` to manually create an empty line.

**Comment by jasonwilliams** [comment]
+1!
@julienp as this is a very common occurrence it would be nice to have some autocomplete/help here.

Also having it set up when you type 
```tsx
const Container = styled.div`
```

then hit enter

**Comment by linonetwo** [comment]
@jasonwilliams probably when you write a PR, he will appear and accept it

**Comment by jasonwilliams** [comment]
PR added @julienp @linonetwo
