### ISSUE TITLE
It doesn't highlight margin-vertical and margin-horizontal

### ISSUE THREAD

**Issue by LuigiMaestrelli** [styled-components/vscode-styled-components#185]
I'm using version 0.0.26

![image](https://user-images.githubusercontent.com/5038871/63100599-c7facc00-bf4d-11e9-861e-5e0c9d191de3.png)

**Comment by RageOfJustice** [comment]
with TS ive got this
![image](https://user-images.githubusercontent.com/18666217/63861238-3199c200-c9b3-11e9-8154-dafdb2136de4.png)

**Comment by christophby** [comment]
any news on this?

**Comment by ViniciusPaldes** [comment]
I'm also interested.

**Comment by ariane92** [comment]
Hi, I was also having this same problem when trying to use resize-mode. It appears that styled-components don't recognize the exclusive properties of react-native. So it is necessary to add the types in tsconfig.json
![resize-mode](https://user-images.githubusercontent.com/5742201/90697170-2be85c80-e254-11ea-9c43-649c82550043.PNG)

**Comment by jasonwilliams** [comment]
sounds like a react-native property so closing for https://github.com/styled-components/vscode-styled-components/issues/91

**Comment by GabrielCorreia19** [comment]
Rapaaz, pegou mesmo aqui... Muito obrigado, direto tentava estilizar com essas propriedades e não conseguia, agora acabou o sofrimento kkkk. Tmj!

> Olá, também estava tendo o mesmo problema ao tentar usar o modo de redimensionamento. Parece que os componentes estilizados não reconhecem as propriedades exclusivas do react-native. Então é necessário adicionar os tipos em tsconfig.json ![modo de redimensionamento](https://user-images.githubusercontent.com/5742201/90697170-2be85c80-e254-11ea-9c43-649c82550043.PNG)
