### ISSUE TITLE
Single line commenting not working?

### ISSUE THREAD

**Issue by omartan** [styled-components/vscode-styled-components#187]
![Screenshot 2019-08-21 at 7 05 47 PM](https://user-images.githubusercontent.com/12379413/63427098-f2192600-c446-11e9-85e7-4f59ed55e46d.png)

It appears after installing this plugin, it doesn't allow to do single line CSS `//comment` comments?

CMD + / will give `/* */` instead of `//`

**Comment by cdeutsch** [comment]
Just running into this as well.

Emotion supports inline comments, would be nice if vscode didn't complain 👍

**Comment by lcswillems** [comment]
Same thing!

**Comment by tiancihe** [comment]
Same here

**Comment by jasonwilliams** [comment]
This has been fixed in https://github.com/styled-components/vscode-styled-components/commit/32cebc8ce7fbc21d878b190d313c92751fd4209d and will be available in 1.0.0
