### ISSUE TITLE
No syntax highlighting when styled has second argument

### ISSUE THREAD

**Issue by brandonkal** [styled-components/vscode-styled-components#188]
The syntax highlighting does not function when styled has a second argument:
```jsx
const El = styled('div', options)`
    color: blue; /* This is not highlighted, though ts-styled-plugin still works */
`
```
The highlighting should occur regardless of the count of arguments provided to styled().

ref: https://github.com/microsoft/typescript-styled-plugin/issues/101

**Comment by umanghome** [comment]
Fixed in #237
