### ISSUE TITLE
`at-rule or selector expected`

### ISSUE THREAD

**Issue by schulke-214** [styled-components/vscode-styled-components#189]
# Issue
<img width="564" alt="code" src="https://user-images.githubusercontent.com/37018485/65455513-a98ac900-de47-11e9-963d-0e20337422fe.png">
<img width="593" alt="error" src="https://user-images.githubusercontent.com/37018485/65455514-a98ac900-de47-11e9-8cf2-345dcfe03bf8.png">

vscode throws an error (`css(css-ruleorselectorexpected)`) even though the css is valid.

# Expected behaviour

No errors.

**Comment by schulke-214** [comment]
Im sorry, i found out, that this is an issue with `styled-jsx`

**Comment by silnose** [comment]
![Captura de pantalla de 2020-10-05 22-03-00](https://user-images.githubusercontent.com/10604773/95147265-9d259580-0756-11eb-8a29-4d48e1f46883.png)

I had the same error, and apparently  It was because that extension (Name: styled-jsx Language Server) so I disabled it.
