### ISSUE TITLE
Unknown property: 'aspect-ratio'

### ISSUE THREAD

**Issue by jbjeong-kosac** [styled-components/vscode-styled-components#190]
Hello, I have Problem
  
![스크린샷 2019-09-27 오전 10 45 35](https://user-images.githubusercontent.com/55368637/65736041-a1b37900-e114-11e9-816d-f5ccb3141818.png)

Error Message: Unknown property: 'aspect-ratio'ts-styled-plugin(9999)

Env:
   1. React-Native Project(with expo)
   2. Typescript file

How can i solve this problem?

**Comment by jasonwilliams** [comment]
Two things need to happen for this to be fixed:
1.  https://github.com/styled-components/vscode-styled-components/blob/master/syntaxes/css.styled.json#L779 needs to also include `source.css#media-features` (fixes syntax)
2. https://github.com/microsoft/typescript-styled-plugin/issues/119 (fixes intellisense)

**Comment by karlhorky** [comment]
Is this a problem again? I see this now for a `css` property still now (using version `1.7.5` of the extension):

<img width="473" alt="Screenshot 2022-11-21 at 14 05 28" src="https://user-images.githubusercontent.com/1935696/203063603-841fbf39-158c-4b9d-b39f-84351031aac4.png">

**Comment by karlhorky** [comment]
Hmm... and as per https://github.com/microsoft/typescript-styled-plugin/issues/58, configuring `compilerOptions.plugins[0].lint.validProperties` with `["aspect-ratio"]` seems to help, in `tsconfig.json`:

```json
{
  "$schema": "https://json.schemastore.org/tsconfig",
  "compilerOptions": {
    "plugins": [
      {
        "name": "typescript-styled-plugin",
        "lint": {
          "validProperties": ["aspects-ratio"]
        }
      }
    ]
  }
}
```

**Comment by karlhorky** [comment]
Maybe time for a PR: https://github.com/microsoft/vscode-css-languageservice/pull/317
