### ISSUE TITLE
Format styled.div(({theme}) => `...`

### ISSUE THREAD

**Issue by lcswillems** [styled-components/vscode-styled-components#194]
People often write this kind of code:

```
const StyledDiv = styled.div`
    color: ${props => props.theme.primary.main};
    background-color: ${props => props.theme.backgroundColor};
    border: 1px solid ${props => props.theme.borderColor};
    ...
`
```

But, there is an underrated way of writing this code, that makes it much clearer:

```
const StyledDiv = styled.div(({theme}) => `
    color: ${theme.primary.main};
    background-color: ${theme.backgroundColor};
    border: 1px solid ${theme.borderColor};
    ...
`)
```

However, the VSCode plugin doesn't style the latter. Would it be possible to style it?

**Comment by nhagen** [comment]
Not ideal, but you can do this as a workaround:

```
const StyledDiv = styled.div(({ backgroundColor }) => css`
    backgroundColor: ${ backgroundColor }
    ...
  `);
```

**Comment by lcswillems** [comment]
Thanks! But that's not great...

**Comment by wyqydsyq** [comment]
I also noticed this when trying to set some props on a styled component on the fly for integration with Material-UI:
![image](https://user-images.githubusercontent.com/621277/69960646-b6b5e980-1555-11ea-8ce5-6875387d846b.png)

It seems the plugin only recognises it should highlight when given functions provided by reference and not anonymous callback functions

**Comment by kylepeeler** [comment]
Bump, this would be nice to work w/out importing the `css` function, however that workaround did work for us as well for a short term solution.

+1 to making it supported w/out it though!

**Comment by a7madgamal** [comment]
I'm willing to look into this but I need some help as I never contributed here before.
What needs to be fixed here? Is this also related to prettier?

**Comment by jasonwilliams** [comment]
Thanks @a7madgamal  there’s a contribution guide here https://github.com/styled-components/vscode-styled-components/blob/master/CONTRIBUTING.md

**Comment by a7madgamal** [comment]
I gave it a try now, my head hurt but I kinda get what happening here
I'm just no sure how to modify something like ```(?:([\\s\\S][sS][tT][yY][lL][eE][dD](?:<.+>(?=\\())?(?:\\.[_$[:alpha:]][_$[:alnum:]]*|\\s*\\(['\"][_$[:alpha:]][_$[:alnum:]]*['\"]\\)|\\s*\\((.+)\\))(?:\\s*<.+>)?)|(css|keyframes|injectGlobal|createGlobalStyle)(<.+>)?)\\s*(`)```
I tried a couple of regex websites but nothing worked for me, any suggestions?

**Comment by jasonwilliams** [comment]
There’s links to websites in the contributing guide @a7madgamal
