### ISSUE TITLE
Code completion?

### ISSUE THREAD

**Issue by oscar-b** [styled-components/vscode-styled-components#2]
Excellent work on the syntax highlighting, it looks a lot better now :)

Is it possible to also get CSS code completion, or is that not possible in VSCode?

**Comment by wmertens** [comment]
I came here with that same question, and also with a link to something that may be related: https://github.com/Microsoft/vscode/issues/8928

**Comment by julienp** [comment]
Thanks for the link, I'll look into this in the near future.

**Comment by wmertens** [comment]
See also https://github.com/Microsoft/vscode/issues/2793#issuecomment-260367563, it seems that it is already possible if you manage to match the template strings with a TM grammar

**Comment by chuckhendo** [comment]
To add on to this - Emmet support would be great. Emmet/Code has an option for syntaxProfiles, so you can specify that you want to use CSS Emmet instead of HTML Emmet.... but it doesn't seem to detect that I'm inside of a CSS block and just does the HTML completion. Not sure if this can be fixed here or if it's a VSCode issue.

**Comment by Ajar-Ajar** [comment]
@wmertens You have me confused... is it possible to autocomplete?
I read the comment you referenced. Is it possible to do or is it a suggestion?
Thank you!

**Comment by wmertens** [comment]
Hmm you are right, not sure if autocomplete works with the injection grammars, maybe those are two different things

**Comment by mattiaerre** [comment]
+1 on this, autocomplete would be splendid; the last missing bit I guess 👍  and also linting but that's another story 😅

**Comment by Ajar-Ajar** [comment]
Is there anything we can do to help this feature besides waiting or +1 ?
Can you reference a resource of how to create such an extension? is there anyone working on such an extension that can use some help? How can we go about contributing for this to materialize?

**Comment by julienp** [comment]
Currently I have done no work toward this, and I'm not quite sure where to start. I'll of course happily merge any merge request implementing this :)

As @Ajar-Ajar said, any references or examples on how to go about this would be very helpful

**Comment by xekri** [comment]
I think in-built css code completion is done by css language server, which you can go refer to the (offical css extension)[https://github.com/Microsoft/vscode/tree/master/extensions/css].

By the way, first I thought it's easy, just add `"embeddedLanguages": { "source.css": "css" }` to the "grammars" attribute, but `styled components` syntax differs from original css, which doesn't has css-legal brackets, and it causes can't the completion can't be highlighted by built-in css colorizer.

**Comment by wmertens** [comment]
Isn't the syntax more-or-less SASS compatible?

**Comment by xekri** [comment]
I think .css only contain scss styled syntax.

The method I mention before doesn’t work too. I tried on some language that use embeddedLanguages, and it doesn’t offer auto completion either.

Perhaps it’s a missing feature of vscode, maybe you can create a issue for it.




On 2017年4月3日 at 下午10:25:50, Mertens Wout (notifications@github.com<mailto:notifications@github.com>) wrote:

Isn't the syntax more-or-less SASS compatible?

**Comment by svipben** [comment]
Check this: https://marketplace.visualstudio.com/items?itemName=plievone.vscode-template-literal-editor, it have only 1 problem I write about that in issues.

**Comment by nolan-mbo** [comment]
I use the template literal editor as well. Works great. Thanks for the suggestion @svipben

**Comment by muhajirframe** [comment]
looking for the same thing. And recently foundOut that https://github.com/paypal/glamorous support autocomplete, it's nice. But it doesn't use css syntax, it use JS Object. The API is pretty similiar as it's inspired by styled-components

**Comment by auchenberg** [comment]
This functionality seems to be depend on landing https://github.com/Microsoft/vscode/issues/5961 in Code.

**Comment by lXSPandora** [comment]
Hey guys test it out

https://marketplace.visualstudio.com/items?itemName=lXSPandora.vscode-styled-components-snippets

**Comment by mjbvz** [comment]
I've created a TypeScript server plugin that adds suggestions, error reporting, and hovers for styled component strings in JS and TS: https://github.com/Microsoft/typescript-styled-plugin

![](https://github.com/Microsoft/typescript-styled-plugin/raw/master/documentation/preview.gif)

This plugin works well in VS Code alongside the vscode-styled-components extension, and it also should work in any other editor that uses the TypeScript language service. Eventually we plan to let VS Code extensions contribute TS server plugins as well, which would eliminate the need for any extra npm installs or configuration. 

Please give the plugin a try and let me know if you run into any issues

**Comment by SidKwok** [comment]
@mjbvz Thanks! Great job!

**Comment by comerc** [comment]
@mjbvz how to use it with styled-jsx?

**Comment by aczekajski** [comment]
@mjbvz Thanky you for the plugin! However, it is possible in styled-components to nest the selectors, just like in SCSS, so you can write `&:hover { ... }` or `.wrapper & { ... }` or even `${OtherComponent} { ... }` and the autocompletion breaks inside the curly brackets.

**Comment by mjbvz** [comment]
Please post issues about the plugin here: https://github.com/Microsoft/typescript-styled-plugin/issues

**Comment by tenjojeremy** [comment]
Is there a better solution?

How can Atom make it work seamlessly, but VScode can't. This is the only reason I don't switch completely to VScode.
