### ISSUE TITLE
Highlighting not working when passing component function directly

### ISSUE THREAD

**Issue by kunimitaiyoh** [styled-components/vscode-styled-components#201]
Delighted.

When you style an existing function component in JSX, syntax higligting for styles is not working on a certain kind of component.

It *works* on the following:
```jsx
import styled from "styled-components";

const Link = ({ className, children }) => (
  <a className={className}>
    {children}
  </a>
);

const StyledLink = styled(Link)`
  color: palevioletred;
  font-weight: bold;
`;
```

It *does not work* on the following:
```jsx
import styled from "styled-components";

const DirectStyledLink = styled(({ className, children }) => (
  <a className={className}>
    {children}
  </a>
))`
  color: palevioletred;
  font-weight: bold;
`;
```

It seems that syntax higlighting does not work when you pass a function expression of a component to the `styled` function *directly*.

These examples referes [styled-components: Basics](https://www.styled-components.com/docs/basics#styling-any-component).

Thank you.

**Comment by jukkahuuskonen** [comment]
Any work on this?
This is a problem for me too when I need to filter props out to prevent them being applien to the dom element.

**Comment by ford04** [comment]
Yeah, I also need this pattern also  mentioned in the [TypeScript section](https://styled-components.com/docs/api#using-custom-props) to proxy props.

Workaround:
```
const DirectStyledLinkCss = css`
  color: palevioletred;
  font-weight: bold;
`

const DirectStyledLink = styled(({ className, children }) => (
  <a className={className}>{children}</a>
))`
  ${DirectStyledLinkCss}
`
```

**Comment by umanghome** [comment]
See https://github.com/styled-components/vscode-styled-components/issues/162#issuecomment-706907785
