### ISSUE TITLE
"{ expected ts(2322)" when using the css helper function

### ISSUE THREAD

**Issue by jarodburchill** [styled-components/vscode-styled-components#204]
I am using it the same way it is used in the [docs](https://styled-components.com/docs/api#css) and I get an error in VS code:  

![image](https://user-images.githubusercontent.com/37840393/72817035-1d42b400-3c37-11ea-8a5d-f34aa544b514.png)

**Comment by jarodburchill** [comment]
Just realized that [lit-plugin](https://marketplace.visualstudio.com/items?itemName=runem.lit-plugin) for vs code was conflicting with this plugin.

**Comment by philscott-dev** [comment]
> Just realized that [lit-plugin](https://marketplace.visualstudio.com/items?itemName=runem.lit-plugin) for vs code was conflicting with this plugin.

Disabling this fixed my issue as well.
