### ISSUE TITLE
Support css<Props>`` like element<Props>``

### ISSUE THREAD

**Issue by iansan5653** [styled-components/vscode-styled-components#206]
Migrating from https://github.com/microsoft/typescript-styled-plugin/issues/106:

The styled-components `css` tag passes props through from the parent element, so something like:
```tsx
interface Props {
  //...
}
const baseHeadingStyles = css<Props>`
  //...
`;
```
is perfectly valid. This doesn't get recognized by the extension though.

**Comment by lucastobrazil** [comment]
Related: #207

**Comment by finnp** [comment]
An example like this works:

```js
const baseHeadingStyles = css<Props>`
  color: #ccc;
  height: 12px;
`;
```

I'm closing this assuming that it works now.
