### ISSUE TITLE
props.foo && css`` breaks syntax highlighting

### ISSUE THREAD

**Issue by schulke-214** [styled-components/vscode-styled-components#207]
This breaks the syntax highlighting:
![breaks](https://user-images.githubusercontent.com/37018485/73545454-aa59ea00-443b-11ea-9cc1-e7474205d557.png)

And this works:
![works](https://user-images.githubusercontent.com/37018485/73545710-2d7b4000-443c-11ea-960d-26facfa4c2c6.png)

Since the styled-components docs show that these conditional styles usually use `css`` ` I am confused that this breaks the highlighting.

**Comment by ksjogo** [comment]
Could you check how ```
${({ onClick, theme }) =>
		onClick &&
		css`
			&:hover {
				background-color: ${theme.colors.grey};
			}
		`}
```
Highlights in your setup? Because that seems to be fine.
I assume (without looking into the codebase) it doesn't highlight because the css tags highlighting expects to start with a block and not some key value pair. (which would maybe be invalid css in most cases?).
