### ISSUE TITLE
Typescript Types or Emotionjs adding Label to Styled break color highlighting #111

### ISSUE THREAD

**Issue by Sensiblemnd** [styled-components/vscode-styled-components#209]
![styledComponents](https://user-images.githubusercontent.com/940303/73708194-b78d0800-46cb-11ea-88b8-b5a41f84108f.PNG)
![styledComponents2](https://user-images.githubusercontent.com/940303/73708195-b78d0800-46cb-11ea-8a75-8b0bfa2aa6b4.PNG)
![styledComponents3](https://user-images.githubusercontent.com/940303/73708196-b78d0800-46cb-11ea-9331-574c775615cc.PNG)

**Comment by camsjams** [comment]
Would be fixed in https://github.com/styled-components/vscode-styled-components/pull/165

**Comment by camsjams** [comment]
This is fixed now, please close issue if you agree @Sensiblemnd
