### ISSUE TITLE
No highlighting on Nested Template Literals

### ISSUE THREAD

**Issue by theshaune** [styled-components/vscode-styled-components#21]
When using props with styled-components, it can be useful to nest a template literal to add multiple lines of styles based on a particular prop.

Unfortunately the syntax highlighting doesn't apply to nested template literals as shown in the attached image.

![image](https://cloud.githubusercontent.com/assets/3530038/25555043/1dc5195a-2d20-11e7-9e5c-378aad678e8b.png)

**Comment by julienp** [comment]
The recommended approach here is to use `css`:

<pre>${props => props.bold && css`font-weight: bold;`</pre>
