### ISSUE TITLE
Highlight does not work when using "func-call-spacing" on eslint

### ISSUE THREAD

**Issue by walze** [styled-components/vscode-styled-components#211]
Highlight does not work when using [func-call-spacing](https://eslint.org/docs/rules/func-call-spacing)  on eslint

https://eslint.org/docs/rules/func-call-spacing

![image](https://user-images.githubusercontent.com/20562991/74474567-8a3b1980-4e84-11ea-8f01-ab0183b505cc.png)

**Comment by mariusrak** [comment]
When value is function it does not highlight also, e.g.:
```javascript
const Sumbit = styled(p => <button {...p}>Send</button>)`
        width: 60px;
        border-radius: 20px;
        height: 30px;
`
```

**Comment by jasonwilliams** [comment]
@mariusrak i think you’re describing https://github.com/styled-components/vscode-styled-components/issues/201

**Comment by mariusrak** [comment]
@jasonwilliams, yes, that's it. Thanks.
