### ISSUE TITLE
Coloring conflict with Bracket Pair Colorizer

### ISSUE THREAD

**Issue by geochronology** [styled-components/vscode-styled-components#214]
I'm encountering an issue when using VSCode Styled Components combined with the popular Bracket Pair Colorizer extension.

The issue occurs when destructuring props within the styles.

Here's what my styled component looks like without Bracket Pair Colorizer: 

![image](https://user-images.githubusercontent.com/54387644/76659466-bf926000-6533-11ea-9636-f1a231747176.png)

Here's what the same component looks like when BPC is enabled: 

![image](https://user-images.githubusercontent.com/54387644/76659532-ec467780-6533-11ea-8a19-af6291ab9b6e.png)

**Comment by mbart13** [comment]
it works correctly with newer version of Bracket Pair Colorizer
https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer-2
