### ISSUE TITLE
New functionality `withConfig` fully breaks highlighting

### ISSUE THREAD

**Issue by xeladejo** [styled-components/vscode-styled-components#218]
The [new functionality](https://styled-components.com/releases#v5.1.0) `withConfig` fully breaks highlighting.

Affecting the styled-components block only:
![sreen-1](https://user-images.githubusercontent.com/63747287/81329719-429ce600-909f-11ea-93a1-9fcbb6667667.png)

Affecting the full document:
![screen-2](https://user-images.githubusercontent.com/63747287/81330002-b4752f80-909f-11ea-8d6f-38ec149f2525.png)

**Comment by mikestopcontinues** [comment]
The upstream issues ended up focusing on the wrong aspect of the problem, or at least, not the part that's causing an issue for me. Here's another example, sans TS.

<img width="452" alt="Screen Shot 2020-05-13 at 8 45 28 AM" src="https://user-images.githubusercontent.com/150434/81820322-1990b100-94f6-11ea-905b-53ab55930db1.png">

**Comment by jukkahuuskonen** [comment]
A fix for this would be appreciated.

**Comment by Stupidism** [comment]
Ain't nobody got time for that?
![image](https://user-images.githubusercontent.com/5801015/87285025-9c9bab00-c529-11ea-82ca-5e513f98af26.png)

**Comment by auver** [comment]
https://github.com/auver/vscode-styled-components/commit/b521aac89fb5e1e1b6d3a020d61bbbaf2f8628b5

like this

![image](https://user-images.githubusercontent.com/6441838/87908149-872e0000-ca98-11ea-9c4f-1e90ae4e4008.png)

**Comment by auver** [comment]
> [auver@b521aac](https://github.com/auver/vscode-styled-components/commit/b521aac89fb5e1e1b6d3a020d61bbbaf2f8628b5)
> 
> like this
> 
> ![image](https://user-images.githubusercontent.com/6441838/87908149-872e0000-ca98-11ea-9c4f-1e90ae4e4008.png)

#225
