### ISSUE TITLE
No support for typescript syntax

### ISSUE THREAD

**Issue by vincaslt** [styled-components/vscode-styled-components#22]
Specifying proptypes with typescript syntax breaks highlighting:

```
const StyledHeader = styled<Props>(Header)`
  position: fixed
  width: 100%
  background-color: ${({ theme }: Props) => theme.colors.secondary}
  height: 50px
`
```

All of the rules are highlighted with string highlighting.

**Comment by CBainx** [comment]
As far as I know, you can't specify the props that way. (Reference: https://github.com/Microsoft/TypeScript/issues/11947)
If Header is a regular component, you could remove `<Props>` and you'd still get type checking. If it's a stateless component you have to do something like whats in the docs: https://github.com/styled-components/styled-components/blob/master/docs/typescript-support.md

You can however remove `<Props>` and just replace the following line:
`  background-color: ${(props: Props) => props.theme.colors.secondary}`

**Comment by julienp** [comment]
Can this issue be closed or can someone confirm that we do need to support something like `styled<Type>`?

**Comment by clayne11** [comment]
We definitely need to support this. It's 100% allowed.

**Comment by misantronic** [comment]
+1

This could be pretty easily solved by changing the regex-statement in line 7:
https://github.com/styled-components/vscode-styled-components/blob/master/syntaxes/styled-components.json

I will try to make it work and add a pull-request
