### ISSUE TITLE
Add a colon and semicolon, as well as trigger property value completion after rule name completion

### ISSUE THREAD

**Issue by michaelschufi** [styled-components/vscode-styled-components#220]
Currently we lose out on some of VS Codes' CSS auto-completion UX. There are some features I really miss using styled-components opposed to CSS/LESS/SCSS files. (see also [this issue](https://github.com/Microsoft/vscode/issues/32200)) 

After selecting/completing the rule name, it should:

- Add a colon after the rule name
- Add a semicolon at the end of the line
- Trigger the property value completion for the completed rule

[As shown here](https://github.com/Microsoft/vscode/issues/32200#issuecomment-530574357)

![image](https://user-images.githubusercontent.com/4033249/64736903-8c95e380-d4a0-11e9-90cf-37e8e145ce84.gif)

**Comment by SrBrahma** [comment]
This is a must do. It annoys me that we have to manually insert the semicolon, even after saves.

But, is a nice extension!

**Comment by jasonwilliams** [comment]
Hey @dilincoln looks like the language server is triggered here:
https://github.com/microsoft/typescript-styled-plugin/blob/master/src/_language-service.ts#L215-L244

Maybe you could make edits to this rather than implement the feature directly?
You may need to yarn link that project to see how it's getting called.

**Comment by golfomania** [comment]
started today to learn about styled components (dev eds react course) and i totally agree, that this extended autocomplete would be great.

**Comment by seb-thomas** [comment]
https://github.com/styled-components/vscode-styled-components/issues/172#issuecomment-612857719

Fork works

**Comment by NayamAmarshe** [comment]
> [#172 (comment)](https://github.com/styled-components/vscode-styled-components/issues/172#issuecomment-612857719)
> 
> Fork works

But it's based on an older version and doesn't support newer features like color highlighting.

**Comment by NayamAmarshe** [comment]
> Currently we lose out on some of VS Codes' CSS auto-completion UX. There are some features I really miss using styled-components opposed to CSS/LESS/SCSS files. (see also [this issue](https://github.com/Microsoft/vscode/issues/32200))

This is the only thing that's making me hate styled components compared to node-sass

**Comment by jasonwilliams** [comment]
Would appreciate any help on this, see https://github.com/styled-components/vscode-styled-components/blob/master/CONTRIBUTING.md#intellisense-issues

**Comment by jasonwilliams** [comment]
This should be released in v1.6.0

**Comment by jasonwilliams** [comment]
This has now been released, ive added a gif to the readme to showcase

**Comment by Diagonet** [comment]
I see this has already been added but I can't seem to get proper autocomplete and colon/simicolon. All I want is the same behavior I can see in the gif, is there anything that could be interfering with it?

**Comment by jasonwilliams** [comment]
> I see this has already been added but I can't seem to get proper autocomplete and colon/simicolon. All I want is the same behavior I can see in the gif, is there anything that could be interfering with it?

@Diagonet please raise a new bug issue with a screenshot and code for reproducing

**Comment by jasonwilliams** [comment]
@Diagonet i think https://github.com/microsoft/typescript-styled-plugin/pull/156 may fix your issue

**Comment by Diagonet** [comment]
Yeah so, I found out I only get the proper semi-colon auto complete when I use Enter to auto complete (even thought I changed the vscode setting for Tab auto completion)

**Comment by timbam** [comment]
For anyone it can help, I had the same problem as Diagonet. Found out there's a styled-components shortcut that was set to enter instead of tab:
@ext:styled-components.vscode-styled-components
