### ISSUE TITLE
`css ... ` break syntax highlight

### ISSUE THREAD

**Issue by bexoss** [styled-components/vscode-styled-components#222]
![eeee11](https://user-images.githubusercontent.com/12633102/83322351-dd00db80-a291-11ea-9309-b7540220a058.PNG)

after css`...` break syntax hightlight.

![e3333](https://user-images.githubusercontent.com/12633102/83322353-de320880-a291-11ea-8bef-034f23678a26.PNG)

if I change css`...` ===> css[space]`...` problem is gone.

**Comment by tomasztunik** [comment]
For me, it was a conflict with `vscode-styled-jsx`. It might be worth checking if you don't have conflicting extensions installed and remove or disable them for a given workspace.

**Comment by bexoss** [comment]
@tomasztunik Wow, you are totally right. after I remove `vscode-styled-jsx` it works like charm.

**Comment by JoshuaSoileau** [comment]
Turned out being the same thing that @tomasztunik said for me, disabling `vscode-styled-jsx` fixed my syntax highlighting with `css`.
