### ISSUE TITLE
Custom Tag Names Do Not Work

### ISSUE THREAD

**Issue by contrarian** [styled-components/vscode-styled-components#224]
The linked [https://github.com/Microsoft/typescript-styled-plugin#configuration](styled-plugin configuration) says that you can specify custom tag names as follows:
```json
{
  "compilerOptions": {
    "plugins": [
      {
        "name": "typescript-styled-plugin",
        "tags": [
          "styled",
          "css",
          "sty",
         "custom!"
        ]
      }
    ]
  }
} 
```

Unfortunately, the custom tag names do not get syntax highlighting or completion. Interestingly, they do get hints (.e.g "Shorthand property for setting most background properties at the same place in the style sheet.").

**Comment by vzaidman** [comment]
+1

**Comment by mlukac-be** [comment]
+1

**Comment by mikestopcontinues** [comment]
And just for reference, it doesn't work replacing "typescript-styled-plugin" with "vscode-styled-components" either. (Not really sure of the syntax for tsconfig/jsconfig, so I figured I'd give that a whirl.

**Comment by jasonwilliams** [comment]
@mikestopcontinues could you paste some example code that isn’t getting highlighted?

**Comment by mikestopcontinues** [comment]
Hey, thanks! I'm using `astroturf@v1.0.0-beta.15`. They added a new `stylesheet` tag, so I was trying to setup the config for highlighting...

```js
const styles = stylesheet`
  .class {
    position: fixed;
  }
`;
```

**Comment by jasonwilliams** [comment]
Thanks @mikestopcontinues 
The typescript-styled-plugin only deals with intellisense. Syntax highlighting is done by us and we hardcode the tags we highlight right now.

We would need to add some more tags or just make it so it works with any tag.

Would you be up for looking at this?
We have a contributing guide here https://github.com/styled-components/vscode-styled-components/blob/master/CONTRIBUTING.md

**Comment by mikestopcontinues** [comment]
I'd actually already looked at the code. I thought I must be missing something given the config instructions. It shouldn't be too hard to update the regex. I'll give it a go.
