### ISSUE TITLE
Wrong syntax highlighting for substitutions variable in vscode

### ISSUE THREAD

**Issue by AndreaCitrolo** [styled-components/vscode-styled-components#226]
Hi everybody,
I stepped into this problem. Basically syntax highlighting is not working for variables in styled-components declarations:

![image](https://user-images.githubusercontent.com/5507598/88405954-443d9680-cdd0-11ea-9bb8-72ed96e304b1.png)
![image](https://user-images.githubusercontent.com/5507598/88406366-e198ca80-cdd0-11ea-8f99-31a00947dee8.png)

Environment:
VSCode
Version: 1.47.2 (user setup)
Commit: 17299e413d5590b14ab0340ea477cdd86ff13daf
Date: 2020-07-15T18:22:06.216Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

Extensions:
![image](https://user-images.githubusercontent.com/5507598/88406279-bf9f4800-cdd0-11ea-9744-3f1b42b8671b.png)

WSL Ubuntu-18.04

styled-components version 5.1.1

Kind regards

**Comment by ionut-botizan** [comment]
I couldn't reproduce this issue.
What I can suggest is:
1. Try a different color theme. It seems that you might be using the default "Dark" theme (not even the "Dark+") that ships with VSCode (The [Github Theme](https://marketplace.visualstudio.com/items?itemName=GitHub.github-vscode-theme) and the [Material Theme](https://marketplace.visualstudio.com/items?itemName=Equinusocio.vsc-material-theme) are both good places to start exploring custom color themes)
2. In your second example (the `someMixin` one) you're kind of overdoing it, by unnecessarily embedding a template literal into a template literal. 😀

Here's how it looks for me (note that not only the syntax highlight properly works, but IntelliSense too):

![image](https://user-images.githubusercontent.com/408501/89661569-863fff80-d8db-11ea-9a23-eb0d12aaba80.png)

**Comment by AndreaCitrolo** [comment]
I'll give it a try! Thank you for the reply.
