### ISSUE TITLE
Highlighting breaks when using attrs with parenthesis

### ISSUE THREAD

**Issue by pedrodurek** [styled-components/vscode-styled-components#227]
Hey guys, the syntax highlighting is not working properly when declaring a styled-component using attrs and parenthesis (over template literals).

![Screen Shot 2020-07-24 at 6 12 04 PM](https://user-images.githubusercontent.com/12190482/88442550-89ff5c80-cdda-11ea-8f8a-f41352c3bb35.png)

Thanks!

**Comment by a7madgamal** [comment]
yesssss, I wanted to report this too :D

**Comment by jasonwilliams** [comment]
Should be fixed in 1.0.0

**Comment by panda919** [comment]
I got same issue
