### ISSUE TITLE
Highlight does not work when typing props break into a new line

### ISSUE THREAD

**Issue by brpapa** [styled-components/vscode-styled-components#228]
I believe that the following images are self explanatory.

<img width="361" alt="Screen Shot 2020-08-15 at 22 15 25" src="https://user-images.githubusercontent.com/31225808/90324399-d30f8000-df44-11ea-89f0-0e781d4c0bab.png">

<img width="274" alt="Screen Shot 2020-08-15 at 22 15 55" src="https://user-images.githubusercontent.com/31225808/90324412-e4f12300-df44-11ea-9207-fd63c53f0893.png">

**Comment by finnp** [comment]
The main issue here is that the entire `styled.g<..>` is matched on one line right now. It's not possible to match syntax on different lines unless you're using `start` and `end`.

This needs some rethinking of how to capture this. I'm leaving the fixture code here in case anyone wants to try:

```js
export const Group = styled.g<{
    backgroundColor?: string
    foregroundColor?: string
    visited?: boolean
}>`
    &:hover {
        fill: red;
        stroke: red;
    }
`
```

**Comment by finnp** [comment]
I'm closing this in favor of #174
