### ISSUE TITLE
Highlight does not work when useing anonymous function component

### ISSUE THREAD

**Issue by daief** [styled-components/vscode-styled-components#233]
![image](https://user-images.githubusercontent.com/19222089/93754071-b812e880-fc33-11ea-9979-6f0af73974d1.png)

```tsx
const A = styled(Button)`
  display: flex;
  color: #6cf;
  width: 160px;
`;

const B = styled(({ ...props }) => {
  return <Button {...props}>button</Button>;
})`
  display: flex;
  color: #6cf;
  width: 160px;
`;
```

**Comment by umanghome** [comment]
Encountered the same issue. Would like to try fixing it if that's a possibility.

**Comment by InsaLili** [comment]
Same here. Looking forward to the fix

**Comment by jasonwilliams** [comment]
I believe his is a duplicate of https://github.com/styled-components/vscode-styled-components/issues/162 closing.

**Comment by umanghome** [comment]
See https://github.com/styled-components/vscode-styled-components/issues/162#issuecomment-706907785
