### ISSUE TITLE
Fix Styled Components highlighting for v2

### ISSUE THREAD

**Issue by kitten** [styled-components/vscode-styled-components#24]
In v2 (which will be officially released shortly, and is currently in RC) we have a few new methods which will need to be added to the syntax highlighting. The three methods are:

### `.extend`

```js
const Comp = styled.div`color: red;`

const NewComp = Comp.extend`
  color: green;
`
```

### `.extendWith()`

```js
const Comp = styled.div`color: red;`

const NewComp = Comp.extendWith('span')`
  color: green;
`
```

### `SC.attrs({})`

```js
const Link = styled.a.attrs({
  target: '_blank'
})`
  color: red;
`
```

**Comment by julienp** [comment]
Thanks for the heads up. I've implemented `.extend`, but I don't know yet how to deal with `.extendWith` or `attrs`.

**Comment by philpl** [comment]
`.extendWith` has been replaced by `withComponent` now ^^

for reference: https://www.styled-components.com/docs/api

**Comment by bessey** [comment]
I've tackled `withComponent` in #25, hope its a worthy addition

**Comment by julienp** [comment]
Merged #25, thank you @bessey !

**Comment by pluma** [comment]
Having support for `.attrs()` would be super useful. At the moment I'm avoiding that method merely because I don't want to lose syntax highlighting.

**Comment by bsutt123** [comment]
So I take it that we still don't have `.attrs()` support because I am not getting my syntax highlighting inside the component after an `.attrs()` call . I'm willing to take a wack at it, I am looking to start contributing to some open source projects but I have literally 0 experience making extensions.

Is this something that a relative newbie to vscode extensions and syntax highlighting in general should take on?

**Comment by bessey** [comment]
@bsutt123 take a look at my PR for a hint on where to start here https://github.com/styled-components/vscode-styled-components/pull/25/files.

I was new to working on VS Code extensions too, it's not too complicated, especially modifying an existing extension. I don't know if this is best practice but my approach was to checkout the github repo, and then symlink to it from my VS Code extensions folder (`~/.vscode/extensions` on Mac). Then you can pretty much live edit with the `> Reload Window` command.

Just like chrome, VS Code extensions are debugged through the developer console, which can be opened with the same shortcut as chrome. On Mac thats `Cmd+Option+I`. 

Extension authoring reference: https://code.visualstudio.com/docs/extensions/overview

**Comment by bessey** [comment]
Your challenge (and the reason I bailed on this bit) will be building a regex for that captures the JS object in the `attrs()` call!

**Comment by bsutt123** [comment]
thanks @bessey I'll take a wack at it. I am looking for stuff to contribute to anyways.

**Comment by bsutt123** [comment]
All issues are now fixed as of latest release, we should close this Issue.

**Comment by mxstbr** [comment]
Thanks @bsutt123!
