### ISSUE TITLE
Plugin doesnt work for me at all

### ISSUE THREAD

**Issue by elShailee** [styled-components/vscode-styled-components#242]
**Describe the bug (including copyable syntax)**
pretty much staight-forward  -  the plugin doesnt work for me.

**Screenshot**
![image](https://user-images.githubusercontent.com/67635802/96857993-5fb84c00-1468-11eb-8d79-dc16809ab963.png)

**To Reproduce**
i've just installed it, right after installed styled-components and made sure the module works.

**Expected behavior**
Explain what you expected to happen, and what is happening instead.

**Build environment (please complete the following information):**

- OS: win10
- VSCode Version: 1.44.0
- Extension Version: 0.0.31

**Additional context**
tried reinstalling the plugin, restarting vscde, and disabling every combination of plugins i have...

**Comment by jasonwilliams** [comment]
Hey @elShailee i can see on the bottom right your language is set to `JavaScript`, You need to be on `JavaScript React` for the plugin to work.

This is usually triggered by having a `.jsx` extension instead of `.js` (i personally find this good practise) or manually setting your language to `JavaScript React`.

**Comment by elShailee** [comment]
> Hey @elShailee i can see on the bottom right your language is set to `JavaScript`, You need to be on `JavaScript React` for the plugin to work.
> 
> This is usually triggered by having a `.jsx` extension instead of `.js` (i personally find this good practise) or manually setting your language to `JavaScript React`.
> 
> Also your version of the extension is old

At first - the js to jsx change made no difference, but thanks for the tip!
after futher messing around - the reason ext. version 1.20 didnt show for me in the first place is because its incompatible with vscode v1.44, so i upgraded to 1.50 (vscode) and reinstalled the extension.
RESULTS - the code's text remains uncolored, but now the autocomplete for css is working, so i'll settle for that.
also - the little square that indicates the color picked now shows up, but only with jsx files (always) or js files but only in Javascript React language mode.
Thanks for all the help, hopfully the text coloring could be fixed sometime, but the autocomplete was absolutely the more important feature!

**Comment by jakubziemba** [comment]
> Hey @elShailee i can see on the bottom right your language is set to `JavaScript`, You need to be on `JavaScript React` for the plugin to work.
> 
> This is usually triggered by having a `.jsx` extension instead of `.js` (i personally find this good practise) or manually setting your language to `JavaScript React`.
> 
> Also your version of the extension is old

It worked for me, thank you!
