### ISSUE TITLE
Doesn't show color preview of var in styled-components file

### ISSUE THREAD

**Issue by Krugerrgabriel** [styled-components/vscode-styled-components#243]
The color preview for code of colors show normally, but when it's a variable doesn't show :(

**Comment by jasonwilliams** [comment]
@Krugerrgabriel please fill in the issue template, we add it for a reason as it makes our lives easier when attempting to fix your problem.

 Could you add some steps to reproduce and maybe a screenshot? We will need some version info too

**Comment by Krugerrgabriel** [comment]
![Screenshot_89](https://user-images.githubusercontent.com/48792379/98249363-eb47d780-1f54-11eb-9698-49b9973f0eff.png)

**Comment by Krugerrgabriel** [comment]
![Screenshot_90](https://user-images.githubusercontent.com/48792379/98249447-01559800-1f55-11eb-98c4-a176e145fbbb.png)
Don't show the color :(

**Comment by jasonwilliams** [comment]
@Krugerrgabriel the color picker only works when it detects literal colors `#000` or `HLS()` or `RGB()`. In order for this to work it would need to trace the variable back to its definition. This is a bit more complicated than plain syntax highlighting.

My advice would be to click Bug report and raise a new feature request ticket, filling in the issue template. title the issue as a feature request.

I don't know if what you're asking for is possible but someone may be able to give it a go

**Comment by Krugerrgabriel** [comment]
So... In some videos of channel "Rocketseat" this feature works so well. But thanks for you help :)
