### ISSUE TITLE
Support Svelte

### ISSUE THREAD

**Issue by madeleineostoja** [styled-components/vscode-styled-components#246]
Similar to https://github.com/styled-components/vscode-styled-components/issues/96, it would be great if `vscode-styled-components` added support for `.svelte` files for `css` tagged literals.

Also rather than hardcoding all these file types, would it make sense to expose a configuration option for the files that the extension runs on, defaulting to the current set (I asume `vue|[jt]sx?`)?

**Comment by jasonwilliams** [comment]
@seaneking PRs are welcome, it doesn’t look too difficult to add (looking at the vue example)

> Also rather than hardcoding all these file types, would it make sense to expose a configuration option for the files that the extension runs on, defaulting to the current set (I asume vue|[jt]sx?)?

Users can already do this themselves so I don’t think we need to change how we operate here. The hard coded file extensions already act as a default

**Comment by seaneking** [comment]
> Users can already do this themselves 

How can you do it without changing the whole file association? If that's possible then all good, no need to add explicit support I guess

**Comment by jasonwilliams** [comment]
Hmm you won’t be able to do it without changing the file association. Why would you need to do this anyway? It would be good to have it “just work” for compatible files so the users shouldn’t have to do anything but install the extension.

What’s wrong with doing what we did for vue?

**Comment by seaneking** [comment]
Yeah that's what I thought. Nothing wrong at all with doing what was done for Vue, I just thought it would be more maintainable to expose a setting for filetypes rather than adding support every time a new one comes along. Didn't realise that wasn't possible though. I'm happy to attempt a PR, if I just find where Vue support was added and chuck on Svelte. I have zero experience with VS Code extensions though.

**Comment by jasonwilliams** [comment]
Should be yeah, I’ve never used Svelte so it would be hard for me to test. Do you have a typical svelte file where this extension would be used?

**Comment by jasonwilliams** [comment]
> I'm happy to attempt a PR, if I just find where Vue support was added and chuck on Svelte. I have zero experience with VS Code extensions though.

> Would it literally just be a matter of adding svelte to this array?

@madeleineostoja yes pretty much

**Comment by madeleineostoja** [comment]
👍 Made a PR
