### ISSUE TITLE
Is there any way to check styled-component outside VSCode

### ISSUE THREAD

**Issue by aspirisen** [styled-components/vscode-styled-components#247]
Hi, this is a great extension to check syntax and correct CSS properties in IDE. However, I wonder if it is possible so to say run this extension outside of IDE, for example if I need to check the code on CI or just by running CLI tool.

**Comment by jasonwilliams** [comment]
hi @aspirisen 

This extensions doesn't really do any checking per-say. Instead it: 
- highlights the relevant code
- passes on TypeScript syntax to the TypeScript language server.
- passes on CSS/SCSS syntax to the relevant languages servers.

It's not really possible or within the scope of this extension to have anything on the command line. A better place to ask this question maybe in https://github.com/styled-components/styled-components.

**Comment by aspirisen** [comment]
@jasonwilliams Yeah, but if there will be syntax error, i.e. you forgot `:` this extension will highlight it.
Anyway, thanks for answering.
