### ISSUE TITLE
Can not change Hex alpha using the color picker

### ISSUE THREAD

**Issue by OhadBaehr** [styled-components/vscode-styled-components#252]
**Describe the bug (including copyable syntax)**
```
const test= styled.div`
  background:#553845;
`
```
Hex colors do not support changing of the alpha channel in current version

**Screenshot**
![image](https://user-images.githubusercontent.com/33723454/101279404-bb495980-37ca-11eb-9cbc-cbcaacec328d.png)
![image](https://user-images.githubusercontent.com/33723454/101279417-cac8a280-37ca-11eb-8ca5-62ded6cf13f4.png)

**To Reproduce**
make an Hex color, try changing its alpha.

**Expected behavior**
The Hex string should change to accommodate for the alpha channel change.

**Build environment (please complete the following information):**

- OS: Windows
- VSCode Version: Latest
- Extension Version Latest

**Comment by jasonwilliams** [comment]
This is a limitation of d3-color, their issue is here:
https://github.com/d3/d3-color/issues/78

Ill be waiting to see if they add support for alpha values on HEX colors

**Comment by jasonwilliams** [comment]
Fixed in https://github.com/styled-components/vscode-styled-components/commit/e5afe260007e76997cb6356e94b0afd5940e16be should be released as part of v1.6.0 Its not perfect but should be an improvement over what there is today
