### ISSUE TITLE
Next js <style> tags are not being highlighted

### ISSUE THREAD

**Issue by OhadBaehr** [styled-components/vscode-styled-components#255]
I don't know if that is intentional but I would love to see this feature added.
![image](https://user-images.githubusercontent.com/33723454/101390333-5164a900-38cb-11eb-9fe1-3c389c3975f0.png)

**Comment by jasonwilliams** [comment]
@OhadBaehr would you be interested in adding this feature?
https://github.com/styled-components/vscode-styled-components/blob/master/CONTRIBUTING.md
