### ISSUE TITLE
Colour preview for css property name

### ISSUE THREAD

**Issue by patrikniebur** [styled-components/vscode-styled-components#257]
**Describe the bug (including copyable syntax)**
For the following code I get colour preview in front of the css property name which provides no value and disturbs the view.
```
	button {
		white-space: nowrap;
	}
```
**Screenshot**
<img width="194" alt="Screen Shot 2020-12-09 at 10 55 30 AM" src="https://user-images.githubusercontent.com/6452693/101546150-3c902e80-3a0d-11eb-851a-7eb8697a29a8.png">

**To Reproduce**
Use above code with styled syntax highlight

**Expected behavior**
I shouldn't get the colour preview for css property names.

**Build environment (please complete the following information):**

- OS: OSX (Darwin x64 19.6.0)
- VSCode Version: 1.51.1
- Extension Version 1.4.0

**Additional context**
Guessing from the changelog it appears to be caused by https://github.com/styled-components/vscode-styled-components/pull/249/files

**Comment by jasonwilliams** [comment]
ping @OhadBaehr
