### ISSUE TITLE
Suggestion: ability to run this tool on the cmd line

### ISSUE THREAD

**Issue by JamesZoft** [styled-components/vscode-styled-components#259]
Hi there! I've recently pored over the styled-component docs in search of a tool that would help me spot when I put incorrect css in my styled components, and although they promote stylelint, it doesnt actually seem to work at all. Is there some way I can run the css validation you do in vscode, on the command line, as yours seems to work very well?

**Comment by finnp** [comment]
Hello @JamesZoft,

I think what you need it [stylelint-processor-styled-components](https://github.com/styled-components/stylelint-processor-styled-components) to extract the css. There is more information about how to set it up here: https://styled-components.com/docs/tooling#stylelint

Does this work for you?

**Comment by dminkovsky** [comment]
FWIW, I configured/ran stylelint and it didn't seem to work well w/ Typescript. It found some real mistakes which was great, but then it failed processing some TS, with errors like:

```
pony-common/src/AuthClient.ts
 189:45  ✖  Unexpected token, expected "}" (189:45)    

pony-common/src/AuthState.ts
 127:51  ✖  Unexpected token, expected "}" (127:51)    

pony-common/src/Private/getThreadData.ts
 86:8  ✖  Unexpected token (86:8)    
```

I followed the guidance in the [FAQ](https://github.com/styled-components/stylelint-processor-styled-components#faq): made sure `@babel/parser` and `@babel/traverse` were up-to-date, and other things, but still these errors. Didn't open an issue there, though.

**Comment by jasonwilliams** [comment]
@JamesZoft have you looked at https://github.com/stylelint/postcss-css-in-js ?
The inner-workings of this extension would not work on the command line because they rely heavily on the VSCode API. It would need to be something thats built from the ground up
