### ISSUE TITLE
Highlighting doesn't work in vscode

### ISSUE THREAD

**Issue by overthestream** [styled-components/vscode-styled-components#263]
Highlighting doesn't work in vscode 1.52.1, macOS BigSur 11.1 
<img width="286" alt="image" src="https://user-images.githubusercontent.com/45127769/104288674-76b48a80-54fb-11eb-9b8c-0685f57a8429.png">

**Comment by davidetruffo** [comment]
I'm having the same issue. Is this closed because it eventually worked? if so, how? :)
