### ISSUE TITLE
css IntelliSense not show

### ISSUE THREAD

**Issue by yoodu** [styled-components/vscode-styled-components#264]
I had intalled vscode-styled-components and typescript-styled-plugin and setup tsconfig.json，bug I can't see the intelliSense of css in \` \`

<img width="682" alt="图片" src="https://user-images.githubusercontent.com/20815670/104883190-5a9f6600-599f-11eb-9f1f-d261c005c1ea.png">

tsconfig.json
```
{
  "compilerOptions": {
    "target": "ES6",
    "module": "CommonJS",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "esModuleInterop": true,
    "importHelpers": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "allowUnreachableCode": true,
    "allowUnusedLabels": true,
    "noImplicitAny": false,
    "noImplicitThis": false,
    "noUnusedParameters": false,
    "lib": ["dom", "esnext"],
    "jsx": "react",
    "strict": true,
    "pretty": true,
    "sourceMap": true,
    "allowJs": true,
    "baseUrl": ".",
    "paths": {
      "src/*": ["src/*"],
      "#/*": ["src/common/*"],
    },
    "plugins": [
      {
        "name": "typescript-styled-plugin",
        "tags": [
          "styled",
          "css",
          "sty"
        ]
      }
    ]
  },
}

```

**Comment by xon52** [comment]
I have this issue too and have not found a solution or alternative.
VSCode Version: 1.52.1
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363

vscode-styled-components version: 1.5.0

**Comment by jasonwilliams** [comment]
@yoodu you shouldn’t need to directly install the plugin, styled components extension should handle all that. Do you still have this issue?
