### ISSUE TITLE
 [Feature request] Move cursor into parentheses when using properties which invole them 

### ISSUE THREAD

**Issue by itbarbaris** [styled-components/vscode-styled-components#270]
Could you please implement a feature that would automatically move cursor into property's value parentheses when using snippets? 

For example, `transform: translate(...);`, when you start typing `transl` autocomplete dialog box appears, then when you select a snippet it completes the value `translate()` but it moves the cursor after parentheses.
![issue](https://user-images.githubusercontent.com/77689559/108805298-d5682c00-75b0-11eb-8f23-903c828d923b.gif)

**Comment by jasonwilliams** [comment]
@itbarbaris this project is looking for support if this is something you’re willing to try your hand at?

we have a contributing guide here 
https://github.com/styled-components/vscode-styled-components/blob/master/CONTRIBUTING.md

**Comment by jasonwilliams** [comment]
This should be released in v1.6.0

**Comment by jasonwilliams** [comment]
This has now been released, I've showcased the feature in the gif on the readme
