### ISSUE TITLE
All custom patterns/tags via vscode configuration

### ISSUE THREAD

**Issue by PssbleTrngle** [styled-components/vscode-styled-components#273]
**Describe the bug (including copyable syntax)**
At the moment, the vscode plugin allows to enable matching for custom tags,
but the highlighting is not able to be configured for custom patterns.

**Expected behavior**
It would be great if there was a possibility to configure custom tags or even patterns in the vscode settings of a project.

**Comment by jasonwilliams** [comment]
Unless it can be figured out via https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide i don't see this being possible. 

Ill leave it open as a future enhancement but it would be difficult to dynamically update the syntax based on custom tags.

**Comment by jasonwilliams** [comment]
Closing as a duplicate of https://github.com/styled-components/vscode-styled-components/issues/303
