### ISSUE TITLE
Unknown property: 'user-drag'ts-styled-plugin(9999)

### ISSUE THREAD

**Issue by Androidest** [styled-components/vscode-styled-components#274]
The 'user-drag' property works well in styled-component, but there is an underline showing that the property is unknown. Is this a problem with the vscode-styled-components extension?

![image](https://user-images.githubusercontent.com/10008376/109901805-9b93d580-7cd4-11eb-9a61-6da31904f3fc.png)

![image](https://user-images.githubusercontent.com/10008376/109901759-89b23280-7cd4-11eb-8cc3-b597bc34f53d.png)

**Expected behavior**
No underline appears while using 'user-drag' property

**Build environment**

- OS: Windows_NT x64 10.0.18363
- VSCode Version: 1.53.2 (System setup)
- Extension Version v1.5.0

**Comment by jasonwilliams** [comment]
So I think definitions come from ts-styled-plugin -> vscode-css-languageservice -> https://github.com/mdn/data 

So any unknown properties would need to be taken up with https://github.com/mdn/data

**Comment by mikestopcontinues** [comment]
@jasonwilliams I'm using standard properties like `margin-inline` and getting the error. I understand not wanting to get in the way of upstream configuration—but I think we should have an option to disable `typescript-styled-plugin`. Or maybe it shouldn't even be included with this plugin? I've got `stylelint` already and it doesn't flag these. For that reason, I think this ticket should be reopened. Thanks!

**Comment by jasonwilliams** [comment]
@mikestopcontinues do you mind creating a new issue with the title around being able to switch of the styled plugin? I won’t have time to work on it but will accept PRs
