### ISSUE TITLE
Pressing return after back-ticks does not jump to new line, selects first result of intellisense

### ISSUE THREAD

**Issue by mmckinley8** [styled-components/vscode-styled-components#276]
**Describe the bug (including copyable syntax)**
When creating a styled component, pressing return after a back tick does not add a space and auto-indent the way it should.  In fact, it selects the first result from intellisense and does not jump to the next line. This is a very glaring issue and slows down productivity.

**Screenshot**
Atom (how it should behave):
<img width="416" alt="Screen Shot 2021-03-10 at 2 07 23 PM" src="https://user-images.githubusercontent.com/11301364/110690967-2a5b9300-81aa-11eb-9f1f-2a8241369211.png">

VS Code:
<img width="527" alt="Screen Shot 2021-03-10 at 2 11 19 PM" src="https://user-images.githubusercontent.com/11301364/110691218-7f97a480-81aa-11eb-972e-e6b05da5a468.png">

**To Reproduce**
Create a styled components, press enter after back tick

**Expected behavior**
I expect the trailing back tick to jump two lines below the leading, and the cursor to be indented on the line in between the back ticks.

**Build environment (please complete the following information):**

- OS: MacOS Big Sur 11.2.3
- VSCode Version: 1.54.1
- Extension Version 1.5.0

**Additional context**

**Comment by jasonwilliams** [comment]
Thanks for raising this @mmckinley8 I appreciate the detailed bug report. I have noticed this too, but sadly not have time to look at it. We are looking for [contributors](https://github.com/styled-components/vscode-styled-components/issues/275) at the moment.

Did you want to contribute to fixing this bug?

The logic lives [here](https://github.com/styled-components/vscode-styled-components/blob/master/src/completionItemProvider.ts) and we have a [contributing guide](https://github.com/styled-components/vscode-styled-components/blob/master/CONTRIBUTING.md) also.

**Comment by jasonwilliams** [comment]
👋 @jrieken do you know how we can override completions so that ours will be top? Even though we add our snippet in directly it’s sometime halfway down the list.

**Comment by jasonwilliams** [comment]
@mmckinley8 is this still an issue in the latest version?

**Comment by jasonwilliams** [comment]
https://github.com/microsoft/typescript-styled-plugin/pull/157 should help with this

**Comment by emfresh2o** [comment]
Hello,

i am wonderng why am i getting syntax error in VSCODE using style component.  The problem is when using styled component with the 'tick mark'... when I start to type in 'tick mark' it actually doesn't create the pair... and what happens I need to create another one to put my style in... why is this happening? HELP!  (attached screenshot) 
<img width="319" alt="tickmark" src="https://user-images.githubusercontent.com/61608534/144088789-ff2e2afd-40c1-46fa-adc6-ad50d09bc74f.png">

**Comment by jasonwilliams** [comment]
@emfresh2o im not sure I understand your problem. Could you post a video here?

**Comment by codewithmalik** [comment]
Install vscode-styled-components on visual code extension
