### ISSUE TITLE
Question: is there a way to run this on all project files?

### ISSUE THREAD

**Issue by dminkovsky** [styled-components/vscode-styled-components#279]
Works great in VSCode, thank you.

I am wondering: is there a way to run many files through this or https://github.com/Microsoft/typescript-styled-plugin? I would like to scan for problems in all my .ts files.

I have tried configuring `typescript-styled-plugin` in `compilerOptions.plugins` and running `tsc`, but I do not see errors that I see in VSCode.

**Comment by jasonwilliams** [comment]
Hi @dminkovsky this sounds like a duplicate to https://github.com/styled-components/vscode-styled-components/issues/259 can I close?

**Comment by dminkovsky** [comment]
Yes it is. I looked and didn't find that one. Thanks a lot.
