### ISSUE TITLE
Publish to npm?

### ISSUE THREAD

**Issue by justinfagnani** [styled-components/vscode-styled-components#285]
This package is used as a dependency by [vscode-lit-plugin](https://github.com/runem/lit-analyzer/tree/master/packages/vscode-lit-plugin). Right now it has to install as a Git dependency, but has been fragile.

Would it be possible to publish vscode-styled-components to npm for downstream dependents?

**Comment by jasonwilliams** [comment]
Hi @justinfagnani how does VSCode out plugin use this?

**Comment by justinfagnani** [comment]
To be honest, I'm not exactly sure yet. I'm trying to ramp up on the library to help maintain it.

Here's the dependency on it: https://github.com/runem/lit-analyzer/blob/780b3b8977d7f3dc84a544d6f6492371fea2386e/packages/vscode-lit-plugin/package.json#L39

But I can't actually see where it's imported into any code or referenced in settings. Would its mere existence in node_modules cause it to work?

**Comment by justinfagnani** [comment]
And here's a PR to upgrade to a newer version of `vscode-styled-components`, but I guess we can't upgrade to latest because of a git hook: https://github.com/runem/lit-analyzer/pull/170 I think that would be solved by an npm package.

**Comment by justinfagnani** [comment]
I see now how it's wired in: vscode-lit-plugin injects the grammar from styled-components here in package.json: https://github.com/runem/lit-analyzer/blob/efc64a88c157ad3b73bf3b2a21aa8b6dc96ef0ea/packages/vscode-lit-plugin/package.json#L713

If that's all that's needed for that extension to use part of styled-components, it does seem nicer to depend on an npm package, which would let it upgrade to the latest version.

**Comment by 43081j** [comment]
we still need this for lit-analyzer btw. we depend on a git tag at the min which means your `prepare` script runs, causing two problems:
* it tries to run yarn, which you don't list in your dev dependencies, so won't exist
* it tries to install husky, which won't work in a non-git directory

if you can publish to npm, all these problems are solved and the prepare script doesn't matter

**Comment by justinfagnani** [comment]
@43081j I've resorted to just copying the syntax files into our repo in this branch: https://github.com/runem/lit-analyzer/tree/update-stuff/packages/vscode-lit-plugin/syntaxes

**Comment by jasonwilliams** [comment]
That’s fair, it’s not me trying to be awkward but this is a VSCode extension, once we start supporting a package on npm it opens up more things we need to maintain. I’m pretty sure you can extend grammar but that would require this extension to be installed, it may not be ideal for you but that may be cleaner.
