### ISSUE TITLE
withConfig not supported

### ISSUE THREAD

**Issue by tolnai** [styled-components/vscode-styled-components#29]
When using withConfig it doesn't recognize css code. When removing withConfig it works correctly.

```
const Foo = styled.div.withConfig({ displayName: 'Foo' })`
  display: flex;
`;
```

**Comment by third774** [comment]
This seems to also be the case with the `attrs` method.

```js
const Foo = styled.div.attrs({ className: 'Foo' })`
  display: flex;
`;
```

**Comment by bsutt123** [comment]
Apparently, all issues are related to `attrs` highlighting. `withConfig` is no longer supported when I look at styled components side and `attrs` is now highlighted.

**Comment by mxstbr** [comment]
`.withConfig` should never be used directly. Thanks for the ping, closing!

**Comment by javialon26** [comment]
Hello, styled component was updated and now support the withConfig api for shouldforwardprop:

https://github.com/styled-components/styled-components/blob/master/CHANGELOG.md#v510---2020-04-07

I think we need the support for withConfig now.

Thanks!
