### ISSUE TITLE
This extension seems to affect or override: editor.acceptSuggestionOnEnter VSCode setting

### ISSUE THREAD

**Issue by madeinchema** [styled-components/vscode-styled-components#291]
After enabling/disabling my VSCode extensions, it seems that this is the extension that is somehow overriding the VSCode setting "editor.acceptSuggestionOnEnter".

**To Reproduce**
- Have this extension enabled
- Have this VSCode setting: "editor.acceptSuggestionOnEnter": "off"

**Expected behavior**
- When shown a suggestion, clicking "Enter" adds a new line.

**Result**
- When shown a suggestion, clicking "Enter" accepts the suggestion.

**Build environment:**
- OS: Windows 10 (WSL2)
- VSCode Version: 1.56.2
- Extension Version: 1.6.1

**Comment by GuskiS** [comment]
I'm facing something similar where this extension hijacks editor controls when I'm writing TS code not related with styled components. Here are couple of examples where `|` is meant to be cursor:
broken in 1.6.1:
```
warn| -> snippet -> console.warn|()
store.camera.z| -> autocomplete -> store.camera.zoo|m
```

working in 1.5.2:
```
warn| -> snippet -> console.warn(|)
store.camera.z| -> autocomplete -> store.camera.zoom|
```

**Comment by jasonwilliams** [comment]
Thanks for raising this, it sounds like we may need to roll back this feature

**Comment by jasonwilliams** [comment]
I think it’s possible to only enable this if it’s a css property on the suggestion. It may take a bit of time to get this right but hopefully it can be resolved

**Comment by jasonwilliams** [comment]
@GuskiS your issue is fixed for now. @madeinchema ill need to find some way to revert back to the original keybinding of `Enter` which is somehow difficult to find

**Comment by jasonwilliams** [comment]
Fixed in https://github.com/styled-components/vscode-styled-components/releases/tag/v1.6.3

**Comment by hmarques98** [comment]
With me when I on enter suggestion in component instead of to show `width=` is showing `width: ;`

How to fix that? May anyone help me?

**Comment by jasonwilliams** [comment]
@hmarques98 please raise a new issue. That is unrelated to this.
