### ISSUE TITLE
Extension causes incorrect cursor placement in snippets

### ISSUE THREAD

**Issue by jacksonhardy** [styled-components/vscode-styled-components#295]
Issue Type: <b>Bug</b>

When this extension is enabled, I'm finding that one of my frequently-used snippets is being inserted with incorrect cursor position, and when tabbing to the next step of the snippet, unexpected code insertion is taking place. 

This is the snippet in question:
  ```
  "TS useState": {
		"prefix": "tsus",
		"body": ["const [${1}, set${1/([a-z])(.*)/${1:/upcase}${2}/}] = useState<${3}>(${2});${0}"],
		"description": "useState for typescript"
	},
```

Expected behavior
```
    const [{cursor}, set{cursor}] = useState<>()
```
Actual behavior
```
    const {cursor}[,se{cursor}t] = useState<>()
```
Extension version: 1.6.1
VS Code version: Code 1.56.2 (Universal) (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:44:30.902Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 6, 6|
|Memory (System)|32.00GB (5.03GB free)|
|Process Argv|--crash-reporter-id 3aa111e9-790b-40f7-94f8-133db785909a|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30291415
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
vscoreces:30290705
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2ct:30301613
vscorehov:30302759
bridgeflight:30302069
vscod805:30301674

```

</details>

**Comment by jasonwilliams** [comment]
Should be fixed by https://github.com/styled-components/vscode-styled-components/commit/ff307c3a97c409ab83f9f6845ca94fc099457883
