### ISSUE TITLE
Auto-completion affects non-styled syntax which resulting in semicolon suffix in Object.

### ISSUE THREAD

**Issue by iamyoki** [styled-components/vscode-styled-components#299]
## Description
When I typing inside original style, it triggers vscode-styled-components auto-completion with semicolon suffix.

**Screenshot**
![2021-05-28 14 11 54](https://user-images.githubusercontent.com/74389358/119939119-ef564800-bfbf-11eb-8230-a628ee959152.gif)

## Expected behavior
Don't bother original style syntax.

## Build environment (please complete the following information):

- OS: 11.2.2 (20D80)
- VSCode Version: 1.56.2
- Extension Version 1.6.3

**Comment by iamyoki** [comment]
I switched to v1.5.2, and it's fine.

**Comment by anasyusef** [comment]
This issue also seems to happen when autocompleting React component props.

**GIF**
![styled-components-bug](https://user-images.githubusercontent.com/12603278/120926258-0984da00-c6d4-11eb-8e68-061b9ac6dcc6.gif)

**Comment by gluons** [comment]
Does it have any config to disable this feature?  
I don't want to disable this extension but this problem bother me. 😰

**Comment by anasyusef** [comment]
You can change the version back to 1.5.2 as suggested by @iamyoki

**Comment by jasonwilliams** [comment]
I will put in an option to toggle this feature

**Comment by jasonwilliams** [comment]
Is someone able to knock up a small test case? Im unable to reproduce this issue :/
When i try to use style i don't get the auto complete in those situations. 

I think it may be fixable without having to disable it but for that i need a tiny test case

**Comment by iamyoki** [comment]
![QQ20210805-164840-HD](https://user-images.githubusercontent.com/74389358/128321707-4c03b560-9581-4ed2-869d-684442e808a6.gif)

@jasonwilliams  I tried to find a way to reproduce it, but I don't know how...

However, I found it was caused by 'extension.insertColonOrSemiColon' command.
Source code at [https://github.com/styled-components/vscode-styled-components/blob/4c059a3f203aea2cb62508608df03bcd12fd4a84/src/insertColonCommand.ts#L27](here)

**Comment by jasonwilliams** [comment]
Hmm I think we should just get rid of this feature and hope the typescript css/sass service can provide it instead. @RJWadley id accept a PR which just removes this command
