### ISSUE TITLE
Inconsistent highlighting?

### ISSUE THREAD

**Issue by apiep** [styled-components/vscode-styled-components#3]
I think, this picture will tell everything 😁 
![inconsistent-hightlighting](https://cloud.githubusercontent.com/assets/20897748/20263522/b305dcc0-aa99-11e6-9f01-3523cef10e15.png)

**Comment by julienp** [comment]
Thank you for the bug report! I forgot to handle the case where you pass a tagname `styled`.

**Comment by julienp** [comment]
Fixed in b14fbb9f95550b30a6d0998362fbee5b5173fdd1
