### ISSUE TITLE
Attached additional props not supported

### ISSUE THREAD

**Issue by F4b1n0u** [styled-components/vscode-styled-components#30]
first, I wanted to thank you :)
I really like your plugin !
but unfortunately it doe snot support attached additional props
https://www.styled-components.com/docs/basics#attaching-additional-props

if you could have a look to it it could help me to sleep at night :p

**Comment by aharl** [comment]
I really love the `.attrs` constructor but vscode colors the tagged template literal as a string when its used. I've attached a screenshot showing this.

![styledcompissue](https://user-images.githubusercontent.com/343228/31412405-35952876-add2-11e7-91b1-d3f645f0dbe1.PNG)

**Comment by martynhoyer** [comment]
Just came across this myself, but in a slightly different scenario which may prove useful: 

![image](https://user-images.githubusercontent.com/5610747/31545402-3ba75ab2-b017-11e7-8d96-934a47f2a445.png)

The `extend` usage loses syntax highlighting, but it is maintained with `styled(Component)` usage.

**Comment by bsutt123** [comment]
Extend and Attrs are both supported now as of the latest release. Can we close this issue?

**Comment by mxstbr** [comment]
Yep, good catch @bsutt123, thanks!
