### ISSUE TITLE
No code autocompletion for `@media` queries. 

### ISSUE THREAD

**Issue by Profesor08** [styled-components/vscode-styled-components#302]
**Describe the bug (including copyable syntax)**
No code autocompletion for `@media` queries. And if you type `@media` and press `(` key, it will replace entire string with `@:-moz-user-disabled()`

**Screenshot**
![vsc](https://user-images.githubusercontent.com/8218016/120470416-29eb2680-c3ac-11eb-9ce1-ccb130e3bd7f.gif)

**To Reproduce**
1. Install VScode if you don't have
2. Install `vscode-styled-components`
3. Create some .tsx component
4. Type `@media` or type `@media` and press `(`

**Expected behavior**
I want to see `@media` in autocomplete list and if I type `@media(`, it must not be replaced with `@:-moz-user-disabled()`

**Build environment (please complete the following information):**

- OS: Windows
- VSCode Version: 1.56.2
- Extension Version: v1.6.4

**Additional context**
May be I miss some additional configuration or extensions?

**Comment by jasonwilliams** [comment]
Thanks for raising @Profesor08 that indeed does look like a bug. Would you be interested in working on it?

**Comment by jasonwilliams** [comment]
Sadly its an upstream issue, you'll need to keep an eye on https://github.com/microsoft/typescript-styled-plugin/issues/141
I don't think the CSS language server offers any auto complete for `@media`, when i run it in CSS i only get emmet auto complete 

It could be as simple as updating `vscode-emmet-helper` on https://github.com/microsoft/typescript-styled-plugin

**Comment by jasonwilliams** [comment]
@Profesor08 a nice change would be adding a new auto completion in our [completionsProvider](https://github.com/styled-components/vscode-styled-components/blob/master/src/completionItemProvider.ts) that would help with the issue

**Comment by jasonwilliams** [comment]
@Profesor08  when you hit Enter on `@media` what do you expect to happen?

**Comment by Profesor08** [comment]
> @Profesor08 when you hit Enter on `@media` what do you expect to happen? To have braces open up or something else?

I don't hit `Enter`, I type `@media` and then hit `(`, and expect to have `@media()` with cursor between brackets. As you can see on image, there is no sugestions for `@media` query, only some vendor specific things.
![image](https://user-images.githubusercontent.com/8218016/131253496-fff7446a-a5de-483f-bc84-37b05ba627b2.png)

Erlier I have tried to figure out why this happens, but no results.

**Comment by jasonwilliams** [comment]
> Erlier I have tried to figure out why this happens, but no results.

because there is no such completion, one would need to be added

**Comment by jasonwilliams** [comment]
Fixed by: https://github.com/microsoft/typescript-styled-plugin/pull/156

**Comment by Profesor08** [comment]
> Fixed by: [microsoft/typescript-styled-plugin#156](https://github.com/microsoft/typescript-styled-plugin/pull/156)

Is there an easy way to check if it working, and not broke anything? I don't know what exactly changed in vscode, but now I can't reproduce this bug, popup is the same, but `@media` is remaining when I type `(`. The most anoing thing is just gone with time.

**Comment by kevincharp** [comment]
Since 2018 this problem has not been solved? 

Was there any solution/configuration to get autocompletion or suggestions when using media querys in css files?

![image](https://github.com/microsoft/vscode/assets/85292141/cab66965-235d-485b-aae6-0cd481a79d4e)
