### ISSUE TITLE
Duplicates #261 - Hightlighting doesn't work with nested template string and with css helper

### ISSUE THREAD

**Issue by Avivhdr** [styled-components/vscode-styled-components#304]
A while back I open issue #261 and this issue was closed due to [this pull request](https://github.com/styled-components/vscode-styled-components/commit/174cdc62854edc203d13e97e3c1d386bdd1b13e5) being merged.

Despite this merge, The issue still occurs on my VSCode.

I'm currently on version 1.6.4, but I see no change.
In this screenshot you can see that the CSS inside the template function is not being taken care of:

![image](https://user-images.githubusercontent.com/23265867/120891920-89933d00-c60b-11eb-81d4-0197cd3a68cd.png)

A reminder: this works properly in this [sandbox](https://codesandbox.io/s/styled-components-oqll7?file=/test.js), but it also did before version 1.5 (the version with the fix). So the issues do not occur in CodeSandbox. only on my IDE.

Thank you!

**Comment by jasonwilliams** [comment]
@Avivhdr as the issue template asks, can you provide some pastable code? I don’t want to re-type out everything in your screenshot 😄

**Comment by Avivhdr** [comment]
Of course!
I forgot to mention that in the initial issue there were 2 options to deal with my syntax:
   1. using `css` helper.
   2. not using `css` helper.

They were both not working properly.
I see now that the pull request **did** fix the 2nd scenario, so for me, it is not an issue anymore.

The first option is still problematic but I'm not sure that this is a bug.
You can see in the code is also in this [CodeSandBox](https://codesandbox.io/s/styled-components-oqll7?file=/test.js) test.js:20-25

```
const box1 = styled.div`
  ${setMediaQuery("medium")`
    display: grid;
    grid-template-columns: repeat(9, 1fr);
    grid-column: 6/11;
    color: red;
  `}

  ${setMediaQuery("big")(css`
    display: grid;
    color: ${myColor};
    color: red;
    grid-column: 6/11;
    grid-template-columns: repeat(9, 1fr);
  `)}
`;

const box2 = styled.div`
  display: grid;
  grid-template-columns: repeat(9, 1fr);
  grid-column: 6/11;
  color: ${myColor};
`;
```

**Comment by Profesor08** [comment]
@Avivhdr Try to play with [#tags](https://github.com/Microsoft/typescript-styled-plugin#tags), and may be you shoul make some refactoring for your `setMediaQuery` and move it calls to some defined constants, like `mediaMedium`, `mediaBig`.

**Comment by jasonwilliams** [comment]
Tags will enable intellisense but highlighting is specific to `styled`. What is `setMediaQuery` can you tell us where this comes from? Is it defined above or from an API? 

Anyway, a fix is most likely in https://github.com/styled-components/vscode-styled-components/issues/303

**Comment by Avivhdr** [comment]
`setMediaQuery` can be seen [here, in my original sandbox](https://codesandbox.io/s/styled-components-oqll7?file=/test.js): line 6.

It's basically a function that receives the desired query size and returns a function that takes the CSS style (inside the template string) and returns the proper media query.

I wanted to abstract my media queries to one source of truth, instead of defining them again and again all over my codebase.
This way, if I want to change the queries, I can do it in one function and it will affect the entire app.

@Profesor08, I do plan to convert this app from JS to TS, but now it is not TS. The `tags` link you provided is being used in 
[typescript-styled-plugin](https://github.com/Microsoft/typescript-styled-plugin) so i can't use it yet.

**Comment by Avivhdr** [comment]
But in case it was not clear, this issue is not an issue for me anymore (and can be closed if you don't see a problem).
I'm using the `css` helper and it works perfectly.

**Comment by jasonwilliams** [comment]
Thanks, this ticket is basically asking for custom tags which is the same as the duplicate one so I’m closing this
