### ISSUE TITLE
No intellisense and a little bit of syntax highlighting 

### ISSUE THREAD

**Issue by donomron** [styled-components/vscode-styled-components#306]
**Describe the bug (including copyable syntax)**
I have installed vscode-styled-components and added a simple file with language set to `javascriptreact`. I'm importing the default `styled`. There seems to be no intellisense available even when I press `ctrl + space`. 
Syntax highlighting is kind of odd. It is definitely enabled but is not exactly like the `scss` version.

**Screenshot**
![vscode](https://user-images.githubusercontent.com/8871653/121701993-b7362580-cae6-11eb-8cce-3ed1d7726bde.jpg)

**To Reproduce**
Create two files with same styles. `styles.js` and `styles.scss`

**Expected behavior**
Same color in syntax highlighting and auto complete.

**Build environment (please complete the following information):**

- OS: windows 10 enterprise. version 1909
- VSCode Version: 1.56.2
- Extension Version v1.6.4

**Comment by jasonwilliams** [comment]
please re raise if this is still an issue
