### ISSUE TITLE
Highlighting break using css function into templates

### ISSUE THREAD

**Issue by vimaciel** [styled-components/vscode-styled-components#310]
**Describe the bug (including copyable syntax)**
Highlighting doesn't work when uses the `css` function in templates

**Screenshot**
![image](https://user-images.githubusercontent.com/13278596/124051032-0e4a5e80-d9f2-11eb-9ad4-d028a0d1f2e1.png)

**To Reproduce**
Open up the snippet below on `vscode` 
_don't forget to install the vscode-styled-components plugin_

```js script  
import styled, { css } from 'styled-components'

const Button = styled.button`
  background: transparent;
  ${(props) =>
    props.primary &&
    css`
      background: green;
    `};
`
const Span = styled.span`
  font-size: 12px;
`
```

**Expected behavior**
As you can see on the screenshot, css into templates causes this issue.
You have may notice, It doesn't work into the css and every code after that.

**Build environment (please complete the following information):**

- OS: Linux Ubuntu 18.04.5
- VSCode Version: 1.57.1
- Extension Version 1.6.4

**Additional context**
Would be a pleasure to work on it if needed.

**Comment by lambrosx77** [comment]
Hi,

Same bug here with attrs().

**Comment by jasonwilliams** [comment]
> Would be a pleasure to work on it if needed.

Yes please! see the contribution guide.

**Comment by callmeberzerker** [comment]
@vimaciel you started on this right? :)

Just to know if I should dig into this when I have spare time 😅

**Comment by eric-burel** [comment]
Lost googlers, please check: https://github.com/styled-components/vscode-styled-components/issues/208#issuecomment-646606763

`vscode-styled-jsx` may create issue with Styled Components syntax highlighting, you can disable it in Styled Components projects.

**Comment by jasonwilliams** [comment]
> vscode-styled-jsx

Hey @eric-burel whats the reason of using that extension these days? Isn’t jsx/tsx support now baked in? I’ve never needed a plugin for that

**Comment by eric-burel** [comment]
@jasonwilliams this is for styled-jsx precisely, the styling solution embedded in Next.js. They basically add  CSS-in-JS within normal `<style>` tag. So I think yes you would need that in Next.js projects using Styled JSX.

**Comment by jasonwilliams** [comment]
> @jasonwilliams this is for styled-jsx precisely, the styling solution embedded in Next.js. They basically add CSS-in-JS within normal `<style>` tag. So I think yes you would need that in Next.js projects using Styled JSX.

@eric-burel so I’m assuming if you have styled components extension you’ll never need it?

**Comment by eric-burel** [comment]
Currently, styled JSX is the defautl styling solution of Next and you cannot completely remove it as far as I can tell. I am developing a framework, Vulcan, where we provide also Material UI v5 which relies either on Emotion or Styled Components. So indeed, end users should pick one and only one, but I may not know that in advance (+ it's not obvious that it can cause bug).

Is it possible for the plugin to detect other incompatible plugin for instance? It's be pretty awesome to print a clean message in this scenario.

**Comment by jasonwilliams** [comment]
Yes

https://code.visualstudio.com/api/references/vscode-api#extensions

**Comment by jasonwilliams** [comment]
This has been addressed in  https://github.com/styled-components/vscode-styled-components/commit/2059975990e5948fc5b6b24671c4fbbd3bd174d6

**Comment by vimaciel** [comment]
@jasonwilliams Sorry for the delay, after opening this issue a high demand came up to me. I'm so sorry.
