### ISSUE TITLE
IntelliSense not working

### ISSUE THREAD

**Issue by codingknite** [styled-components/vscode-styled-components#311]
I've installed the plugin and as far as I know, the syntax highlighting within the backticks is working but IntelliSense is not working.

I have tried to troubleshoot using some of the information in issue #118 but still doesn't work.

![sshot](https://user-images.githubusercontent.com/70036189/125279201-58014600-e31c-11eb-9296-cdf7006c5171.png)

- OS: Windows

- VSCode Version: 1.58.0
- Extension Version: 1.6.4

**Comment by jasonwilliams** [comment]
@codingknite could you put together a minimal test case that’s reproducible

**Comment by vasilev-alex** [comment]
@jasonwilliams I believe it's suggested because of the `Natural Language Search`

**Comment by vasilev-alex** [comment]
we should ask @codingknite

**Comment by codingknite** [comment]
**UPDATE**
I'm not sure if this issue should still remain open. Few weeks after this encounter I went back to the project and it seemed to be working. The behavior was unusual and I'm not sure what could've been the possible cause.

**Comment by animeshdas2000** [comment]
> Ok I’m closing please raise if it returns

I am facing this issue. Please let me know if I should open a new issue 

![image](https://user-images.githubusercontent.com/40542456/152940692-bc3d4ec4-7451-4965-985e-e6d231975eda.png)

**Comment by jasonwilliams** [comment]
@animeshdas2000 see pinned issues before opening issue. There’s 2 at the top already
