### ISSUE TITLE
Add intellisense for shadows in styled components for React Native.

### ISSUE THREAD

**Issue by Hmoulvad** [styled-components/vscode-styled-components#315]
Hey could you add intellisense for React Native shadow attributes for styled components?

All of below is valid and is working.
```
shadow-color: #000;
shadow-offset: {width: 0, height: 2};
shadow-opacity: 0.8;
shadow-radius: 2;
elevation: 1;
```

**Comment by jasonwilliams** [comment]
Please see https://github.com/styled-components/vscode-styled-components#i-get-unknown-property-x-on-a-property-i-know-is-valid
