### ISSUE TITLE
Support for styled-properties

### ISSUE THREAD

**Issue by djhi** [styled-components/vscode-styled-components#32]
Hi! First, thanks for this extension :)

Would you mind adding support for https://github.com/codepunkt/styled-property ?

**Comment by bsutt123** [comment]
@julienp is this something that you have the desire to support? I think I can see how to make the regex pretty easily but I'm not trying to add support for  a feature that you don't really want in the first place.

**Comment by mxstbr** [comment]
We probably won't support any custom syntax or extension of styled-components in the same repository, but @djhi you're happy to fork the package if you really need this!
