### ISSUE TITLE
Vscode File Icon

### ISSUE THREAD

**Issue by Rallanvila** [styled-components/vscode-styled-components#329]
I've been searching online on how to possibly have all files in VSCode that have an extension of .styled.js have the styled component logo instead of the JS logo. 

I'm sorry if this might be a repetitive question but I can't seem to find an answer or a fix for this. It'd be nice to have this functionality to quickly identified the styled-components files. 

The only reference that I can see close to this is [](https://github.com/vscode-icons/vscode-icons/issues/2201)

**Comment by jasonwilliams** [comment]
There's no guarantee something with styled.js is a styled-component so it isn't a path I would want to go down.  It feels like the benefits don't outweigh the costs here
