### ISSUE TITLE
Mark styled string contents as css embeddedLanguage

### ISSUE THREAD

**Issue by mjbvz** [styled-components/vscode-styled-components#33]
**Problem**
Styled template strings are currently marked as `language: javascript`

![screen shot 2017-09-18 at 12 42 45 pm](https://user-images.githubusercontent.com/12821956/30561166-f48403ee-9c6e-11e7-802c-935fe828f02a.png)

It should be `css` instead. The language mode effects editor features such as bracket matching.

**Fix**
VSCode has an `embeddedLanguages` setting that marks language mode.  We just added support for using `embeddedLanguages` with an an injected grammar: https://github.com/Microsoft/vscode/issues/34316

I'll submit a PR that does this for this extension

**Comment by mjbvz** [comment]
This will also fix #13

**Comment by julienp** [comment]
Thanks! Sorry for the delays, I’m traveling.  I’ll merge this and release a new version once I get home in a couple of weeks.

**Comment by jinalskothari** [comment]
@mjbvz , will this provide basic css syntax intellisense & highlighting (similar to working on a .css file?) or would I still need to use your plugin https://github.com/Microsoft/typescript-styled-plugin ?

**Comment by mjbvz** [comment]
@jinalskothari No, this change does not add intellisense
