### ISSUE TITLE
Missing autocomplete and syntax highlighting for newer CSS properties

### ISSUE THREAD

**Issue by florianbuehler** [styled-components/vscode-styled-components#335]
Currently autocomplete and syntax highlighting is not working for some newer CSS properties (e.g. `accent-color`, `ascent-override`, `descent-override`, line-gap-override` and `size-adjust`.)

**Screenshot**
![current - autocomplete](https://user-images.githubusercontent.com/77963076/142178349-e9dfa050-1d9f-4b50-81ae-c905adb63133.jpg)
![current - highlighting](https://user-images.githubusercontent.com/77963076/142178363-bdff05ce-08d6-423b-9d26-f7c2506d86cd.jpg)

The autocomplete will be fixed with PR [https://github.com/styled-components/vscode-styled-components/pull/333](https://github.com/styled-components/vscode-styled-components/pull/333).

However the syntax highlighting depends on [https://github.com/microsoft/vscode/blob/main/extensions/css/syntaxes/css.tmLanguage.json](https://github.com/microsoft/vscode/blob/main/extensions/css/syntaxes/css.tmLanguage.json) which again depends on [https://github.com/atom/language-css/blob/master/grammars/css.cson](https://github.com/atom/language-css/blob/master/grammars/css.cson).

So we are dependend, that they adapt their css grammar.

**Comment by jasonwilliams** [comment]
@florianbuehler ive just tested this in a native css file and there's no syntax highlighting there either.  So it looks like https://github.com/microsoft/vscode/blob/main/extensions/css/syntaxes/css.tmLanguage.json hasn't updated yet. Maybe when that updates it will just work here too.

You probably need to raise this further upstream.
https://github.com/microsoft/vscode/pull/132199 which is waiting on https://github.com/atom/language-css/pull/184

**Comment by florianbuehler** [comment]
@jasonwilliams, you are right. I also raised it upstream. ([issue](https://github.com/atom/language-css/issues/189) and [fix](https://github.com/atom/language-css/pull/188)).

However there was already a pull request to fix the `accent-color` (but not the other CSS properties) quite some time ago but nothing happened till now.
