### ISSUE TITLE
We need to change the publisher of this extension

### ISSUE THREAD

**Issue by jasonwilliams** [styled-components/vscode-styled-components#338]
The access token of @julienp expired today, so we can't publish for a while until this is sorted out. 
I think this may be a good time to change the ownership of the extension and move it under styled-components. 

Annoyingly there's [no easy way](https://github.com/microsoft/vscode/issues/4772) to do that with VSCode's marketplace. So I think we'll need to unpublish the extension and publish again from under the styled-components namespace. 

Until we can sort this there'll be now releases for now

**Comment by jasonwilliams** [comment]
The new extension lives here: https://marketplace.visualstudio.com/items?itemName=styled-components.vscode-styled-components 

Make sure you change it in your config, I will be unpublishing the old one in a week or so

**Comment by karlhorky** [comment]
Thanks @jasonwilliams ! Just checking this out now.

Easy command line upgrade path for anyone who wants to upgrade:

```bash
code --uninstall-extension jpoissonnier.vscode-styled-components
code --install-extension styled-components.vscode-styled-components
```
