### ISSUE TITLE
Auto-suggestion of CSS properties does not work.

### ISSUE THREAD

**Issue by lucasaugustscode** [styled-components/vscode-styled-components#339]
I noticed that CSS properties auto-suggestion is not working.

**Comment by mohammedsobhi** [comment]
it doesn't work for me too.

**Comment by osamamammar** [comment]
me too. It was working earlier today.

**Comment by MRamadan1474** [comment]
you can install an older version following the steps in this screenshot
![image](https://user-images.githubusercontent.com/61327194/145496269-e1418c05-e9d3-4a81-9939-d7c541363525.png)

**Comment by Metarock** [comment]
Facing the same issue too, had to install an older version.

**Comment by jasonwilliams** [comment]
Can you all tell me the versions where it stopped working please?

**Comment by Metarock** [comment]
Version 1.7.0

**Comment by jasonwilliams** [comment]
Eugh ☹️ I will try and take a look today it’s most likely some change in the styled plugin

**Comment by jasonwilliams** [comment]
Could some of you post videos/gifs of this failing? It would help me out to see it. There were some changes where we switched off completions in places they weren’t needed.

**Comment by MRamadan1474** [comment]
gif with extension version 1.7.0
![nj3lVo4PKl](https://user-images.githubusercontent.com/61327194/145576886-613ec6c9-06fc-4100-a5f4-c7f0130ebdf5.gif)
gif with extension version 1.6.6
![KplAdFs1Lu](https://user-images.githubusercontent.com/61327194/145577593-1d4e3708-5060-417e-b2aa-3e3a6d5d5287.gif)

**Comment by jasonwilliams** [comment]
Could someone try the pre-release here and tell me if it fixes the issue?

**Comment by MRamadan1474** [comment]
Works in 1.7.1
![DBl1TSvB07](https://user-images.githubusercontent.com/61327194/145612228-1d3aa67b-a963-4ffc-a2a8-b274e02b2fa9.gif)

**Comment by jasonwilliams** [comment]
Ok thanks 1.7.2 is now out and should be fixed.
