### ISSUE TITLE
css intellisense suggestions not working after updating to latest verssion 1.70

### ISSUE THREAD

**Issue by Creanick** [styled-components/vscode-styled-components#343]
After updating the plugin to its latest version 1.70, I didn't get the CSS Intellisense suggestions anymore, so I rolled back to the previous version which is working absolutely fine, I hope that it's will be fixed soon

**Comment by DennisJunior247** [comment]
hi, i am having same issue

**Comment by VolodymyrVoronov** [comment]
@DennisJunior247 It helped me. 
I use React + TS => https://github.com/microsoft/typescript-styled-plugin

**Comment by jasonwilliams** [comment]
You're using the wrong extension, make sure you remove it and install https://marketplace.visualstudio.com/items?itemName=styled-components.vscode-styled-components which should be version 1.7.2

Sorry about the disruption but we needed to switch publishers

**Comment by Creanick** [comment]
Thanks, It works perfectly right now

**Comment by craigcosmo** [comment]
I installed the latest version from your link, but after installation, my vscode says it's 1.7.0

**Comment by DennisJunior247** [comment]
install tslint vscode extension

**Comment by anthonibs** [comment]
I have problem in my intellisense css properties are not giving a list of suggestions. About 30-40 days it was working perfectly I'm using version 1.7.6

**Comment by jasonwilliams** [comment]
@anthonibs please can you create a new issue
