### ISSUE TITLE
Syntax highlighting not working on vscode 1.18.0-insider

### ISSUE THREAD

**Issue by lhz516** [styled-components/vscode-styled-components#35]
After I updated to vscode 1.18.0-insider, the syntax highlighting no longer worked

Env: Windows 10

![image](https://user-images.githubusercontent.com/9879279/31531241-bdf86330-af9a-11e7-91d6-c0246f43f0c2.png)

**Comment by dmt-13** [comment]
Same for me.

**Comment by euan-gwd** [comment]
not working on stable 1.17.2 either

**Comment by xahon** [comment]
1.15.0 also not working

**Comment by LestaD** [comment]
Works on 1.17.2

![image](https://user-images.githubusercontent.com/5620073/31903640-5bd58314-b831-11e7-84c4-79950ed7cfcb.png)

**Comment by LestaD** [comment]
On 1.18.0-insiders, too

![image](https://user-images.githubusercontent.com/5620073/31903712-9b174f08-b831-11e7-9df3-50d7a2f7429c.png)

**Comment by lhz516** [comment]
@LestaD Maybe because you are on Mac. This issue is only for Windows, I've edited the topic.

**Comment by dmt-13** [comment]
Doesn't work for me on 1.18.0 (Insiders) with the Mac.

<img width="615" alt="screen shot 2017-10-23 at 22 48 23" src="https://user-images.githubusercontent.com/10092277/31909902-59dcba7e-b844-11e7-9a70-2c7c2ff85995.png">

**Comment by LestaD** [comment]
@dmt-13 have different build commit

**Comment by sarahbethfederman** [comment]
Not working on Mac for me on Version 1.18.0-insider (1.18.0-insider)

**Comment by euan-gwd** [comment]
Respectfully, still doesn't work, on macos 10.12.6, have tried uninstalling and reinstalling. 
Anyone got any suggestions?
<img width="903" alt="screen shot 2017-10-25 at 09 10 33" src="https://user-images.githubusercontent.com/13132625/31985298-e506117e-b964-11e7-9122-a8ceff3d8b2c.png">

**Comment by euan-gwd** [comment]
Not working on fresh install of Insiders Build either
<img width="972" alt="screen shot 2017-10-25 at 09 28 53" src="https://user-images.githubusercontent.com/13132625/31986011-2d5a02e4-b967-11e7-8b3d-e7c5c82cb9e2.png">

**Comment by xahon** [comment]
![image](https://user-images.githubusercontent.com/18731681/32420933-51e4a17a-c2de-11e7-90b1-f62acffabc40.png)
Ubuntu 16.04

**Comment by test27c** [comment]
Anyone using Babel ES6/ES7 ? try to disabling it, works for me. VSCode 1.17, Windows 7. I don't know if it's work in other OS.

**Comment by wongyue** [comment]
![123](https://user-images.githubusercontent.com/17574258/32583930-d1346fc4-c530-11e7-84b9-73ebfe7b0847.png)
1.18.0not work！

**Comment by wongyue** [comment]
![1 172](https://user-images.githubusercontent.com/17574258/32584187-1b5fad42-c532-11e7-8499-05142250200f.png)
back to 1.17.2 is ok.

**Comment by cauldyclark15** [comment]
I am following this issue, so far I set the file type to CSS just to obtain syntax highlighting and code completion. 
![screen shot 2017-11-09 at 10 39 56 am](https://user-images.githubusercontent.com/11132381/32585891-a1e85a0a-c53a-11e7-8f1e-6706de1e2d48.png)

**Comment by brentmclark** [comment]
I was having this same issue but was able to fix it by disabling/uninstalling the `vscode-babel-coloring` plugin for Babel ES6/7 syntax coloring by `dzannotti`.

**Comment by dmt-13** [comment]
@brentmclark Awesome! Disabling Babel ES6/ES7 extension and switching language to Javascript activated highlighting again! Thanks for your solution! :)

VSCode Insiders - 1.18.0

**Comment by zalishchuk** [comment]
Doesn't work in 1.18.0 stable release using `JavaScript React` syntax, works using `TypeScript`, `TypeScript React`, `JavaScript` languages.

- VSCode Version: Code 1.18.0 (dcee2202709a4f223185514b9275aa4229841aa7, 2017-11-08T12:32:39.870Z)
- OS Version: Darwin x64 17.2.0

**Comment by xahon** [comment]
@dmt-13 did you switch to `javascriptreact` lang?

**Comment by dmt-13** [comment]
@xahon no, I've disabled that Babel plugin and switched to Javascript language. Here are some screenshots.

![screen shot 2017-11-09 at 15 27 32](https://user-images.githubusercontent.com/10092277/32607801-c0698ce2-c562-11e7-904a-877722777b21.png)
![screen shot 2017-11-09 at 15 28 46](https://user-images.githubusercontent.com/10092277/32607802-c0888188-c562-11e7-8490-e0851b6aee8f.png)

**Comment by euan-gwd** [comment]
Disabling the dzannotti.vscode-babel-coloring plugin worked a charm for me on the latest stable 1.18.0 on mac

**Comment by cauldyclark15** [comment]
yeah it is also working on me, I also set file associations as

`"files.associations": {
    "*.jsx": "javascriptreact",
    "*.js": "javascript"
  },`

then restart vs code

**Comment by tz5514** [comment]
It works after I install this vs-code plugin
https://marketplace.visualstudio.com/items?itemName=mgmcdermott.vscode-language-babel
hope this will help someone.

**Comment by wooolfgang** [comment]
@cauldyclark15 Thanks! Setting .jsx files to associate with javascript worked for me.
![screen shot 2017-11-10 at 9 25 26 am](https://user-images.githubusercontent.com/20152170/32638214-3ae35a20-c5f9-11e7-96cf-4ae9c2657b6f.png)

**Comment by mjbvz** [comment]
I believe the issue is that VS Code 1.18 uses the `source.js.jsx` scope for jsx files now instead of `source.jsx`.  I've submitted a PR to fix this: #37

Until a new version of this extension is published, try forcing all jsx files to use the JavaScript language mode:

```
"files.associations": { "*.jsx": "javascript", "*.js": "javascript" },
```

**Comment by xahon** [comment]
![image](https://user-images.githubusercontent.com/18731681/32690900-a7e83526-c74a-11e7-9fa2-56a9a26bff57.png)
Is this all highlighting? Compared with true css colors
![image](https://user-images.githubusercontent.com/18731681/32690904-c69cdd46-c74a-11e7-90b8-cb346c8b0d43.png)

I think something went wrong because no autocompletion is present

(After https://github.com/styled-components/vscode-styled-components/issues/35#issuecomment-343341506)

But its certainly better than nothing

**Comment by supadupdip** [comment]
> It works after I install this vs-code plugin
> https://marketplace.visualstudio.com/items?itemName=mgmcdermott.vscode-language-babel
> hope this will help someone.

This also worked for me. Really weird that I didn't already have it, it must've been uninstalled when I moved from one machine to another.
