### ISSUE TITLE
autocomplete is not working in tsx file

### ISSUE THREAD

**Issue by craigcosmo** [styled-components/vscode-styled-components#350]
<img width="948" alt="Screen Shot 2022-01-05 at 1 43 03 PM" src="https://user-images.githubusercontent.com/538657/148173056-062149c1-f839-49a0-b831-455a7cebd7d5.png">

Here it should suggest `text-align` but it didn't, 

This just happened recently. Maybe because the version of vscode ?

```
Version: 1.62.3
Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
Date: 2021-11-17T07:59:13.865Z (1 mo ago)
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.2.0
```

**Comment by jasonwilliams** [comment]
@craigcosmo what version of the extension are you using

**Comment by craigcosmo** [comment]
v1.7.0

**Comment by jasonwilliams** [comment]
@craigcosmo please see pinned issue before raising, you’re on an old version https://github.com/styled-components/vscode-styled-components/issues/343

**Comment by craigcosmo** [comment]
I installed the 1.7.2 and update vscode Version: 1.63.2
Still have the problem

<img width="864" alt="Screen Shot 2022-01-05 at 3 55 01 PM" src="https://user-images.githubusercontent.com/538657/148189320-364fc12f-2b57-4fbd-aa49-914734e82ffd.png">

**Comment by jasonwilliams** [comment]
@craigcosmo could you create a test case repo for us to look at? There could be a settings conflict

**Comment by craigcosmo** [comment]
I can share the settings and extension on my vscode. would that help ?

**Comment by craigcosmo** [comment]
everything is here

https://gist.github.com/craigcosmo/3fde269f67f3d7fc4c8559bef8cea8d6

**Comment by jasonwilliams** [comment]
we will need to be able to reproduce it sadly so some sort of minimal test case would help

**Comment by craigcosmo** [comment]
how can I provide it ?

**Comment by jasonwilliams** [comment]
Example here https://github.com/styled-components/vscode-styled-components/issues/347#issuecomment-1000821884

**Comment by jasonwilliams** [comment]
@craigcosmo is this still an issue?

**Comment by craigcosmo** [comment]
I think not, lets close it for now

**Comment by fredowisk** [comment]
If anyone else is having this issue, go to styled-components in VSCode extensions tab and click switch to pre-release version. It worked for me!
