### ISSUE TITLE
No syntax highlighting for `padding-inline` / `padding-block`

### ISSUE THREAD

**Issue by guytepper** [styled-components/vscode-styled-components#352]
**Describe the bug (including copyable syntax)**
Both padding and margin `inline` and `block` properties doesn't have syntax highlighting.

**Screenshot**
<img width="276" alt="Screen Shot 2022-01-25 at 14 09 28" src="https://user-images.githubusercontent.com/13344923/150974495-62d4d7bb-8c00-486e-aa34-5b01553112a8.png">

**To Reproduce**
```ts
const Container = styled.div`
  padding-block: 10px;
  padding-inline: 10px;

  margin-block: 10px;
  margin-inline: 10px;

  color: red;
`;
```

**Build environment (please complete the following information):**
- VSCode Version: 1.63.2
- Extension Version 1.7.2

**Comment by jasonwilliams** [comment]
Thanks @guytepper our syntax highlighting extends from VSCode's css syntax highlighting.  So the first thing I'd do is find out if it happens also in native CSS files.

If so it needs to be raised with VSCode.

If its fine in CSS but not working here then yeah that's a bug with the syntax highlighting here.

**Comment by guytepper** [comment]
Gotcha, thanks for the info 😊 Hopefully Atom's PR will be merged soon

**Comment by jasonwilliams** [comment]
as this is upstream im going to close this
