### ISSUE TITLE
IntelliSense not working after updating vscode to 1.64

### ISSUE THREAD

**Issue by Sezar-SZ** [styled-components/vscode-styled-components#354]
Hi, I updated the vscode to version 1.64 and now the IntelliSense doesn't work.
Syntax Highlighting seems fine but IntelliSense is not working as expected.

**Screenshot**

![image](https://user-images.githubusercontent.com/71314782/152546356-0297b639-3a94-4197-b2e2-72c5f50c7386.png)

**Build environment:**

- VSCode Version: 1.64
- Extension Version: 1.7.2
- OS: Windows 10

**Edit:**
This issue is upstream from VSCode itself so either:
- Rollback to VSCode 1.63
- Use VSCode Insiders

Root cause: https://github.com/microsoft/vscode/issues/142139

**Comment by vininice** [comment]
Same thing here, was normal yesterday. Happened right after VScode update :/

**Comment by maxleon52** [comment]
Same thing here, :/

**Comment by willian-lemann** [comment]
Same thing in here 
 
![image](https://user-images.githubusercontent.com/44612750/152580938-b6c8dfd9-d63f-4382-bde7-0fcf1ad44054.png)

**Comment by jarrisoncano** [comment]
same issue

**Comment by bsquiroz** [comment]
same issue

**Comment by jarrisoncano** [comment]
es el sistema operativo :)

**Comment by Jhonatan-lezcano** [comment]
my operating system is **Linux Mint 20.2 Cinnamon** and it works without problems, but my colleagues with a **windows 10** operating system if the extension fails,the operating system may be something to consider for this issue

- current version of VSCode: **1.64.0**
- Operating system: **Linux Mint 20.2 Cinnamon**
- technology: **React with Typescript**

![image](https://user-images.githubusercontent.com/65751128/152585859-9d487af5-f12c-4f23-9bfe-07d825b7262f.png)

**Comment by Sezar-SZ** [comment]
@Jhonatan-lezcano I'm using Windows 10 too. So yes, maybe that's where the problem is coming from.
I will edit the issue and add OS, so maybe it could help to solve the problem.

**Comment by Guilherme11gr** [comment]
Same issue!

**Comment by Theakayuki** [comment]
same Issue as well windows 10 started yesterday after update to 1.64, did reinstall of both the extension and vscode.

**Comment by DMCFA** [comment]
same issue with windows 10 after vscode update (1.64)

**Comment by Hugocorreaa** [comment]
i have the same issue too!

**Comment by minivida** [comment]
same issue too with windows 10

**Comment by pzajas** [comment]
Yeap, windows 10 here too. Guess we have to wait for the fix :(

**Comment by seokwoo-park** [comment]
same Issue, thanks for the Extension but can't wait till fix the bug :)

**Comment by pildrums** [comment]
same issue too with windows 10 :(
I can't await to fix bugs.

**Comment by jarrisoncano** [comment]
For the people that need the extension you can try installing the November vscode version (1.63), here in this page it's the executable: 
https://code.visualstudio.com/updates/v1_63

**Comment by jarrisoncano** [comment]
For the people that need the extension can try installing the November vscode version (1.63), here in this page it's the executable: 
https://code.visualstudio.com/updates/v1_63

Maybe this could be a quickly solution.

**Comment by jasonwilliams** [comment]
Hi all thanks for the reports. Can you include your VSCode versions and windows versions please.
I'm using Windows 11 with VSCode insiders, tested this this morning and its working for me.

Version: 1.65.0-insider (system setup)
Commit: 62de8dc3f78b8bef1eb62deeb093164a8d76c254
Date: 2022-02-04T11:47:20.200Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

![styled-components-working](https://user-images.githubusercontent.com/936006/152643883-da7cf2bc-0628-44d8-a3a3-e878e4540207.gif)

Because i can't reproduce it right now someone else will need to take a look.
The [Contributing Guide](https://github.com/styled-components/vscode-styled-components/blob/master/CONTRIBUTING.md#intellisense) goes into more than enough detail on how to look into this.

There's also a [Discord](https://discord.gg/hfGUrbrxaU) chat too

**Comment by nyuuke** [comment]
this issuse happens pretty much every one or two update in vscode, it started with typescript managed project with NextJs and the CRA templates, now I am using a react native with styled components and other project in JS yet the problem still available, despite the extension does not behave well with typescript, I think there is a problem that runs way deep.

Version: 1.64.0 (system setup)
Commit: 5554b12acf27056905806867f251c859323ff7e9
Date: 2022-02-03T04:22:20.678Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

a react native with styled components project using JS
![image](https://user-images.githubusercontent.com/44040669/152644880-f421d6b7-aeb1-45d5-96bf-1375e84231af.png)

a next js project with typescript:
![image](https://user-images.githubusercontent.com/44040669/152644941-9b20e339-ac7a-4046-a746-37908fe5d976.png)

**Comment by Sezar-SZ** [comment]
Thank you for your response @jasonwilliams 
I tried the latest VSCode insiders and the extension was ok there.
So yeah.... probably that problem was just about VSCode and it will be fixed in the next version.

Again, Thank you very much for your attention.

**Comment by nyuuke** [comment]
> this issuse happens pretty much every one or two update in vscode, it started with typescript managed project with NextJs and the CRA templates, now I am using a react native with styled components and other project in JS yet the problem still available, despite the extension does not behave well with typescript, I think there is a problem that runs way deep.
> 
> Version: 1.64.0 (system setup) Commit: 5554b12acf27056905806867f251c859323ff7e9 Date: 2022-02-03T04:22:20.678Z Electron: 13.5.2 Chromium: 91.0.4472.164 Node.js: 14.16.0 V8: 9.1.269.39-electron.0 OS: Windows_NT x64 10.0.22000
> 
> PS: it behaves the same with (.js/.jsx | .ts/.tsx)
> 
> a react native with styled components project using JS ![image](https://user-images.githubusercontent.com/44040669/152644880-f421d6b7-aeb1-45d5-96bf-1375e84231af.png)
> 
> a next js project with typescript: ![image](https://user-images.githubusercontent.com/44040669/152644941-9b20e339-ac7a-4046-a746-37908fe5d976.png)

Revirting to vscode 1.63 update fixes the problem of the extension

**Comment by Hortigas** [comment]
> For the people that need the extension can try installing the November vscode version (1.63), here in this page it's the executable: https://code.visualstudio.com/updates/v1_63
> 
> Maybe this could be a quickly solution.

worked for me

**Comment by Deknoinarak** [comment]
@jasonwilliams I have tested in VS Insider and it worked too!

![image](https://user-images.githubusercontent.com/60281096/152648221-0f8716d6-00d6-4780-8d2d-18ed4c428319.png)

**Comment by benHung1** [comment]
> For the people that need the extension can try installing the November vscode version (1.63), here in this page it's the executable: https://code.visualstudio.com/updates/v1_63
> 
> Maybe this could be a quickly solution.

worked for me

Help me a lot , Thx

**Comment by jasonwilliams** [comment]
The upstream issue seems to be this:
https://github.com/microsoft/vscode/issues/142139

**Comment by hanseulhee** [comment]
It was not applied in version 1.64.0, but it was applied after changing to 1.63.0. 😀

**Comment by leonardojacomussi** [comment]
Same problem here (and same settings too). Downgrading to VSCode version 1.63.2 worked for me.

**Comment by TheAleSch** [comment]
same issue here

**Comment by eisa-rezaei** [comment]
I have same issue

**Comment by MD-Fleksa** [comment]
> The upstream issue seems to be this: [microsoft/vscode#142139](https://github.com/microsoft/vscode/issues/142139)

this is awesome. it works for me

**Comment by vini54** [comment]
same here T-T

**Comment by jasonwilliams** [comment]
Please don’t do “me to” messages. It alerts people watching this thread and adds noise.
If this affects you you can upvote the top comment.

i will close for now as it’s been fixed upstream.

**Comment by Mathews-mw** [comment]
Recently, I had this same problem

What did I do?

I turned off all my installed extensions;
Then, I turned on the styled-components extension;
So, I started to turn on one extension at a time until I found one that was causing conflict and I found;

In my case, the extension that was conflicting was 'JavaScript and TypeScript Nightly v5.0.20221112'. I'm not exactly sure why this extension causes a conflict with styled-component, but I turned it off and everything was back normal.

Perhaps, for each case it is a different extension that causes conflict, but I think it's worth trying to check one by one.

**Comment by akshaysr-buku** [comment]
> Recently, I had this same problem
> 
> What did I do?
> 
> I turned off all my installed extensions; Then, I turned on the styled-components extension; So, I started to turn on one extension at a time until I found one that was causing conflict and I found.
> 
> In my case, the extension that was conflicting was 'JavaScript and TypeScript Nightly v5.0.20221112'. I'm not exactly sure why this extension causes a conflict with styled-component, but I turned it off and everything was back to normal.
> 
> Perhaps, for each case it is a different extension that causes conflict, but I think it's worth trying to check one by one.

Thank you @Mathews-mw , Irrespective of VS code version, `JavaScript and TypeScript Nightly ` was affecting Styled component autocomplete feature

**Comment by Mathews-mw** [comment]
Glad it helped you too.

**Comment by VincentRuoka** [comment]
> Recently, I had this same problem
> 
> What did I do?
> 
> I turned off all my installed extensions; Then, I turned on the styled-components extension; So, I started to turn on one extension at a time until I found one that was causing conflict and I found.
> 
> In my case, the extension that was conflicting was 'JavaScript and TypeScript Nightly v5.0.20221112'. I'm not exactly sure why this extension causes a conflict with styled-component, but I turned it off and everything was back to normal.
> 
> Perhaps, for each case it is a different extension that causes conflict, but I think it's worth trying to check one by one.

Thanks a lot @Mathews-mw ! You just saved my sanity. I couldn't figure out why it stopped working. Can't even remember installing that extension.

**Comment by VincentRuoka** [comment]
Im pretty sure it got installed as part of some TS package I installed. Sadly I can't tell you what exactly because of this issue I cleaned up my whole VSC instance. Maybe it already was there and an update caused the bug with styled-component. 
I remember that the issue started after updating VS Code to the November built.

**Comment by huajiujiang** [comment]
You can disable the related plug-ins at the beginning of typescript and js temporarily, and then enter them. Then you can start the plug-ins, which can also be used normally. I am like this

**Comment by guyeilon** [comment]
> 'JavaScript and TypeScript Nightly

help for me, thanks!

**Comment by Clypsonymity** [comment]
Hi, am I the only one who cannot fix this issue? aka the autocompletion css in jsx files 😅 
### I'm using :

> react `18.2`
> vscode `1.63.2` as suggested
> vscode-styled-components `1.7.5`
> .+ disabled all extensions..

**Comment by Mathews-mw** [comment]
> 



> Hi, am I the only one who cannot fix this issue? aka the autocompletion css in jsx files 😅
> 
> ### I'm using :
> > react `18.2`
> > vscode `1.63.2` as suggested
> > vscode-styled-components `1.7.5`
> > .+ disabled all extensions..

Probably, it's because your vscode version. When a trying this solution, my vscode version was 1.74. Try to update to the latest and then, tur on only the styled-components extension and see if it works to you.

**Comment by Clypsonymity** [comment]
Just tried this but without any success.. So I came back to the good old method:
Indeed, the best way was to delete everything and restart all from scratch like every times 🚀 

> I completely uninstalled vscode and all residual data such as extensions folders etc.. and all reinstalled from scratch and work perfectly 👌

**Comment by mateuscesarglima** [comment]
> 

Helped me a lot, thanks! This extension is conflicting with styled-components.

**Comment by mateuscesarglima** [comment]
> Recently, I had this same problem
> 
> What did I do?
> 
> I turned off all my installed extensions; Then, I turned on the styled-components extension; So, I started to turn on one extension at a time until I found one that was causing conflict and I found.
> 
> In my case, the extension that was conflicting was 'JavaScript and TypeScript Nightly v5.0.20221112'. I'm not exactly sure why this extension causes a conflict with styled-component, but I turned it off and everything was back to normal.
> 
> Perhaps, for each case it is a different extension that causes conflict, but I think it's worth trying to check one by one.

Helped me a lot, thanks! This extension is conflicting with styled-components.

**Comment by mateuscesarglima** [comment]
> Recently, I had this same problem
> 
> What did I do?
> 
> I turned off all my installed extensions; Then, I turned on the styled-components extension; So, I started to turn on one extension at a time until I found one that was causing conflict and I found.
> 
> In my case, the extension that was conflicting was 'JavaScript and TypeScript Nightly v5.0.20221112'. I'm not exactly sure why this extension causes a conflict with styled-component, but I turned it off and everything was back to normal.
> 
> Perhaps, for each case it is a different extension that causes conflict, but I think it's worth trying to check one by one.

Thanks a lot! The extension JavaScript and TypeScript Nightly is conflicting with Styled-components ext. 

Glad dude, it helped too

**Comment by avitslv** [comment]
I'm working on typescript project using styled-components.
Can confirm, after disabling `JavaScript and TypeScript Nightly` extension, suggestions list works.

**Comment by jasonwilliams** [comment]
@mateuscesarglima && @avitslv your issue is not related to this thread. You need to go to https://github.com/styled-components/vscode-styled-components/issues/387 which is about the typescript nightly extension causing problems.

I’m going to mute this thread now as there’s just noise being added which isn’t related. If you think you have an issue, check troubleshooting first on the front page, then search other issues, and only then make a new issue.
