### ISSUE TITLE
Intellisense not working on 1.7.2

### ISSUE THREAD

**Issue by vishal-63** [styled-components/vscode-styled-components#355]
CSS autocomplete and intellisense not working.

![Screenshot (67)](https://user-images.githubusercontent.com/64728353/152654116-781ec5f7-d1ae-4cd2-9a69-1c1af3135398.png)

```
import styled from "styled-components";

export const CheckoutButton = styled.button`
  color: #fff;
  background-color: #000;
  font-size: 1.2rem;
  padding: 0.6rem 1.5rem;
  cursor: pointer;
  margin-top: 1rem;
  border: none;
  outline: none;
`;
```

Tried jumping back to 1.7.0, but didn't work, then again updated to 1.7.2 but to no luck. Also updated VS Code but no luck again.

- OS: Windows 10
- VSCode Version: 1.64.0
- Extension Version: 1.7.2

**Comment by jasonwilliams** [comment]
@vishal-63 please look at the pinned issues before raising a new one
