### ISSUE TITLE
Intellisense not working = a solution that worked for me, maybe it will work for you

### ISSUE THREAD

**Issue by ArturdaSilvaRezende** [styled-components/vscode-styled-components#356]
![no suggestion](https://user-images.githubusercontent.com/59118341/146624974-c96e4ce2-78f7-4dc3-80f9-bdc9e95f0fc2.PNG)
For the people that need the extension can try installing the November vscode version (1.63), here in this page it's the executable:
[vscode version - 1.63](https://code.visualstudio.com/updates/v1_63)

Maybe this could be a quickly solution.
This worked for me, I believe tentatively this might help.

**Comment by jasonwilliams** [comment]
@ArturdaSilvaRezende theres already an issue about this. It’s even pinned at the top.

Why did you need to make a new issue?
