### ISSUE TITLE
Intellisense on this extension not working

### ISSUE THREAD

**Issue by RitvikSardana** [styled-components/vscode-styled-components#357]
I am using styled components with react, the extension was working fine few weeks back, but it stopped working today.
![image](https://user-images.githubusercontent.com/65544983/153048103-c754ec7a-3ff5-401f-80c8-d1ddb61806bc.png)

PS. Tried both v1.7 and 1.7.2 both did not work

**Comment by gluvielmo** [comment]
I'm having the same issue here

**Comment by jasonwilliams** [comment]
See pinned issue

**Comment by RitvikSardana** [comment]
@jasonwilliams how to see the pinned issue?

**Comment by Tanmay2711** [comment]
> I am using styled components with react, the extension was working fine few weeks back, but it stopped working today. ![image](https://user-images.githubusercontent.com/65544983/153048103-c754ec7a-3ff5-401f-80c8-d1ddb61806bc.png)
> 
> PS. Tried both v1.7 and 1.7.2 both did not work

Same issue I am facing now with latest plugin version

**Comment by jasonwilliams** [comment]
See:
- https://github.com/styled-components/vscode-styled-components/issues/343
- https://github.com/styled-components/vscode-styled-components/issues/354

If neither of the suggestions in there work please raise a new issue
