### ISSUE TITLE
Incorrect cursor position after css autocomplete

### ISSUE THREAD

**Issue by tpszhao** [styled-components/vscode-styled-components#360]
**Describe the bug (including copyable syntax)**
CSS autocomplete cursor position af
The cursor is right before the last character of the last word.

**Screenshot**
`justify-conten/*the cursor is currently here*/t: ;`
<img width="462" alt="Screen Shot 2022-03-04 at 10 46 30 AM" src="https://user-images.githubusercontent.com/54560658/156823857-3645c6bc-a262-47a1-8141-7f3180c23cc5.png">

**To Reproduce**
Add any css property, then hit enter on any suggestions.
<img width="366" alt="Screen Shot 2022-03-04 at 10 52 14 AM" src="https://user-images.githubusercontent.com/54560658/156824243-3ba7c102-846a-4e03-b248-c524041af219.png">

**Expected behavior**
The cursor should be BETWEEN the colon and the semi colon

`display:  /*the cursor should be here*/  ;`

**Build environment (please complete the following information):**

- OS: Mac OS Catalina 10.15.7 
- VSCode Version: 1.65
- Extension Version 1.72

**Additional context**
This bug only appeared after I updated vscode to 1.65

**Comment by jasonwilliams** [comment]
For anyone looking into this, see the investigation I did here.
https://github.com/microsoft/typescript-styled-plugin/pull/156

**Comment by guiprais** [comment]
Same problem here.

**Comment by zqy233** [comment]
> For anyone looking into this, see the investigation I did here. [microsoft/typescript-styled-plugin#156](https://github.com/microsoft/typescript-styled-plugin/pull/156)

the problem of code in insertColonCommand.ts,please PR,thanks ,my network is not very well

error code
`
  if (properties.find((value) => value.name === lastWordBeforeCursor)) {
      editor.edit((editBuilder) => {
        editBuilder.insert(
          editor.document.lineAt(cursorPosition.active).range.end,
          ": ;"
        );
        commands.executeCommand("cursorLeft");
        commands.executeCommand("editor.action.triggerSuggest");
      });
    }
`
correct
`
  if (properties.find((value) => value.name === lastWordBeforeCursor)) {
      editor.edit((editBuilder) => {
        editBuilder.insert(
          editor.document.lineAt(cursorPosition.active).range.end,
          ": ;"
        );
      });
      commands.executeCommand("cursorLeft");
      commands.executeCommand("editor.action.triggerSuggest");
    }
`

**Comment by zqy233** [comment]
my solution is "git clone" this project,fix the code in insertColonCommand.ts
![image](https://user-images.githubusercontent.com/57588553/156951852-73a144c4-34bd-49e7-85d9-abe9f6f4c0b9.png)
then "npx vsce package",use the visx, and  it's working correctly

**Comment by zqy233** [comment]
my solution is "git clone" this project and "yarn",fix the code in src/insertColonCommand.ts
![image](https://user-images.githubusercontent.com/57588553/156952607-fd596460-fac0-461b-87c4-020150c7ed32.png)
then "npx vsce package",use the generated visx file,and it works

**Comment by adsonmacedo** [comment]
> my solution is "git clone" this project and "yarn",fix the code in src/insertColonCommand.ts like below
> 
> then "npx vsce package",use the generated vsix file,and it works

I have the same problem, this solution worked for me, at least temporarily!

**Comment by GodaP** [comment]
I can also reproduce this issue on VS Code 1.65.0. Working with Mac OS Big Sur 11.6.4

**Comment by dylanscott** [comment]
Also running into this in VS Code 1.65.1. The cursor seems to consistently end up 3 characters off from where it should be even if it's in nested/indented CSS.

**Comment by TheThomasY** [comment]
For me the update did nothing to fix the issue. However removing a conflicting vscode-styled-components extension did.
So double check you have the correct VS Code extension installed.

**Comment by urkin-dev** [comment]
For me the problem was in vscode-styled-components extension but from another author, not Styled Components. So check your extension and remove all wrong ones if you have them and install "vscode-styled-components" from Styled Components

**Comment by gustavoalfaro** [comment]
> cursor

This worked for me, checked the package and it was the right one, it is the newest version of VS Code what is causing problems

**Comment by Pat-Gekoski** [comment]
I don't want a hack to fix a simple tool. I shouldn't have to downgrade my IDE or patch the extension. Is there a fix for this problem coming soon?   ...... I hope

**Comment by Migggz** [comment]
I just reInstalled any extensions that related to styled-components and now works fine

**Comment by AdrianFahrbach** [comment]
Reinstalling the extension did not fix it for me, I had to downgrade to VSCode v1.64.2 as well.
I'm using vscode-styled-components v1.7.4.
In the changelog for v1.7.3 it says that this is fixed but it seems like it's not.
Am I the only one still having this issue?

**Comment by chenrupo** [comment]
I am still having this issue in v1.7.4, vscode 1.68.1, macos 12.4

**Comment by alexalannunes** [comment]
me too

**Comment by GusPrado** [comment]
Same issue here!! Not fixed as stated on #362 
Removed and reinstalled vscode-styled-components v1.7.4
VSCode v1.70.1 and upgraded to v1.70.2 (latest)
MacOS Monterey 12.5

**Comment by pedroelton** [comment]
> For me the problem was in vscode-styled-components extension but from another author, not Styled Components. So check your extension and remove all wrong ones if you have them and install "vscode-styled-components" from Styled Components

I'm having the same problem, I use only the styled-components original plugin. But I have a feeling it's some conflict with emmet or another plugin that autocompletes CSS.

**Comment by vavdav** [comment]
I have the same issue, tried reinstall and nothing works
