### ISSUE TITLE
Color picker does not register for color strings in .tsx files

### ISSUE THREAD

**Issue by DanielHZhang** [styled-components/vscode-styled-components#363]
**Describe the bug (including copyable syntax)**
The built-in VSCode color picker normally shows up next to color strings (i.e. hex, rgb) within `typescriptreact` and `javascriptreact` files. After updating to the newest version, these color strings are no longer considered ranges to trigger the color picker.

**Screenshot**
Version 1.7.3:
<img width="358" alt="image" src="https://user-images.githubusercontent.com/30360288/157582165-990656b5-2bc5-4da1-b477-5f50ab6a9013.png">

Version 1.7.2:
<img width="356" alt="image" src="https://user-images.githubusercontent.com/30360288/157582414-aae586ba-d80a-4f74-aa73-6d90ff7644cc.png">

**To Reproduce**
Create a `.tsx` file with the following content:
```typescript
const red = '#ff0000'
```

**Expected behavior**
The built-in VSCode color picker appears next to the hex color string. 

**Build environment (please complete the following information):**

- OS: macOS 12.1
- VSCode Version: 1.65.1
- Extension Version 1.7.3

**Comment by jasonwilliams** [comment]
Thanks for raising @DanielHZhang 
Would you be ok to work on this?

**Comment by zqy233** [comment]
> Thanks for raising @DanielHZhang Would you be ok to work on this?
> 
> https://github.com/styled-components/vscode-styled-components/blob/master/CONTRIBUTING.md
> 
> you would just need to clone this project, npm install, then launch the extension

I found it was the problem with “esbuild”, use "0.14.2" or "0.14.3" , it would be ok , but later version ,Color picker do not work such as "0.14.25"

**Comment by vinibortoletto** [comment]
I'm having the exact same problem. Started after 1.7.3 update.

**Comment by pildrums** [comment]
I have same problem too.

**Comment by jasonwilliams** [comment]
Please don’t do “me too” posts. If you’re affected by this issue “thumb up” the original message. This gives me a better idea of who’s affected rather than creating noise.

**Comment by jasonwilliams** [comment]
This should be fixed in 1.7.4 https://github.com/styled-components/vscode-styled-components/releases/tag/v1.7.4
