### ISSUE TITLE
vscode-styled-components doesn't work when i use it with 'ES7+ React/Redux/React-Native snippets' extension

### ISSUE THREAD

**Issue by cjy0019** [styled-components/vscode-styled-components#365]
**Describe the bug (including copyable syntax)**
command 'extension.insertColonOrSemiColon' not found bug is displayed 

**Screenshot**
 <img width="1157" alt="스크린샷 2022-03-13 오전 10 59 36" src="https://user-images.githubusercontent.com/33951916/158041716-4f6f266c-bad9-4579-8849-e68521a686cd.png">

**To Reproduce**
Steps to reproduce the issue, or JavaScript code that causes this failure.
If you showed a screenshot, it will help a lot to paste accompanying code which matches

**Expected behavior**
react-snippets doesn't works.

**Build environment (please complete the following information):**

- OS: mac 12.2.1 (M1)
- VSCode Version: 1.65.2 v
- Extension Version 1.73 v
- ES7+ React/Redux/React-Native snippets Version : 4.43 v

**Comment by jasonwilliams** [comment]
@cjy0019 can you provide some steps to reproduce or a test case because I don’t understand what the issue is here. The screenshot doesn’t have enough detail

**Comment by cjy0019** [comment]
> @cjy0019 can you provide some steps to reproduce or a test case because I don’t understand what the issue is here. The screenshot doesn’t have enough detail

Oh! sorry.
When I turn off and on my MacBook, it works fine again. I think it was a problem with my vscode!
