### ISSUE TITLE
wrong cursor position

### ISSUE THREAD

**Issue by zhangzhinan** [styled-components/vscode-styled-components#366]
**Describe the bug (including copyable syntax)**
When I select the style according to the prompt, the cursor position is wrong

**Screenshot**

https://user-images.githubusercontent.com/16774464/159110075-0fd7a83e-46ff-4265-9080-826712e9f64e.mov

**Build environment (please complete the following information):**

- OS: 
<img width="392" alt="mac" src="https://user-images.githubusercontent.com/16774464/159110082-77886bc5-032b-488b-be2c-00c85ff140e9.png">
- VSCode Version: 
<img width="269" alt="vscode" src="https://user-images.githubusercontent.com/16774464/159110086-2d8eecf6-c128-4c8f-a851-b43148e4313e.png">

- Extension Version 
<img width="869" alt="WX20220319-141326@2x" src="https://user-images.githubusercontent.com/16774464/159110090-7c3bf3d6-4131-4dc6-b249-536ca6960ff8.png">

**Comment by jasonwilliams** [comment]
@zhangzhinan did you try the suggestions in https://github.com/styled-components/vscode-styled-components/issues/360

**Comment by zhangzhinan** [comment]
> @zhangzhinan did you try the suggestions in #360

I downgraded VS Code to 1.64.2 and now the cursor it's working correctly.

**Comment by karlhorky** [comment]
The problem for us was having 2 versions of the extension installed (the current one, published by `Styled Components`, and the old one, published by `Julien Poissonnier (jpoissonnier)`)

The solution was to remove remove the old VS Code extension from `Julien Poissonnier (jpoissonnier)` and reload VS Code.

**Comment by zhangzhinan** [comment]
> The problem for us was having 2 versions of the extension installed (the current one, published by `Styled Components`, and the old one, published by `Julien Poissonnier (jpoissonnier)`)
> 
> The solution was to remove remove the old VS Code extension from `Julien Poissonnier (jpoissonnier)` and reload VS Code.

Perfect！  it really works, thank you very much

**Comment by sudipta9** [comment]
> The problem for us was having 2 versions of the extension installed (the current one, published by `Styled Components`, and the old one, published by `Julien Poissonnier (jpoissonnier)`)
> 
> The solution was to remove the old VS Code extension from `Julien Poissonnier (jpoissonnier)` and reload VS Code.

Perfectly worked for me, thanks @karlhorky
