### ISSUE TITLE
) expected ts-styled-plugin(9999)

### ISSUE THREAD

**Issue by AaronMcCloskey** [styled-components/vscode-styled-components#371]
**Describe the bug (including copyable syntax)**
Getting the following error from `ts-styled-plugin` on the 2nd line

```
@media screen and (max-width: ${({ theme }) =>
    theme.DynamicTheme.mobXLargeMax - 20}px) {
```

**Screenshot**
<img width="333" alt="Screenshot 2022-07-05 at 15 17 50" src="https://user-images.githubusercontent.com/20436343/177349397-31051f08-346b-4310-987a-14f5fc5d4b11.png">

**To Reproduce**
I believe this occurs due to`printWidth` setting in my `prettier` options

## .prettierrc.js
```
module.exports = {
  "printWidth": 80,
  "singleQuote": true,
  "trailingComma": "all"
}
```

For good measure, I'll add my `eslint` settings to
```
module.exports = {
  extends: ['airbnb', 'plugin:prettier/recommended', 'prettier/react'],
  env: {
    browser: true,
    commonjs: true,
    es6: true,
    jest: true,
    node: true,
  },
  parser: 'babel-eslint',
  parserOptions: {
    sourceType: 'module',
    allowImportExportEverywhere: true,
  },
  rules: {
    'jsx-a11y/href-no-hash': ['off'],
    'react/jsx-filename-extension': ['warn', { extensions: ['.js', '.jsx'] }],
    'max-len': [
      'warn',
      {
        code: 80,
        tabWidth: 2,
        comments: 80,
        ignoreComments: false,
        ignoreTrailingComments: true,
        ignoreUrls: true,
        ignoreStrings: true,
        ignoreTemplateLiterals: true,
        ignoreRegExpLiterals: true,
      },
    ],
    'react/forbid-prop-types': 'off',
    'react/prop-types': [2, { ignore: ['children'] }],
    'react/jsx-props-no-spreading': 'off',
    'prettier/prettier': ['error'],
  },
};
```

**Expected behavior**
Don't believe the error should appear as it is valid css

**Build environment (please complete the following information):**

- OS: macOS Cataline v10.15.7
- VSCode Version: 1.68.1
- Extension Version v1.7.4

**Additional context**

**Comment by MatthiasDh** [comment]
I think I got a similar issue:
`{ expected ts-styled-plugin(9999)`

**Comment by stanislawdera** [comment]
I'm getting similar issue: `semi-colon expected ts-styled-plugin(9999)` Is that related?

```js
export const Wrapper = styled.div`
  background-color: red;

  div {
    padding: ${({ theme }) => theme.spacing.md}
      ${({ theme }) => theme.spacing.sm};
  }
`
```
When I remove the newline everything starts working:
```js
// produces error
padding: ${({ theme }) => theme.spacing.md}
  ${({ theme }) => theme.spacing.sm};
```
```js
padding: ${({ theme }) => theme.spacing.md} ${({ theme }) => theme.spacing.sm}; // works
```

**Comment by mariorodeghiero** [comment]
I am also getting `} expectedts-styled-plugin(9999)` 

 code:
 ```css
 
  &: hover { <====== issue in "&" symbol
        text-decoration: underline;
    }
 ```

**Comment by Allex191** [comment]
### Getting same error on v1.7.4
### *working
<img src="https://user-images.githubusercontent.com/76633311/185364921-cb8a2ef7-3174-467d-9c03-a7d5bd76fa40.png" width="700">
### *not working on formatting
<img src="https://user-images.githubusercontent.com/76633311/185365115-4f664c68-5d7f-4c0b-bf95-95d6c01e504e.png" width="700">
<img src="https://user-images.githubusercontent.com/76633311/185365151-0aac6c6d-df8f-48ac-b254-478d8092bbc7.png" width="700">

Temporary solution -- downgrade to v1.7.0

**Comment by dkyuho** [comment]
Same error on v1.7.5 using emotion with valid CSS using `:has` selector

<img width="452" alt="Screenshot 2023-04-04 at 7 42 36 am" src="https://user-images.githubusercontent.com/103015432/229634064-98c5d5db-6067-4e00-a706-099ee7ca9aac.png">

**Comment by zuehler** [comment]
Same for me v1.7.5 using emotion with forced line breakes

![Bildschirmfoto 2023-04-06 um 10 58 04](https://user-images.githubusercontent.com/93330435/230330924-edfe1f23-2476-466b-9a8d-1e7f60e67bd3.png)

![Bildschirmfoto 2023-04-06 um 11 03 21](https://user-images.githubusercontent.com/93330435/230331041-9f323065-4c99-4d8b-8912-82874517ba42.png)

![Bildschirmfoto 2023-04-06 um 11 00 38](https://user-images.githubusercontent.com/93330435/230331024-01fef8d3-43c8-4b05-bfc5-d410ff7d0b84.png)

**Comment by johnhult** [comment]
I got exactly the same issue. Forced line break and autoformat.
Anyone that has found a way around this?

**Comment by jasonwilliams** [comment]
Are you getting this with 1.7.8?

**Comment by AaronMcCloskey** [comment]
> Are you getting this with 1.7.8?

@jasonwilliams Yes, the `{ expected ts-styled-plugin(9999)` no longer appears on`1.7.8` on any of the instance I had before 🙌

**Comment by ajkl2533** [comment]
@jasonwilliams I'm still getting `{ expected ts-styled-plugin(9999)` on `1.7.8` among two more:
- `semi-colon expected ts-styled-plugin(9999)`
- `at-rule or selector expected ts-styled-plugin(9999)`
<img width="629" alt="Screenshot 2023-04-24 at 10 42 55" src="https://user-images.githubusercontent.com/18654425/233945258-afd5db4e-106d-405b-9f26-3476f7e67e1e.png">

**Comment by MauricioRobayo** [comment]
I'm on version 1.7.8 and getting:

<img width="289" alt="image" src="https://user-images.githubusercontent.com/2121481/236720889-436fb44f-f4d7-453e-a7e7-97a360a1eec9.png">

<img width="292" alt="image" src="https://user-images.githubusercontent.com/2121481/236720935-1bd21af1-fce1-4419-800b-a21274f2ef0f.png">

**Comment by johnninja** [comment]
> > Are you getting this with 1.7.8?
> 
> @jasonwilliams Yes, the `{ expected ts-styled-plugin(9999)` no longer appears on`1.7.8` on any of the instance I had before 🙌

### **Still happens!!!**

**Comment by elektronik2k5** [comment]
I am also experiencing this issue in versions from `1.7.0` up to the current `1.7.8`. My setup is latest Emotion (`11.11.0`) and TS (`5.1.3`). 
![image](https://github.com/styled-components/vscode-styled-components/assets/1078554/847565ad-8051-4502-a57b-c45d3eb754e0)

Can we please reopen the issue? @jasonwilliams

**Comment by sacru2red** [comment]
Similar Issue,

linter fixed my file with new lines, when using ternary operator.
and ext warn

![image](https://github.com/styled-components/vscode-styled-components/assets/43224844/6487d426-a5e6-4826-a605-c7111d4eceaf)

**Comment by JGabriel12** [comment]
Similar Issue

![image](https://github.com/styled-components/vscode-styled-components/assets/43641860/e75a7688-4681-4cb8-960f-0a2b5a22fefe)

**Comment by CyxouD** [comment]
There is an answer in README Troubleshooting:
```
Property look up comes from the [css language service](https://github.com/microsoft/vscode-css-languageservice) which in turn comes from [MDN Data](https://github.com/mdn/data). If its a custom property, or something that is not in MDN you can add your own property like so: https://github.com/microsoft/typescript-styled-plugin/issues/58#issuecomment-444733368

If however you believe this property is standard and thus missing you can raise this issue with either one of the above projects; please check for any raised issue first.
```
However, it doesn't work for me
