### ISSUE TITLE
Cursor is backing when intellisense item is selected

### ISSUE THREAD

**Issue by alexalannunes** [styled-components/vscode-styled-components#374]
Type: <b>Bug</b>

when I'm typing some css in js code and press enter to autocomplete my code, the cursor is backing

**With inline style**
[inline-style-react.webm](https://user-images.githubusercontent.com/16847836/184344922-e924185d-1096-4eaa-8223-fb0188f9d20f.webm)

**With styled-components**
[with-styled-components.webm](https://user-images.githubusercontent.com/16847836/184345025-4bd3ed03-c33b-44a0-a80a-0e428accca0a.webm)

In CSS files it works perfectly :smile: 

Extension version: 1.7.0
VS Code version: Code 1.70.1 (6d9b74a70ca9c7733b29f0456fd8195364076dda, 2022-08-10T06:09:15.055Z)
OS version: Linux x64 5.15.0-46-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 2000)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|2, 2, 1|
|Memory (System)|15.50GB (6.59GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id a8c01c81-74da-4a14-9262-92e6cb321fce|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
wslgetstarted:30449410
cppdebug:30492333
pylanb8912:30545647
vsclangdf:30486550
c4g48928:30535728
d7fjc500:30543455
dsvsc012cf:30540253
azure-dev_surveyonecf:30545436

```

</details>

**Comment by uloco** [comment]
Possible duplicate of https://github.com/styled-components/vscode-styled-components/issues/366

**Comment by alexalannunes** [comment]
> Possible duplicate of #366

thanks!
