### ISSUE TITLE
Auto Complete Fails with TypeScript 5.0.0

### ISSUE THREAD

**Issue by ricardroberg** [styled-components/vscode-styled-components#387]
Styled component stop working with JS and TS NIghtly v5.0.20221113  and above.

styled-component 1.73.1

No intelisense

[https://github.com/microsoft/vscode-typescript-next/issues/61](url)

**Comment by jasonwilliams** [comment]
@ricardroberg was that link supposed to go somewhere? 

Do you have any errors? Like do you run the typescript server with “trace” enablee

**Comment by ricardroberg** [comment]
@jasonwilliams  Sorry...never done that. Its began like 7 to 10 days ago. Just found 2hours ago which plugin was in conflict.

**Comment by booooora** [comment]
https://github.com/microsoft/vscode-typescript-next/issues/61#issue-1457321234

Guess he linked it to wrong url. 
I'm having a same issue and this is the issue I left to TS nightly a week ago. 🥲

**Comment by ricardroberg** [comment]
Yes @booooora . Thank you a lot.

**Comment by jasonwilliams** [comment]
Ok thanks for raising this.
I think https://github.com/microsoft/typescript-styled-plugin needs updating.

**Comment by jasonwilliams** [comment]
This issue is being looked at in https://github.com/microsoft/TypeScript/issues/51713

**Comment by vilic** [comment]
It seems that @mjbvz has already fixed this in [typescript-template-language-service-decorator](https://github.com/microsoft/typescript-template-language-service-decorator) months ago but never released the new version.

Just validated that fix in `typescript-styled-plugin` and e2e tests passes with TypeScript 5.0.

**Comment by jasonwilliams** [comment]
Ok I understand we have a lot of users with the issue of auto complete failing due to the TypeScript update.
Sadly the bad news is, this is an upstream issue which is out of my control to fix. It has been fixed in https://github.com/microsoft/typescript-template-language-service-decorator (as @vilic pointed out) but there's been no release. 

I've pulled the latest commit from https://github.com/microsoft/typescript-template-language-service-decorator and tested it and I can see auto complete works.

I have also [raised this](https://github.com/microsoft/TypeScript/issues/51713#issuecomment-1493053367) with the team.

You will either need to roll back your typescript version, or get onto the people upstream to make a release.

**Comment by admiralrohan** [comment]
This was happening to me after I updated VS code. The easiest fix is to add this to VS code local settings.

```json
"typescript.tsdk": "node_modules/typescript/lib"
```

**Comment by Aluisio** [comment]
I updated the plugin to the pre-release version (1.7.7) and it worked again. I will continue testing.
VS Code version: 1.77.0
vscode-styled-components version: 1.7.7

**Comment by kostiuck** [comment]
all good, thanks!

**Comment by ricardroberg** [comment]
Pre-release 1.7.7 working with JavaScript and TypeScript Nightly v5.1.20230403
Thank you!

**Comment by MeHighLow34** [comment]
Pre-release version works. Thanks!

**Comment by gillescoolen** [comment]
Yep, pre-release version fixes the issue!

**Comment by jasonwilliams** [comment]
Ok thanks for the confirmations

v1.7.8 has now been published as a normal release so that will be rolling out now. 
Now that saga is over I'm closing this issue!

**Comment by paprikman** [comment]
> Ok thanks for the confirmations
> 
> [v1.7.8](https://github.com/styled-components/vscode-styled-components/releases/tag/v1.7.8) has now been published as a normal release so that will be rolling out now. Now that saga is over I'm closing this issue!

I highly appreciate the work you've done, but the intellisense does not work with <5 versions of typescript after upgrading to v1.7.8. So I had to rollback. Can I somehow help to troubleshoot this one?

**Comment by jasonwilliams** [comment]
Hi @paprikman 
You’re right this is now incompatible with TypeScript < 5 and also the latest version of VSCode.

I don’t have any advice to offer other than rollback the version to 1.7.5 or update your typescript to 5.0.0

**Comment by paprikman** [comment]
> Hi @paprikman You’re right this is now incompatible with TypeScript < 5 and also the latest version of VSCode.
> 
> I don’t have any advice to offer other than rollback the version to 1.7.5 or update your typescript to 5.0.0

This is sad news. I think it makes sense to add that to the README then. Not everyone has options to change TS version in their projects at will.

**Comment by leognmotta** [comment]
I can agree, it cannot rely on TS version 5

**Comment by jasonwilliams** [comment]
> > Hi @paprikman You’re right this is now incompatible with TypeScript < 5 and also the latest version of VSCode.
> > I don’t have any advice to offer other than rollback the version to 1.7.5 or update your typescript to 5.0.0
> 
> This is sad news. I think it makes sense to add that to the README then. Not everyone has options to change TS version in their projects at will.

https://github.com/styled-components/vscode-styled-components/tree/main#intellisense-is-not-working
