### ISSUE TITLE
Bug in intellisense is not completing css properties

### ISSUE THREAD

**Issue by anthonibs** [styled-components/vscode-styled-components#392]
I have problem in my intellisense css properties are not giving a list of suggestions. About 30-40 days it was working perfectly I'm using version 1.7.6

The version of my vs code is 1.74.0

[![Captura-de-tela-de-2022-12-13-22-18-56.png](https://i.postimg.cc/L5CgczHQ/Captura-de-tela-de-2022-12-13-22-18-56.png)](https://postimg.cc/QK7M5KKc)

[![Captura-de-tela-de-2022-12-13-22-19-18.png](https://i.postimg.cc/SRNz1Zpz/Captura-de-tela-de-2022-12-13-22-19-18.png)](https://postimg.cc/DJHZ8P02)

**Comment by guyeilon** [comment]
same here

**Comment by jasonwilliams** [comment]
Please fill in the template otherwise your issue will be closed

**Comment by anthonibs** [comment]
css property not complete

[![Captura-de-tela-de-2022-12-15-07-55-40.png](https://i.postimg.cc/zf720hzc/Captura-de-tela-de-2022-12-15-07-55-40.png)](https://postimg.cc/066CNbJY)

configuration of my vs code:


{
    // Workbench
    "files.autoSave": "afterDelay",
    "workbench.colorTheme": "Dracula",
    "workbench.editor.enablePreview": false,
    "workbench.startupEditor": "none",
    "workbench.iconTheme": "material-icon-theme",
    "workbench.editor.untitled.hint": "hidden",
    // Git settings
    "gitlens.advanced.messages": {
        "suppressCommitNotFoundWarning": true,
        "suppressLineUncommittedWarning": true
    },
    "git.enableSmartCommit": true,
    "git.confirmSync": false,
    "git.autofetch": true,
    "gitlens.hovers.currentLine.over": "line",
    "gitlens.currentLine.enabled": false,
    // Editor settings
    "diffEditor.wordWrap": "on",
    "editor.wordWrap": "on",
    "editor.fontSize": 16,
    "editor.tabSize": 2,
    "editor.bracketPairColorization.enabled": true,
    "editor.largeFileOptimizations": false,
    "editor.linkedEditing": true,
    "editor.fontFamily": "Fire Code, JetBrains Mono",
    "editor.fontLigatures": true,
    "editor.fontWeight": "normal",
    "editor.codeActionsOnSave": {
        "source.fixAll": true
    },
    // Editor settings terminal
    "terminal.integrated.fontSize": 14,
    "terminal.integrated.defaultProfile.linux": "bash",
    "terminal.integrated.profiles.linux": {
        "bash": {
            "path": "bash",
            "icon": "terminal-bash"
        },
    },
    // Extensions of Emojis
    "emojisense.languages": {
        "markdown": true,
        "plaintext": false,
        "json": true,
        "typescript": true,
        "python": true,
        "scminput": true, // linguagem usada na caixa de mensagem de confirmação do controle de origem;
        "javascript": true
    },
    /* 
        Extensions 
    */
    "liveServer.settings.donotShowInfoMsg": true,
    "liveServer.settings.CustomBrowser": "chrome",
    "liveServer.settings.donotVerifyTags": true,
    "cSpell.language": "en, pt-BR",
    "code-runner.clearPreviousOutput": true,
    "explorer.compactFolders": false,
    "explorer.confirmDelete": false,
    "explorer.confirmDragAndDrop": false, //Quando a pasta estiver vazia ou tiver somente um arquivo não fica o arquivo no lado da pasta na aba explorador;
    "javascript.updateImportsOnFileMove.enabled": "always",
    "typescript.updateImportsOnFileMove.enabled": "always",
    "material-icon-theme.folders.associations": {
        "domain": "core",
        "infra": "app",
        "main": "public",
        "presentation": "connection",
        "cryptography": "secure",
        "entities": "class",
        "repositories": "mappings",
        "protocols": "resource",
        "useCases": "components",
        "subcomponents": "components",
        "adapters": "connection",
        "factories": "container",
        "globals": "global",
        "ui": "views"
    },
    "emmet.triggerExpansionOnTab": true,
    "emmet.syntaxProfiles": {
        "javascript": "js",
        "typescript": "ts",
    },
    "emmet.includeLanguages": {
        "javascript": "javascriptreact",
        "typescript": "typescriptreact",
    },
}

**Comment by jasonwilliams** [comment]
@anthonibs please open a new issue filling out the template.
