### ISSUE TITLE
In the use of react, there is no code prompt, which makes me unable to work normally

### ISSUE THREAD

**Issue by huajiujiang** [styled-components/vscode-styled-components#393]
<img width="657" alt="image" src="https://user-images.githubusercontent.com/105536345/207504089-7da9e534-4291-40ba-96a1-fa95a72fdbe9.png">
In the use of react, there is no code prompt, which makes me unable to work normally

**Comment by jasonwilliams** [comment]
Please fill in the template otherwise your issue will be closed
