### ISSUE TITLE
"command 'extension.insertColonOrSemiColon' not found" error

### ISSUE THREAD

**Issue by D-Maher** [styled-components/vscode-styled-components#398]
Type: <b>Bug</b>

I keep seeing a "command 'extension.insertColonOrSemiColon' not found" error when trying to hit 'Enter' on item in suggestions menu. An extension bisect suggests that the vscode-styled-components extension is to blame.

Extension version: 1.7.0
VS Code version: Code 1.75.0 (Universal) (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:24:42.903Z)
OS version: Darwin arm64 22.2.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|4, 4, 8|
|Memory (System)|32.00GB (3.23GB free)|
|Process Argv|--crash-reporter-id e4599b47-489c-4ba3-98b9-8cf8a081b0ac|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848cf:30577861
nodejswelcome1cf:30587006
3biah626:30602489
f6dab269:30613381
pythonsymbol12:30657548
vscodeenable:30660116

```

</details>

**Comment by jasonwilliams** [comment]
Can you give us some steps to reproduce @D-Maher ?

**Comment by D-Maher** [comment]
I can't seem to reproduce this reliably anymore. It might have been a momentary hiccup with my setup.

I'll close this. Thank you anyways.

**Comment by jasonwilliams** [comment]
Ok sure no probs, feel free to re-raise once you can reproduce it
