### ISSUE TITLE
Shouldn't highlight inside comments

### ISSUE THREAD

**Issue by julienp** [styled-components/vscode-styled-components#4]
<img width="380" alt="comment" src="https://cloud.githubusercontent.com/assets/387068/20455241/a1c09d1c-ae57-11e6-9875-1aa438248e3a.png">

The `injectionSelector` is set to `L:source`, which makes it apply inside comments and breaks highlighting for the rest of the file.

**Comment by wmertens** [comment]
Similar issue:
![image](https://cloud.githubusercontent.com/assets/54934/20596763/43ad5458-b240-11e6-9e05-dfe3b61bebbf.png)

it triggers off the ".css`" at the end of that string :)

**Comment by julienp** [comment]
Good catch, thank you for the screenshot.

I haven't found a solution for the highlighting inside comments yet. Currently the plugin looks for matching regexes in the whole file, with `"injectionSelector": "L:source"`. I've been trying to find the correct selectors to just match the places where a template string could occur, but seemingly there's none that matches any expression (something like `L:meta.expr`). This might be linked to https://github.com/Microsoft/vscode/issues/6858#issuecomment-221801714

**Comment by ajhyndman** [comment]
See also: https://github.com/Microsoft/vscode/issues/2793

**Comment by mxstbr** [comment]
Running into this really badly in my project 😢 Super annoying bug!

**Comment by alpyre** [comment]
In my project I wrote:
`'injectionSelector': 'L:source -comment'`
...and it solved the issue for me.

**Comment by kumarharsh** [comment]
@alpyre is there any place where all of these possible values for injectionSelector are documented? I've tried searching, but come up empty. I need something similar for my project (graphql-for-vscode).

**Comment by kumarharsh** [comment]
OK, after some digging, I found a few documents which highlight what all those textmate scopenames mean. Linking it here for anyone else stumbling on the problem: https://github.com/kumarharsh/graphql-for-vscode/issues/7#issuecomment-268360641
