### ISSUE TITLE
Intellisense / emmet / autocomplete not working

### ISSUE THREAD

**Issue by lomeat** [styled-components/vscode-styled-components#401]
**Describe the bug (including copyable syntax)**
Don't offer any suggestions in .js or .jsx file when you styling the dom element. Screenshot below.

**Screenshot**   
![CleanShot 2023-03-15 at 07 09 58](https://user-images.githubusercontent.com/33469504/225195927-ffac0a9f-6931-4d27-bdd4-f1a28730877e.png)

![CleanShot 2023-03-15 at 07 14 24](https://user-images.githubusercontent.com/33469504/225196013-a65f9a78-0d71-4ed5-bb91-b124127d0840.png)

**To Reproduce**   
Hm, I do not know

**Expected behavior**   
See CSS suggestions based on what I am typing

**Build environment (please complete the following information):**

- OS: [Mac OS 13.2.1]
- VSCode Version: [1.76.1]
- Extension Version [1.7.5]

**Extensions**   
```
aaron-bond.better-comments
AdamCaviness.theme-monokai-dark-soda
akamud.vscode-theme-onedark
anthonypennadev.rescriptllighttheme
apust.rubber-theme
artlaman.chalice-color-theme
bernik.theme-codeschool2-minimal
calebdoxsey.minimal
chenglou92.rescript-vscode
chrisbibby.hide-node-modules
cluzier.ocean
dbaeumer.vscode-eslint
dev1ce.dev1ce
doay.onyx
dracula-theme.theme-dracula
dunstontc.dark-plus-syntax
eamodio.gitlens
Equinusocio.vsc-community-material-theme
Equinusocio.vsc-material-theme
equinusocio.vsc-material-theme-icons
esbenp.prettier-vscode
fivepointseven.vscode-theme-onedark-spacegray
formulahendry.auto-close-tag
formulahendry.auto-rename-tag
gargakshit.theme-alabaster-dark
golang.go
jcbuisson.vue
jibsen.theme-solarized-minimal
k3a.theme-dark-plus-contrast
kleber-swf.ocean-dark-extended
liquori.material-minimal-dark
marioterron.one-dark-bimbo
ms-vscode.vscode-typescript-next
mullakhmetov.shale
NicolaiVerbaarschot.alabaster-variant-theme
nwolverson.ide-purescript
nwolverson.language-purescript
ritwickdey.live-sass
ritwickdey.LiveServer
rokoroku.vscode-theme-darcula
rvest.vs-code-prettier-eslint
styled-components.vscode-styled-components
tonsky.theme-alabaster
vscode-icons-team.vscode-icons
WakaTime.vscode-wakatime
zhuangtongfa.material-theme
Zyst.Egoist-One
```

**Comment by jasonwilliams** [comment]
I don't even see syntax highlighting happening there, but I can see the extension is working based on that tooltip.
That's a lot of extensions, could you try disabling them all to see if there's a conflict?

For reproduction it would be a case of making a small repository we could try out

**Comment by lomeat** [comment]
@jasonwilliams  I do not think that case in repository or plugins. Because almost all extensions are just the theme styles. And your extension should work in "plain" file with no repo. 
I'll be glad to offer steps to reproduce if I could repeat it where it already works.

Maybe do you know some vscode settings for it or special vscode version?

**Comment by lomeat** [comment]
@jasonwilliams Sorry. My bad. I deleted the Vue deprecated extension and your extension started work. I dunno how it influences on intellisence into .jsx but it is so.
