### ISSUE TITLE
Hints for stylized components do not work if the `JavaScript and TypeScript Nightly` extension is enabled

### ISSUE THREAD

**Issue by zharinov-nikita** [styled-components/vscode-styled-components#403]
If extension `vscode-styled-components` is enabled together with extension `JavaScript and TypeScript Nightly`, then hints for stylized components stop working.

### Extension `JavaScript and TypeScript Nightly` is enabled
    
<img width="387" alt="image" src="https://user-images.githubusercontent.com/101789452/225972673-a42c395e-43a5-48c8-98c6-9cc7f859df16.png">

### Extension `JavaScript and TypeScript Nightly`  is disabled 

<img width="394" alt="image" src="https://user-images.githubusercontent.com/101789452/225972911-e54b9f9f-eacb-48ce-b1be-4f1c84a14aca.png">

### The error was detected on: 

- Windows  - 11
- `Microsoft Visual Studio Code` - v1.76.2
- (VS Code extension) `vscode-styled-components` - [v1.7.5](https://marketplace.visualstudio.com/items?itemName=styled-components.vscode-styled-components)
- (VS Code extension) `JavaScript and TypeScript Nightly` - [v5.1.20230313](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next)

**Comment by Losery1021** [comment]
I have the same problem.

**Comment by jasonwilliams** [comment]
Did you honestly open this issue without checking to see if this was already being raised?

Not only this is an issue already but it’s PINNED at the top! How did you miss it??

Sorry if this comes across as harsh but please check other issues before creating a new one, it creates noise for maintainers on this repo. I often spend a lot of time closing duplicates. Help us to help you.

Go here https://github.com/styled-components/vscode-styled-components/issues/387
