### ISSUE TITLE
cannot use auto complete 

### ISSUE THREAD

**Issue by kenanimok** [styled-components/vscode-styled-components#409]
windown 11 extention version v1.7.5

![image](https://user-images.githubusercontent.com/89970690/229056673-98ff5e3d-3761-4d4a-94d5-da5c221aa390.png)

**Comment by kenanimok** [comment]
please help me

**Comment by datawn-jy** [comment]
I have same issues..

**Comment by datawn-jy** [comment]
![스크린샷 2023-03-31 오후 5 12 00](https://user-images.githubusercontent.com/99210950/229063834-977010dc-34ca-444c-a472-ab2519c6c140.png)

**Comment by Gh3rra** [comment]
same problem today

**Comment by Rowen-S** [comment]
同样的问题css 不会提示了

**Comment by pedrorvelloso** [comment]
Just updated my VSCode and intellisense stoped working too. I was using the 1.76.X version then updated to 1.77.0.

Probably a conflict with this new VScode version.

**Comment by ArthurSimoess** [comment]
I have the same problem, it stopped autocompleting

**Comment by thiagoacmonteiro** [comment]
I was facing the same issue. Downgrading to version 1.76.2 of vscode solved my problem. 
Just uninstall vscode and then reinstall it through this link https://code.visualstudio.com/updates/v1_76

**Comment by Aluisio** [comment]
I'm having the same problem. Actually the problem happens after updating to version 1.77

**Comment by WebDevMirza** [comment]
> ctually the problem happens after updating to version 1.77

Hmm, the extension was perfect yesterday night. But after updating to 1.77, problem occurs and it kills my 3 hours.

**Comment by soberbat** [comment]
Having the same...

**Comment by MeHighLow34** [comment]
Same problem...

**Comment by geril2207** [comment]
in new vscode update ships typescript 5.0.2 which brokes styled components completion. for me downgrading typescript version in vscode to 4.9.3 works fine
![image](https://user-images.githubusercontent.com/62308020/229299797-36b97ce7-10c5-4fcb-8a39-7ed50356b980.png)

**Comment by kr4chinin** [comment]
@geril2207 solution is the best option for now if you don't wont to downgrade entire IDE.
