### ISSUE TITLE
No autocomplete or suggestions!

### ISSUE THREAD

**Issue by MeHighLow34** [styled-components/vscode-styled-components#410]
There is no autocomplete or suggestions for stylized components.
![image](https://user-images.githubusercontent.com/89307630/229352771-14f440d7-56cf-4af6-8ab5-ce602625eaf0.png)

It just doesn't come up. Is there any way to fix this without downgrading VS Code.

- OS: Windows 10
- VSCode Version: 1.77.0
- Extension Version 1.7.5

**Comment by jasonwilliams** [comment]
Don’t raise new issues without checking if it’s already raised, it’s pinned at the top
