### ISSUE TITLE
IntelliSense not working in demo app with only itself enabled

### ISSUE THREAD

**Issue by Enzodtz** [styled-components/vscode-styled-components#414]
**Describe the bug (including copyable syntax)**
My intellisense was not working. So I checked both pinned issues and none of them could help me. I [disabled all extensions but this one](https://github.com/styled-components/vscode-styled-components/issues/354#issuecomment-1312617252), but still didn't work. I also tried it in a simple `create-react-app` application, but got no success. It is not on the video, but I also tried to comment all my custom `settings.json` file.

**Screenshot**   

https://user-images.githubusercontent.com/7780770/229823258-44abd6da-8095-4d94-953e-7cc7c626c6ba.mp4

**To Reproduce**   
```bash
npx create-react-app my-app
cd my-app
npm install --save styled-components
code .
# try to write a styled component in App.js
```

**Expected behavior**   
I expected it to show me the possibilities of words with `back` 

**Build environment (please complete the following information):**

- OS: Windows
- VSCode Version: 1.77.0
- Extension Version: 1.7.5

**Extensions**   

<details>
  <summary>I tested it with all of them disabled, but still:</summary>
  
```
adpyke.vscode-sql-formatter
amazonwebservices.aws-toolkit-vscode    
batisteo.vscode-django
bierner.color-info
burkeholland.simple-react-snippets      
cweijan.vscode-office
Dart-Code.dart-code
Dart-Code.flutter
dsznajder.es7-react-js-snippets
eamodio.gitlens
Equinusocio.vsc-community-material-theme
Equinusocio.vsc-material-theme
equinusocio.vsc-material-theme-icons    
esbenp.prettier-vscode
FelixAngelov.bloc
James-Yu.latex-workshop
kddejong.vscode-cfn-lint
monosans.djlint
ms-azuretools.vscode-docker
ms-python.isort
ms-python.python
ms-python.vscode-pylance
ms-toolsai.jupyter
ms-toolsai.jupyter-keymap
ms-toolsai.jupyter-renderers
ms-toolsai.vscode-jupyter-cell-tags
ms-toolsai.vscode-jupyter-slideshow
ms-vscode.vscode-typescript-next
Nash.awesome-flutter-snippets
pascalsenn.keyboard-quickfix
planbcoding.vscode-react-refactor
softwaredotcom.swdc-vscode
styled-components.vscode-styled-components
syler.sass-indented
VisualStudioExptTeam.intellicode-api-usage-examples
VisualStudioExptTeam.vscodeintellicode
vscodevim.vim
william-voyek.vscode-nginx
```
</details>

**Additional context**   
Maybe it could be related to I have a conflict with all my extensions enabled, and a missing dependency with them disabled?

**Comment by jasonwilliams** [comment]
Try extension version 1.7.7 it’s a pre release so won’t install automatically

**Comment by Enzodtz** [comment]
Worked :) thanks!
