### ISSUE TITLE
In `.ts` file extensions, there is no color preview.

### ISSUE THREAD

**Issue by zhenzhenChange** [styled-components/vscode-styled-components#415]
**Describe the bug (including copyable syntax)**

In .ts file extensions, there is no color preview.

**Screenshot**   

![image](https://user-images.githubusercontent.com/51586637/229971731-405fb924-8a2e-4fe0-aecc-3d03f44b3e47.png)

**To Reproduce**   

None.

**Expected behavior**   

Can you add support for `.ts`? Or can a configuration be opened for users to add it manually?

**Build environment (please complete the following information):**

- OS: Windows 11
- VSCode Version: 1.77.0
- Extension Version 1.7.7

**Extensions**   

```text
adpyke.codesnap
alexiv.vscode-angular2-files
Angular.ng-template
anseki.vscode-color
ardenivanov.svelte-intellisense
bierner.markdown-preview-github-styles
bungcip.better-toml
chrmarti.regex
cweijan.xmind-viewer
DavidAnson.vscode-markdownlint
dbaeumer.vscode-eslint
donjayamanne.githistory
eamodio.gitlens
ElAnandKumar.el-vsc-product-icon-theme
esbenp.prettier-vscode
formulahendry.auto-close-tag
formulahendry.auto-complete-tag
formulahendry.auto-rename-tag
git-emoji.vscode-git-emoji
hangxingliu.vscode-nginx-conf-hint
haskell.haskell
intellsmi.comment-translate
justusadam.language-haskell
kisstkondoros.vscode-gutter-preview
kumar-harsh.graphql-for-vscode
Meowcolm024.runner2
mhutchie.git-graph
mikestead.dotenv
ms-azuretools.vscode-docker
MS-CEINTL.vscode-language-pack-zh-hans
ms-vscode-remote.remote-containers
ms-vscode-remote.remote-wsl
peakchen90.open-html-in-browser
PKief.material-icon-theme
redhat.vscode-yaml
rust-lang.rust-analyzer
shd101wyy.markdown-preview-enhanced
streetsidesoftware.code-spell-checker
styled-components.vscode-styled-components
svelte.svelte-vscode
techer.open-in-browser
tommasov.hosts
tomphilbin.gruvbox-themes
Vue.volar
yzhang.markdown-all-in-one
```

**Additional context**   

None.

**Comment by jasonwilliams** [comment]
By default this extension activates on `.tsx` and `.jsx`, it's good practise to use styled components in `tsx` and `jsx` files so your IDE knows which mode to be in.

If you want to force this extension to be on you'll need to go to the bottom right of your IDE and set `TypeScript JSX` as your language.

**Comment by zhenzhenChange** [comment]
I haven't actually switched the `.ts` file to `.tsx` mode yet, but there are hints in the `.ts` file, I mean just the colours without the preview hints.

![image](https://user-images.githubusercontent.com/51586637/230271775-29910211-324c-4f0a-8ef8-107f21ea22fd.png)

**Comment by jasonwilliams** [comment]
We cannot do that, because if we do that people would have colour pickers showing up all over the place whenever they reference a colour in a .ts file (even just the word “blue”).

Sadly the only option if you want this feature is to move to .tsx which is what most of our users have done already.

**Comment by karahbit** [comment]
IntelliJ IDEA is able to provide color previews for styled components in .ts files. I was hoping to do the same in VS Code through this extension, but unfortunately this is still an issue.
