### ISSUE TITLE
No intellisense after upgrading to v.1.7.8

### ISSUE THREAD

**Issue by khsily** [styled-components/vscode-styled-components#417]
**Describe the bug (including copyable syntax)**
After upgrading to v1.7.8 the auto completion is gone! Working fine with older version v1.7.5.
Also tried to disable all other extensions, but had no luck.

**Screenshot**   
v1.7.8
![v1 7 8](https://user-images.githubusercontent.com/30749436/230249327-402ee2ba-8d3f-462c-b48a-aae7788b5cad.png)

v1.7.5
![v1 7 5](https://user-images.githubusercontent.com/30749436/230249347-89e8fab4-fcab-4bb5-91ee-9989dbcda58d.png)

**To Reproduce**   
Upgrade to v1.7.8 and restart vscode.

**Expected behavior**   
Suggest css syntax.

**Build environment (please complete the following information):**

- OS: MacOS Ventura 13.0
- VSCode Version: 1.76.2 (Universal)
- Extension Version 1.7.8

**Comment by jasonwilliams** [comment]
Update VSCode to 1.77

**Comment by khsily** [comment]
@jasonwilliams Issue solved! Thank you.
