### ISSUE TITLE
syntax highlighting bug

### ISSUE THREAD

**Issue by Ali-ovo** [styled-components/vscode-styled-components#419]
**Describe the bug (including copyable syntax)**

when I use `emotion`, there is no syntax highlighting .
but when I use `vscode-styled-components v1.7.5` , it works fine.
when updating to `vscode-styled-components v1.7.8`, it doesn't work

**Screenshot**   

![image](https://user-images.githubusercontent.com/67216143/230813507-38eb922a-e32d-460d-be72-2fcff6a47eb7.png)

**To Reproduce**   
just css 

**Expected behavior**   
i hope it works，like this
![image](https://user-images.githubusercontent.com/67216143/230813722-bf32610b-3cab-4a18-92db-421c93abda8d.png)

**Build environment (please complete the following information):**

- OS: [Apple M1 Pro macOS：13.2.1 ]
- VSCode Version: [ 1.77.1]
- Extension Version [1.7.8]

**Extensions**   
You can get this by running `$ code --list-extensions` in the command line

**Additional context**

**Comment by jasonwilliams** [comment]
Your title mentions syntax highlighting but your reproduce steps are around auto completion. Use TS 5.x or downgrade the extension
