### ISSUE TITLE
Version 1.7.8 intelisense not working

### ISSUE THREAD

**Issue by rafaelxim** [styled-components/vscode-styled-components#420]
**Describe the bug (including copyable syntax)**
After automaticaly updating to the version 1.7.8, the intelisense stoped working.
I did a downgrade to version 1.7.5 and works fine.

**To Reproduce**   
Upgrado to version 1.7.8 and try intelisense.

**Expected behavior**   
Expected Intelisense working.

**Build environment (please complete the following information):**

- OS: [e.g. Windows 11]
- VSCode Version: [e.g. 1.74.2]
- Extension Version [e.g. 1.7.8]

**Comment by jasonwilliams** [comment]
See https://github.com/styled-components/vscode-styled-components/issues/387
