### ISSUE TITLE
Intellisense not working in this extention v1.7.8 and ts@5.0.4 

### ISSUE THREAD

**Issue by OnlyWick** [styled-components/vscode-styled-components#423]
**Screenshot**   
![image](https://user-images.githubusercontent.com/53461157/233030997-1fbf2aa4-1ba2-44f5-b0e5-deaec5982f21.png)

**To Reproduce**   
I don't think it is necessary to reproduce it. Only intellisense can't be used, without any hint.

**Build environment (please complete the following information):**

- OS: `Win10 WSL2: Ubuntu-20.04`
- VSCode Version: `1.77.3`
- Extension Version: `v1.7.8`

**Additional context**   
- `nextjs@13`
- `storybook@7.0.5`

**Comment by jasonwilliams** [comment]
>I don't think it is necessary to reproduce it. Only intellisense can't be used, without any hint.

Sadly this is necessary, as people have different settings and different environments. We will need a test repo to make sure we're looking at the same thing, otherwise this will just be closed as a "works for me"

**Comment by OnlyWick** [comment]
I just finished initializing the `nextjs` project and then installed `styled-components` and `this extension`, and then it haven't any intellisense.

**Comment by OnlyWick** [comment]
> > I don't think it is necessary to reproduce it. Only intellisense can't be used, without any hint.
> 
> Sadly this is necessary, as people have different settings and different environments. We will need a test repo to make sure we're looking at the same thing, otherwise this will just be closed as a "works for me"

I just finished initializing `the nextjs` project and then installed `styled-components` and `this extension`, and then it haven't any intellisense.

**Comment by OnlyWick** [comment]
I have the impression that you can use the extension directly after installing it. I don't know why it won't work this time. I read some issue and found that I need to upgrade to `v1.7.8` and `ts > 5.0` is needed, I did, but I just couldn't! even though I was downgraded to `ts@4.9.4` and `v1.7.5`. It's weird...Other features is working!!

**Comment by jasonwilliams** [comment]
What nextjs project are you referring to? Are you checking out next itself? Also could you list all of the extensions you're using? There's a command to do that somewhere

**Comment by OnlyWick** [comment]
> What nextjs project are you referring to? Are you checking out next itself? Also could you list all of the extensions you're using? There's a command to do that somewhere
> 
> 你指的是哪个 nextjs 项目？你是要退房吗？你还可以列出所有你正在使用的扩展吗？这是命令

https://nextjs.org/

**Comment by jasonwilliams** [comment]
Are you opening up https://github.com/vercel/next.js/ with VSCode and seeing your issue there?
Also I need a list of extensions `code --list-extensions`

**Comment by OnlyWick** [comment]
I using `npx create-next-app@latest` to create project.

Following is my installed extensions.
```
aaronthomas.vscode-snazzy-operator
alefragnani.Bookmarks
alphabotsec.vscode-eclipse-keybindings
apollographql.vscode-apollo
cschlosser.doxdocgen
danielpinto8zz6.c-cpp-project-generator
dbaeumer.vscode-eslint
dsznajder.es7-react-js-snippets
eamodio.gitlens
EditorConfig.EditorConfig
esbenp.prettier-vscode
evondev.dracula-high-contrast
formulahendry.auto-rename-tag
formulahendry.code-runner
Gruntfuggly.todo-tree
haskell.haskell
jeff-hykin.better-cpp-syntax
justusadam.language-haskell
kisstkondoros.vscode-gutter-preview
kumar-harsh.graphql-for-vscode
liviuschera.noctis
ms-azuretools.vscode-docker
MS-CEINTL.vscode-language-pack-zh-hans
ms-python.python
ms-python.vscode-pylance
ms-vscode.cmake-tools
ms-vscode.cpptools
ms-vscode.cpptools-extension-pack
ms-vscode.cpptools-themes
ms-vscode.hexeditor
nwolverson.ide-purescript
nwolverson.language-purescript
PKief.material-icon-theme
Remisa.shellman
ritwickdey.LiveServer
searKing.preview-vscode
shd101wyy.markdown-preview-enhanced
streetsidesoftware.code-spell-checker
styled-components.vscode-styled-components
stylelint.vscode-stylelint
twxs.cmake
unifiedjs.vscode-mdx
usernamehw.errorlens
vscode-icons-team.vscode-icons
Vue.volar
Vue.vscode-typescript-vue-plugin
wix.vscode-import-cost
```

**Comment by jasonwilliams** [comment]
ok awesome, that's a lot of extensions, can you switch them all off and only have styled components on and try again?

**Comment by OnlyWick** [comment]
It still doesn't work. : (
![image](https://user-images.githubusercontent.com/53461157/233055360-ad7682fe-ad78-4fb7-b595-5f109bbcc7a1.png)

**Comment by jasonwilliams** [comment]
Could you paste your settings?

**Comment by OnlyWick** [comment]
```
{
  "files.autoSave": "off",
  "editor.wordWrap": "on",
  "editor.fontSize": 11,
  "emmet.triggerExpansionOnTab": true,
  "emmet.showAbbreviationSuggestions": true,
  "emmet.showExpandedAbbreviation": "always",
  "workbench.iconTheme": "vscode-icons",
  "update.enableWindowsBackgroundUpdates": true,
  "explorer.compactFolders": false,
  "security.workspace.trust.untrustedFiles": "open",
  "terminal.integrated.gpuAcceleration": "off",
  "code-runner.clearPreviousOutput": true,
  "workbench.editor.untitled.hint": "hidden",
  "vim.smartRelativeLine": true,
  "markdown-preview-enhanced.previewTheme": "atom-dark.css",
  "editor.minimap.showSlider": "always",
  "vsicons.dontShowNewVersionMessage": true,
  "C_Cpp.clang_format_fallbackStyle": "Google",
  "[vue]": {
    "editor.defaultFormatter": "Vue.volar"
  },
  "editor.formatOnSave": true,
  "editor.formatOnPaste": true,
  "editor.formatOnType": true,
  "editor.codeActionsOnSave": {
    "source.fixAll.eslint": true,
    "source.fixAll.stylelint": true
  },
  "window.zoomLevel": 2,
  "vim.foldfix": true,
  "gitlens.hovers.currentLine.over": "line",
  "[markdown]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "http.proxySupport": "off",
  "glassit.alpha": 240,
  "git.alwaysShowStagedChangesResourceGroup": true,
  "[typescript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[jsonc]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[javascript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "haskell.manageHLS": "GHCup",
  "[html]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[json]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[typescriptreact]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "workbench.colorTheme": "Evondev Dracula Darker Contrast"
}
```

**Comment by OnlyWick** [comment]
Errr, I have been struggling for an afternoon(make me creazy!), but now suddenly it works. I don't know what's wrong with vscode!! I'm sorry to waste your time.

**Comment by OnlyWick** [comment]
I have reinstalled several times(vscode and this extension), but I can't figure out the problem. It doesn't seem like a extensions conflict either, because I have been using this plugin for a long time before. It's still my apologies for wasting your time!!! @jasonwilliams

**Comment by jasonwilliams** [comment]
No problem @OnlyWick
