### ISSUE TITLE
We plan to feature your VS Code extension!

### ISSUE THREAD

**Issue by auchenberg** [styled-components/vscode-styled-components#43]
Hi,

It's Kenneth from VS Code. I'm reaching out to tell you that we plan to feature your awesome VS Code extension on our marketplace https://marketplace.visualstudio.com/#VSCode in the next iteration. I'm opening an issue here as there seem to many contributors on this extension.

Please work with your community to resolve any major issues, as you'll probably see a significant bump in new users trying your extension.

Thanks for the great work, and happy coding! 

/k

------
Kenneth Auchenberg
Visual Studio Code
Program Manager, Microsoft

**Comment by mxstbr** [comment]
That's awesome, thanks Kenneth! :heart: Gotta deploy the latest changes so that @mjbvz awesome `typescript-styled-plugin` integration is included.......

**Comment by julienp** [comment]
Thanks, that's great!

**Comment by auchenberg** [comment]
Your are live!
