### ISSUE TITLE
Add support for css prop?

### ISSUE THREAD

**Issue by FezVrasta** [styled-components/vscode-styled-components#48]
I know it's not a Styled Components feature, but it would be great if this plugin supported the Emotion's `css` property.

```
<div css={`
  color: red;
`} />
```

**Comment by mxstbr** [comment]
We probably won't got out of our way to support all the ways any CSS-in-JS library allows you to write CSS, but it shouldn't be too hard to fork this package and add support for that!

**Comment by kripod** [comment]
@mxstbr As support for the `css` prop was added by styled-components v4, is it possible to re-open this issue?

**Comment by KamaKAzii** [comment]
Would also love to see this work for the `css` prop in v4 🎉

**Comment by nathanvale** [comment]
Is there anything I can do to make this possible?

**Comment by njdancer** [comment]
Likewise, If I can be pointed to the relevant file and documentation would be happy to have a crack at this.
