### ISSUE TITLE
Parsing broken on complex selectors

### ISSUE THREAD

**Issue by asn007** [styled-components/vscode-styled-components#50]
My extension just got updated with what looks like IntelliSense support and it looks like parsing complex selectors is rather faulty:

```javascript
import React from 'react'
import styled from 'styled-components'
import fullWidth from '../../helpers/fullWidth'
import withTheme from '../../theme/withTheme'
import Button from './Button'

function ButtonGroup({ ...rest }) {
  return <div {...rest} />
}

const styledButtonGroup = styled(ButtonGroup)`
  display: flex;
  ${fullWidth()};

  ${Button} {
    width: 100%;
    
    &:not(:first-child):not(:last-child) {
      margin-left: 0;
      margin-right: 0;
      border-radius: 0;
    }

    
  }
`

export default withTheme(styledButtonGroup)
```

For the following code I get: `[ts-styled-plugin] } expected (15, 13)`
For now, is there any way to disable IntelliSense for styled-components?

**Comment by asn007** [comment]
*UPD* I've just taken a closer look, this looks like a bug in typescript-styled-plugin, so maybe I should forward it there also

**Comment by Cu3PO42** [comment]
Configuring VS Code to use the workspace version of TypeScript (if you have one) should do that as a temporary workaround.

**Comment by mjbvz** [comment]
Fixed upstream issue https://github.com/Microsoft/typescript-styled-plugin/issues/30 with typescript-styled-plugin@0.4.1

**Comment by Cu3PO42** [comment]
Since this issue itself has been fixed I am going to close this. If you still think that there should be an easy way to disable IntelliSense, I believe it would be more appropriate to open a separate issue about that.
