### ISSUE TITLE
No highlight for just styled``

### ISSUE THREAD

**Issue by deadcoder0904** [styled-components/vscode-styled-components#59]
CSS is Highlighted with `styled.div` but not with just `styled`

# Code

```js
import styled from "styled-components";

styled.div`
	background-color: black;
	color: green;
	font-size: 12px;
`;
```

# Preview

<img width="389" alt="styled div" src="https://user-images.githubusercontent.com/16436270/36413857-2332b91e-1646-11e8-91c1-5646e6694010.png">

# Code

```js
import styled from "styled-components";

styled`
	background-color: black;
	color: green;
	font-size: 12px;
`;
```
# Preview

<img width="442" alt="styled" src="https://user-images.githubusercontent.com/16436270/36413909-4a71db68-1646-11e8-9cbf-7b76bb5702bb.png">

**Comment by ravinggenius** [comment]
What is <code>styled\`\`</code> supposed to return? How is it valid without a tag or a component?

**Comment by deadcoder0904** [comment]
`styled``` is another alias for `styled.div``` as stated in the docs

**Comment by mxstbr** [comment]
> styled is another alias for styled.div as stated in the docs.

What that's not true? Doing ` styled`` ` won't work at all, try it in your app!

**Comment by deadcoder0904** [comment]
What 🤔 

I did it long time back & it worked. Never used `styled-components` other than 1 project & I am pretty sure `styled` & `styled.div` were same & if my memory recalls it was stated in the docs bcz there isn't any other famous project that used template literals that I used. But still its your project so you might know better. But let me check, I've seen it somewhere.

**Comment by deadcoder0904** [comment]
Nope, its not. I guess I was dreaming then 😂

`Glamor` comes close though. So I guess this issue isn't valid.

**Comment by deadcoder0904** [comment]
Noopsy I wasn't dreaming. I have seen it somewhere written that if you write just `styled` than it return `styled.div` or something like that. 

Idk if version 3.0 changed it or not but it was written like that. I'll see if I can find it.

I'd like to think my memory is good enough sometimes 😂
