### ISSUE TITLE
Error with "To", "From" in keyframes

### ISSUE THREAD

**Issue by AntonAderum** [styled-components/vscode-styled-components#6]
See picture:

![to-from](https://cloud.githubusercontent.com/assets/2329863/20706464/c789fbba-b627-11e6-9f27-604c87765105.PNG)

The pictured css is valid but is shown as invalid by the highlighter.

**Comment by julienp** [comment]
I don't think this extension is doing this error highlighting, do you have some other extensions installed that could be doing this, something using stylelint maybe?

**Comment by julienp** [comment]
Closing this for now, feel free to re-open if I misunderstood
