### ISSUE TITLE
Syntax highlighting broken with template literals ` ...css`

### ISSUE THREAD

**Issue by mrducnguyen** [styled-components/vscode-styled-components#65]
Hi,

I found that the current version of vscode-styled-components (0.0.16) causes syntax highlighting issue when using [template literals ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals), and the final text is `css`. It breaks the syntax highlighting.

When it is enabled, and the template ends with `css`
![image](https://user-images.githubusercontent.com/4490596/36767685-abdf8b3a-1c8f-11e8-8fc8-052916481fd2.png)

When it is disabled
![image](https://user-images.githubusercontent.com/4490596/36767670-9d1ea5ae-1c8f-11e8-8f43-279d64035672.png)

Thanks,

**Comment by perry-mitchell** [comment]
I've also been able to reproduce this:

![image](https://user-images.githubusercontent.com/3869469/37111379-2e857280-2248-11e8-844f-b95f2f62d888.png)

And after disabling:

![image](https://user-images.githubusercontent.com/3869469/37111401-3e6c0d3a-2248-11e8-877d-3a574bde5a20.png)

**Comment by Cu3PO42** [comment]
Apparently the injection modifiers will only work with prefixes of grammar scopes and not any substrings. However I can now fix this issue nicely.
