### ISSUE TITLE
Highlighting broken when creating component inline

### ISSUE THREAD

**Issue by Briggybros** [styled-components/vscode-styled-components#66]
Hello, there is a method for consuming props in styled components documented here: https://github.com/styled-components/styled-components/issues/135 (vdanchenkov)

However, taking this approach breaks the highlighting, where the css template has standard template formatting.

**Comment by Cu3PO42** [comment]
I assume the syntax you are talking about is this:

```
styled(({ active, ...rest }) => <Link {...rest} />)`
  color: black;
`
```

This is indeed a limitation of the current grammar. I know how to work around it, but it is a fair amount of work, so I cannot make any statements about when I will get around to doing it.

**Comment by th0th** [comment]
Thanks for the great extension!

Is there any updates on this one?

**Comment by jasonwilliams** [comment]
Im closing this issue in favour of https://github.com/styled-components/vscode-styled-components/issues/233
