### ISSUE TITLE
colon/semi-color expected error

### ISSUE THREAD

**Issue by bernatfortet** [styled-components/vscode-styled-components#67]
![image](https://user-images.githubusercontent.com/390010/37116750-05d5a5a6-2204-11e8-8704-620d7e5b92f9.png)

When I import a literal string from one of my npm libraries it gives an error
`semi-color expected` and `colon-excpected`

I tried the same object structure but without module and it works fine.
![image](https://user-images.githubusercontent.com/390010/37116813-2acf2b2a-2204-11e8-9dbb-973808b957ef.png)

**Comment by nmodi** [comment]
I'm getting this same issue

`
const activeClassName = 'active-nav-link';

const Link = styled(NavLink).attrs({activeClassName

... 

&.${activeClassName} {
        border-bottom: 2px solid ${props => props.theme.red}; 
    }


`

yields "[ts-styled-plugin] semi-colon expected (20, 17)

while the following does not: 

`    &.active-nav-link {
        border-bottom: 2px solid ${props => props.theme.red}; 
    }
`

**Comment by Cu3PO42** [comment]
Since this appears to be an error with [typescript-styled-plugin](https://github.com/Microsoft/typescript-styled-plugin) rather than vscode-styled-components itself, please also open an issue there so that it can be fixed upstream.

**Comment by bernatfortet** [comment]
@Cu3PO42 I talked to @mjbvz and it seems that they've fixed this issue it's just a matter of upgrading to their latest
