### ISSUE TITLE
Intellisense for injectGlobal

### ISSUE THREAD

**Issue by pungggi** [styled-components/vscode-styled-components#68]
Intellisense for injectGlobal seems not to work, I use the newest VS Code Ver. 1.21.1

![grafik](https://user-images.githubusercontent.com/5635709/37430888-e5f0fefe-27d3-11e8-9d36-024992178064.png)

**Comment by deadcoder0904** [comment]
Wow came exactly to write this 😂

**Comment by Cu3PO42** [comment]
As a temporary workaround, you should be able to install typescript-styled-plugin into your own project, configure VSCode to use the workspace version of TypeScript and configure `injectGlobal` as a tag to trigger IntelliSense in accordance with the [typescript-styled-plugin README](https://github.com/Microsoft/typescript-styled-plugin).

**Comment by Cu3PO42** [comment]
I have opened a PR at Microsoft/typescript-styled-plugin#43 to enable this by default.

**Comment by pungggi** [comment]
Thank you this worked.

**Comment by pungggi** [comment]
Thank you for the PR, but as I now read throu some issues it seems that injectGlobal will be deprecated in one of the next major release.. https://github.com/styled-components/styled-components/pull/1493

**Comment by pungggi** [comment]
Maybe you want change or add the new tag: `createGlobalStyle`
https://github.com/styled-components/styled-components/issues/1333#issuecomment-363151088
