### ISSUE TITLE
how to write customize rule?

### ISSUE THREAD

**Issue by xiaoyu-tamu** [styled-components/vscode-styled-components#73]
I am using styled-components-ts to write type checking for my styled components. 

`` export const ButtonBase = styledTS<ButtonBaseProps>(styled.button) `// css style here` ``

In order to support above syntax, I add a custom rule inside styled-components.json file. After modified the regex rule, I got the Syntax highlight correct but no IntellSense. Where should I change to fix intellSense issue?

**Comment by Cu3PO42** [comment]
IntelliSense is handled by `typescript-styled-plugin`. You can follow the instructions [here](https://github.com/styled-components/vscode-styled-components/issues/68) to add your own triggers.
