### ISSUE TITLE
[ts-styled-plugin] property value expected

### ISSUE THREAD

**Issue by jasperdunn** [styled-components/vscode-styled-components#76]
Hey,
I'm getting this error: `[ts-styled-plugin] property value expected`

![screen shot 2018-03-30 at 10 06 46 am](https://user-images.githubusercontent.com/26566353/38117704-42af296a-3402-11e8-983f-fdbae2bd7685.jpg)

```
const activeClassName = 'active-nav-link'

const Link = styled(NavLink).attrs({ activeClassName })`
  &.${activeClassName} {
    background-color: ${color.lightest};
  }

  &:hover {
    background-color: ${color.lightest};
  }
`
```

I get an error above. But not in the code below.

```
const activeClassName = 'active-nav-link'

const Link = styled(NavLink).attrs({ activeClassName })`
  &:hover {
    background-color: ${color.lightest};
  }  

  &.${activeClassName} {
    background-color: ${color.lightest};
  }
`
```

**Comment by Cu3PO42** [comment]
As the error message indicates, this is an issue with [typescript-styled-plugin](https://github.com/Microsoft/typescript-styled-plugin), which vscode-styled-plugin uses.

Please open this issue there as well and we can track the upstream issue.

**Comment by jasperdunn** [comment]
Thanks Tobias, will do.
