### ISSUE TITLE
Syntax highlighting not working for .JSX file on vcode 1.21.1 

### ISSUE THREAD

**Issue by BetaMee** [styled-components/vscode-styled-components#77]
Hi, I found this bug on vscode v1.21.1

- `.JSX` file not work

![image](https://user-images.githubusercontent.com/17882639/38169254-fe414aaa-3597-11e8-8377-1faa240b6b85.png)

- `.JS` file is OK

![image](https://user-images.githubusercontent.com/17882639/38169251-d2148dde-3597-11e8-975d-ecc5310a5f26.png)

**Comment by Cu3PO42** [comment]
I cannot confirm this behaviour. `.jsx` files work fine for me and are definitely included in the list of supported file types.

You are most likely experiencing a conflict with another plugin such as the Sublime Babel plugin.

If this issue persists even when you disable all other plugins, please feel free to reopen this issue.

**Comment by BetaMee** [comment]
@Cu3PO42 My vscode have installed two Javascript syntax coloring plugin: Babel ES6/ES7 & Babel JavaScript. I uninstalled Babel ES6/ES7 and everything is OK~
