### ISSUE TITLE
Not working on other js-like language mode

### ISSUE THREAD

**Issue by Ginhing** [styled-components/vscode-styled-components#8]
For example, when setting the langugae mode as [`Javascript (Babel) `](https://marketplace.visualstudio.com/items?itemName=dzannotti.vscode-babel-coloring) is not working.

![screenshot from 2016-12-21 21-29-02](https://cloud.githubusercontent.com/assets/3444080/21390999/2d06574e-c74f-11e6-95db-8e11b9a029d3.png)

Please feel free to close if it isn`t in plan and thanks for your work!

**Comment by camdub** [comment]
I'm seeing this same thing.

**Comment by rohmanhm** [comment]
Since update to `vscode Version 1.8.1 (1.8.1)` this stuff doesn't work.

**Comment by rohmanhm** [comment]
I'm sorry, it's work. just change from `Styled` to `styled`.

**Comment by julienp** [comment]
Is `Javascript (Babel)` provided by https://marketplace.visualstudio.com/items?itemName=dzannotti.vscode-babel-coloring ? It's probably a mismatched scope name, I'll look into it this weekend.

**Comment by julienp** [comment]
I've tried https://marketplace.visualstudio.com/items?itemName=dzannotti.vscode-babel-coloring and https://marketplace.visualstudio.com/items?itemName=joshpeng.sublime-babel-vscode and both seem to work correctly for me.

Could you check if it works without those extensions in the builtin javascript or (javascriptreact) languages?

Additionally you could try uninstalling and re-installing vscode-styled-components. I've had one occasion where it seemingly didn't work until a reinstall.

**Comment by satya164** [comment]
Which grammar did you try? javascript` or `javascriptreact`? Both of them  are included in both the extensions.

**Works**

![image](https://cloud.githubusercontent.com/assets/1174278/22395940/83bbc09c-e572-11e6-9532-4addb054172b.png)

Default JavaScript (React) Grammar

![image](https://cloud.githubusercontent.com/assets/1174278/22395943/87675990-e572-11e6-99d7-8bb033e35015.png)

Sublime Babel JavaScript React Grammar

**Doesn't work**

![image](https://cloud.githubusercontent.com/assets/1174278/22395944/8f12182e-e572-11e6-969b-30432de4064c.png)

Default JavaScript Grammar

![image](https://cloud.githubusercontent.com/assets/1174278/22395945/94700a74-e572-11e6-9cd9-44febf386728.png)

Sublime Babel JavaScript Grammar

**Comment by julienp** [comment]
That's really weird! Could you list all the extensions you use? `code --list-extensions --show-versions`, I can try to see if one of them messes with the default javascript scope.

**Comment by satya164** [comment]
I've quite a lot, but here you go:

```sh
DavidAnson.vscode-markdownlint@0.6.1
EditorConfig.EditorConfig@0.3.4
HookyQR.beautify@0.7.3
Orta.vscode-jest@2.0.5
abadi199.elm-format@0.1.0
balmor.behave@1.6.0
capaj.vscode-exports-autocomplete@0.3.5
chipcollier.Theme-OceanKit@0.0.2
christian-kohler.path-intellisense@1.2.0
clinyong.vscode-css-modules@0.1.1
dbaeumer.vscode-eslint@1.2.2
djabraham.vscode-yaml-validation@0.0.1
donjayamanne.python@0.5.6
esbenp.prettier-vscode@0.6.0
fabianlauer.vs-code-xml-format@0.1.4
faustinoaq.javac-linter@1.2.2
formulahendry.auto-close-tag@0.3.9
formulahendry.auto-rename-tag@0.0.11
joshpeng.sublime-babel-vscode@0.2.4
joshpeng.theme-onedark-sublime@0.3.4
joshpeng.theme-tomorrowkit-sublime@0.1.1
jpoissonnier.vscode-styled-components@0.0.3
leizongmin.node-module-intellisense@1.3.0
lextudio.restructuredtext@0.0.19
minhthai.vscode-todo-parser@1.8.6
mohsen1.prettify-json@0.0.3
mquandalle.graphql@0.1.2
mrmlnc.vscode-csscomb@4.0.0
mrmlnc.vscode-less@0.6.0
mrmlnc.vscode-scss@0.6.0
ms-vscode.atom-keybindings@1.8.3
ms-vscode.typescript-javascript-grammar@0.0.18
naumovs.color-highlight@1.3.0
pprice.better-merge@0.5.1
redhat.java@0.0.9
robinbentley.sass-indented@1.3.0
rtorr.vscode-flow@276.3.0
sbrink.elm@0.8.3
seanmcbreen.Spell@0.9.1
shinnn.stylelint@0.21.2
steoates.autoimport@1.2.2
teabyii.ayu@0.2.1
tushortz.java-snippets@0.0.1
vsmobile.vscode-react-native@0.2.5
waderyan.babelrc@1.0.0
```

My VSCode settings,

```json
{
  "editor.fontFamily": "Fira Code",
  "editor.fontLigatures": true,
  "editor.scrollBeyondLastLine": false,
  "editor.wordWrap": true,
  "editor.tabSize": 2,
  "editor.renderIndentGuides": true,
  "javascript.validate.enable": false,
  "eslint.autoFixOnSave": true,
  "flow.path": "node_modules/.bin/flow",
  "java.home": "/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home",
  "files.associations": {
    ".eslintrc": "yaml",
    "*.js": "javascript",
    ".stylelintrc": "json"
  }
}
```

**Comment by julienp** [comment]
It works when I disable `rtorr.vscode-flow`. This extension registers its own javascript grammar, just like the various Babel extensions. I've had a quick look at the extension and at first glance I don't see any obvious differences to the other extensions or what could be preventing the styled-components grammar injection from working.

**Comment by satya164** [comment]
@julienp Ah. Thanks a lot for looking into it. I'll try to find a different flow extension then. This is the only one that had worked me properly so far though. I'll open an issue there are reference this one. Thanks again.

**Comment by CameronFletcher92** [comment]
Not sure this should have been closed, I don't get any syntax highlighting either. These are my extensions:

```
PKief.material-icon-theme@1.2.0
christian-kohler.path-intellisense@1.2.0
dbaeumer.vscode-eslint@1.2.2
dzannotti.vscode-babel-coloring@0.0.4
formulahendry.auto-rename-tag@0.0.11
jpoissonnier.vscode-styled-components@0.0.3
vscodevim.vim@0.5.2
zhuangtongfa.Material-theme@1.0.3
```

![image](https://cloud.githubusercontent.com/assets/1721120/22488670/7de0cda0-e867-11e6-8e02-a1e902cb391e.png)

**Comment by mbeaudru** [comment]
Installing both babel & sublime-babel did the trick for me :+1:

**Comment by RedRx** [comment]
How can I use styled-components intellisense for my nvim ?

Thanks so much

**Comment by jasonwilliams** [comment]
@RedRx see https://github.com/typescript-language-server/typescript-language-server/issues/196#issuecomment-874230366
