### ISSUE TITLE
Syntax Highlighting And Intellisense Import Suggestions Broken When Used With Babel ES6/ES7 Plugin

### ISSUE THREAD

**Issue by Undistraction** [styled-components/vscode-styled-components#83]
Looks like syntax highlighting breaks when `injectGlobal` or `css'  isn't in the file root:

![cap1](https://user-images.githubusercontent.com/161489/39144106-b81f4b20-4727-11e8-9d25-9c4fb473ca28.jpg)

The same is true whether wrapped in a function body or not. The eslint comment in the above example has no effect.

Probably related to #82

vscode-styled-components Version **0.0.17**
VSCode Version **1.22.2 (1.22.2)**

**Comment by Undistraction** [comment]
It appears error reporting is also broken in some instances:

`vscode-styled-components` disabled:
![cap2](https://user-images.githubusercontent.com/161489/39614922-41bb3182-4f6b-11e8-8790-c836ba3a2cc9.jpg)


![cap1](https://user-images.githubusercontent.com/161489/39614904-289e24c0-4f6b-11e8-9e22-a26f932d3ebd.jpg)

`vscode-styled-components` enabled:

**Comment by Undistraction** [comment]
@Cu3PO42 Thank you. I switched from **Babel ES6/ES7** to **Babel JavaScript** plugin and that seems to have fixed the highlighting issues. I'd suggest making a note of this in the README as  Babel ES6/ES7 is far more popular (with over twice as many downloads). I'll happily do this in a PR if that would be helpful

**Comment by Undistraction** [comment]
Closed in favour of #23

**Comment by Cu3PO42** [comment]
That's a good suggestion. I'll add a note to the README. In general we can't guarantee compatibility with any custom JS grammars, since the injection of this grammar ultimately relies on some internal structure of the JS/TS grammar. That said, I'm not really sure why those plugins are needed at all anymore. The bundled JS grammar is really good at this point.

**Comment by infodevart** [comment]
it's not working for me, everything work fine only if i disable "Babel javascript"
