### ISSUE TITLE
Highlighting Broken When Using StyledFunction & Typescript

### ISSUE THREAD

**Issue by siorra** [styled-components/vscode-styled-components#84]
![img](https://user-images.githubusercontent.com/2460957/39162849-b68f3b88-47a1-11e8-9b4f-4607d8f3128e.png)

vscode-styled-components Version 0.0.17
VSCode Version 1.22.2 (1.22.2)

**Comment by Cu3PO42** [comment]
Unfortunately the plugin has no semantic analysis that enables it to infer precisely when a tag belongs to styled-components. As such we must resort to a purely syntactic solution. Names that trigger highlighting are `styled`, `css` and `injectGlobal`. It is impossible for us to exhaustively support any sensible names one might come up with for these tags however.

I understand the specific use case here is the passing of template parameters to the `styled` function. Support for specifying generic type parameters on tagged template literals has already landed in TypeScript and is slated for release with the next version. This will offer a different (arguably more concise) way to tackle your problem and will be supported.

For now I can only recommend naming your wrappers `css` or `styled` (possibly combined with another import name).
