### ISSUE TITLE
component.extend doesn't highlighting

### ISSUE THREAD

**Issue by ChilliLittle** [styled-components/vscode-styled-components#86]
![image](https://user-images.githubusercontent.com/29562029/39541556-f4e62f0e-4dfa-11e8-904f-ebe023bafda9.png)
doesn't higliting with extend my own component

**Comment by Cu3PO42** [comment]
This works fine for me. Can you confirm that

* you are using the latest version of this plugin (0.0.18 at the time of writing)
* you aren't using the "Babel ES6/ES7" plugin which is incompatible with this one

**Comment by ChilliLittle** [comment]
@Cu3PO42  thanks It works because I used "Sublime Bable" plugin that causes the issue.

**Comment by Cu3PO42** [comment]
The incompatibility with that is a new one... Good to know.

Glad this resolved your issue.
