### ISSUE TITLE
.extend.attrs rule breaks highlighting after the template literal

### ISSUE THREAD

**Issue by Cu3PO42** [styled-components/vscode-styled-components#87]
The injection rule used for the `.extend.attrs` case does not terminate the CSS scope correctly after the template literal ends, which breaks highlighting.

Interestingly the 'normal' `.attrs` case works fine.

**Comment by sonaye** [comment]
`.extend` without `.attrs()` too.

<img width="307" alt="screen shot 2018-05-06 at 2 57 28 am" src="https://user-images.githubusercontent.com/23000873/39668551-42f8be10-50d9-11e8-86a5-f041ea104f98.png">

**Comment by Cu3PO42** [comment]
You appear to be facing a different issue here, i.e. the `.extend` rule not triggering at all, which is probably an incompatibility with "Sublime Babel" or "Babel ES6/ES7".

**Comment by sonaye** [comment]
You are right I am using sublime-babel, any way around this?

**Comment by Cu3PO42** [comment]
None other than not using that plugin. I have explained in #23 why this is unfortunately a "won't fix" issue.
