### ISSUE TITLE
False Positive Error When Interpolating Props In Declaration Name

### ISSUE THREAD

**Issue by Undistraction** [styled-components/vscode-styled-components#88]
The following code is incorrectly flagged as an error:

Code:
![cap](https://user-images.githubusercontent.com/161489/39671817-5dbb4ee6-5117-11e8-90bd-7f4afd540baa.jpg)

Error Message: 
> [ts-styled-plugin] } expected
 
vscode-styled-components 0.0.18
babel-javascript: 0.0.14
vscode 1.23.0 (1.23.0)

**Comment by Cu3PO42** [comment]
As the error message indicates, this is actually a problem with `ts-styled-plugin` which comes bundled with this plugin and not this plugin directly. Please raise an issue [there](https://github.com/Microsoft/typescript-styled-plugin) as well, so we can track it here.

**Comment by Undistraction** [comment]
Apologies. I thought that was the generic css plugin. I'll open an issue there.

**Comment by mjbvz** [comment]
Should be fixed by #99
