### ISSUE TITLE
Seems to work well with the Emotion library as well

### ISSUE THREAD

**Issue by carpben** [styled-components/vscode-styled-components#89]
I'm actually using the Emotion library, due to performance and syntax. 
I'm happy to let you know that the library also works with Emotion's template literals even though it uses a different syntax. Perhaps it can be used for CSS in JS template literals, and even CSS in JS in general.

**Comment by Cu3PO42** [comment]
Glad to know it works well for you. I took some care to make sure it would work at least decently good with it.

At this time we don't support any other libraries officially, but the grammar for the CSS itself should be able to be used exactly for any other library with only minor adjustments to the grammar triggering the highlight.

Personally I am amenable to adding a few "highlighting triggers" for other popular CSS-in-JS libraries when they make sense, however.
