### ISSUE TITLE
Not work with export default

### ISSUE THREAD

**Issue by rohmanhm** [styled-components/vscode-styled-components#9]
If I define it by `const`, `var` or `let` just work fine.
But when I directly use `export default styled.button` it didn't work

**Comment by julienp** [comment]
Unfortunately I can not reproduce this, do you still have the issue?

**Comment by rohmanhm** [comment]
yeah, I still got it. Take a look my screenshot different between directly using `export default` and define first using `let` and `const`.

Direct `export default`
![image](https://cloud.githubusercontent.com/assets/7524911/22397099/6f53ac9e-e59c-11e6-9a15-a058c4af6e30.png)


Define first as variable
![image](https://cloud.githubusercontent.com/assets/7524911/22397101/7666863c-e59c-11e6-846b-dea5f093a651.png)

**Comment by julienp** [comment]
Which theme and language mode are you using? Could you please paste the output of `code --list-extensions --show-versions` here?

**Comment by rohmanhm** [comment]
Currently, I'm using `Javascript (Babel)` and `One Dark` Theme

This is list extensions which installed on my vscode

```
code --list-extensions --show-versions
JerryHong.autofilename@0.1.3
PKief.material-icon-theme@1.2.0
abusaidm.html-snippets@0.0.18
andischerer.theme-atom-one-dark@0.0.1
azemoh.theme-onedark@0.4.3
bgse.relative-path-and-line@0.1.0
dbaeumer.vscode-eslint@1.2.2
donjayamanne.githistory@0.1.5
dzannotti.vscode-babel-coloring@0.0.4
felixfbecker.php-intellisense@0.0.12
hnw.vscode-auto-open-markdown-preview@0.0.3
joelday.docthis@0.3.10
jpoissonnier.vscode-styled-components@0.0.3
peterjuras.fontsize-shortcuts@1.2.0
robinbentley.sass-indented@1.3.0
seanmcbreen.Spell@0.9.1
sleistner.vscode-fileutils@2.3.3
xabikos.JavaScriptSnippets@1.2.0
```

**Comment by TimeRaider** [comment]
@rohmanhm try switching language mode to `javascript react`, worked for me

**Comment by rohmanhm** [comment]
@TimeRaider Thanks bro, now it's work 👍🏼
