### ISSUE TITLE
Media highlighting in interpolation

### ISSUE THREAD

**Issue by goodmind** [styled-components/vscode-styled-components#90]
![image](https://user-images.githubusercontent.com/3275424/39964998-29062ffc-56aa-11e8-86b5-6fb25558a9bf.png)

**Comment by Cu3PO42** [comment]
This is most likely not related to it being in an interpolation but only to using the trigger in another expression (i.e. the `&&` expression).

I'll look into a few things, but most likely this can't be fixed without modifying the original JS/TS grammar, which would unfortunately be a "won't fix" situation.
