### ISSUE TITLE
Linting & IntelliSense don't work with emotion-style TypeScript declarations

### ISSUE THREAD

**Issue by nicolasschabram** [styled-components/vscode-styled-components#92]
Hey guys,

I noticed that linting and IntelliSense don't quite work for me when providing TypeScript declarations to a styled emotion component. Is it possible that #60 only fixed syntax highlighting? Or is something odd about my setup?

![linting](https://user-images.githubusercontent.com/1027642/40853708-585b39d0-65cf-11e8-8ce1-eb1226eda96f.PNG)

Thanks a lot for putting in the work! This plugin makes the whole CSS-in-JS experience a lot nicer! :)
Nicolas

**Comment by Cu3PO42** [comment]
As always, IntelliSense isn't handled by this plugin, but by `ts-styled-plugin` which comes bundled with this plugin. Please raise an issue [there](https://github.com/Microsoft/typescript-styled-plugin) for the IntelliSense part.

As for the syntax highlighting, this might be an incompatibility with other plugins that "improve" JS syntax highlighting.

**Comment by nicolasschabram** [comment]
Alright, I've [reported the IntelliSense issue](https://github.com/Microsoft/typescript-styled-plugin/issues/56) over at `ts-styled-plugin`. Thanks for the clarification!

**Comment by umlx5h** [comment]
Same as with styled-components.
and when using inline type decorations, Both linting and syntax highlighting are not working.
Is this problem related to this plugin?

![code](https://user-images.githubusercontent.com/20206121/40868830-48deec5e-664c-11e8-8662-85c58be623a1.png)

**Comment by kachkaev** [comment]
One more syntax flavour to support:

```ts
const Title = styled.h1<{ size: number }>`
  font-size: ${p => p.size}em;
`
```

ref: https://github.com/styled-components/styled-components/pull/1798

**Comment by mjbvz** [comment]
Linting and intellisense should be fixed by #99

**Comment by slater101** [comment]
Is it possible to turn of Linting with this? I have no idea why, but mine is littered with bugs from the linting.  Get 100s of ts "problems" reported from one line change, can reboot VsCode and they are all gone...

**Comment by slater101** [comment]
Is it possible to turn off the linting for this? I get littered with bugs from the linter, turning it off would make my day. lol
