### ISSUE TITLE
Color picker?

### ISSUE THREAD

**Issue by cuervoluna** [styled-components/vscode-styled-components#95]
Is there a way to use the color picker? If not, that's the only thing keeping this plugin from being perfect IMO. Thank you.

**Comment by koiski** [comment]
I would also very much like to user a color picker in VSCode when using styled components

**Comment by rainstormza** [comment]
https://marketplace.visualstudio.com/items?itemName=naumovs.color-highlight

Hope this help.

**Comment by webberwang** [comment]
> https://marketplace.visualstudio.com/items?itemName=naumovs.color-highlight
> 
> Hope this help.

@rainstormza Hey thanks for that! it brought the color to life for HEX codes inside JS syntax. It's still missing the color wheel though, which would help productivity quite a bit

![vscode-color](https://user-images.githubusercontent.com/26264925/47205640-59ec7500-d33b-11e8-915c-1fd2c614dacd.gif)

**Comment by dallas** [comment]
Does anybody know what triggers the color preview box and color picker behavior in CSS files in VS Code? I took a quick look at the TM Scope Inspector but I didn’t notice anything that jumped out at me as being the likely cause. Just wondering if there’s something “simple” that could be tapped into to get that same behavior inside CSS scoped within other files (like `.jsx` or `.tsx`).

**Comment by AlfieDarko** [comment]
> https://marketplace.visualstudio.com/items?itemName=naumovs.color-highlight
> 
> Hope this help.

Mate, thank you so much for this!

**Comment by vhflat** [comment]
> https://marketplace.visualstudio.com/items?itemName=naumovs.color-highlight
> 
> Hope this help.

Thanks for this, but it should be supported natively by this extension.

**Comment by Bulletninja** [comment]
> > https://marketplace.visualstudio.com/items?itemName=naumovs.color-highlight
> > Hope this help.
> 
> Thanks for this, but it should be supported natively by this extension.

I think it should also support color highlighting by name. Right now it only gets highlighted if using hex.

**Comment by gkgrepo** [comment]
To whoever it helps, you can use the Color-Picker from your browser's Dev-Tools

![Screenshot - 2_12_2020 , 11_27_21 AM](https://user-images.githubusercontent.com/59545567/74355337-bd997d80-4d8a-11ea-85aa-4076c243882d.jpg)

**Comment by nbar1** [comment]
bump. Would love an integrated solution.

**Comment by vikrantsingh47** [comment]
> https://marketplace.visualstudio.com/items?itemName=naumovs.color-highlight
> 
> Hope this help.

thanks for this. also, can this also suppost colors by name, like "black" ?

**Comment by raphtlw** [comment]
bump. Would love to see this happening, it's already been 2 years.

**Comment by Flandre-X** [comment]
bump

**Comment by PCDSandwichMan** [comment]
More bumps. This needs to be a thing.

**Comment by numeroflip** [comment]
bump. I use the color picker all the time when writing css. It would be a much needed feature in this extension.

**Comment by knidarkness** [comment]
would be really great to have this

**Comment by kenton** [comment]
Bump...would love to see this happen

**Comment by SamuelGadiel** [comment]
Bump for this feature!

**Comment by 8catherine-alexandra8** [comment]
bump

**Comment by amstiel** [comment]
bump

**Comment by ywang04** [comment]
bump!

**Comment by jasonwilliams** [comment]
Sadly, the only way an extension can enable the built-in color picker is via the Language Server Protocol.

How the color picker in VSCode works:
https://github.com/microsoft/vscode/issues/52364#issuecomment-410834051

Looks like a language server is needed to enable the native color picker.
Here is the spec for it:
https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_colorPresentation

It's not impossible, but will be a lot of work for anyone who picks it up.

**Comment by jasonwilliams** [comment]
If anyone wants to have a go at this, ive updated the contributing guide on how to get setup:
https://github.com/styled-components/vscode-styled-components/blob/master/CONTRIBUTING.md#intellisense-isues

**Comment by jasonwilliams** [comment]
It seems styled plugin isn’t the way forward, a language server will need to be made with support for sass as an embedded language, there’s a tutorial and an example project here https://code.visualstudio.com/api/language-extensions/embedded-languages

**Comment by jasonwilliams** [comment]
The color picker has been added and deployed into version v1.2

**Comment by alvarlagerlof** [comment]
@jasonwilliams Is there anything special I need to do to make this work? I'm not getting the native color picker in my files at all. I'm not using anything special. Just JS files with next.

**Comment by jasonwilliams** [comment]
@alvarlagerlof could you show me a screenshot, then maybe show extension version and file extension of the file you’re looking at? Cheers

**Comment by alvarlagerlof** [comment]
@jasonwilliams ![image](https://user-images.githubusercontent.com/14835120/96639549-2675c400-1322-11eb-96f9-e92365a2cd39.png)
As you can see I'm not seeing the box that vscode provides, and there is also no picker when selecting it. 

![image](https://user-images.githubusercontent.com/14835120/96639613-41483880-1322-11eb-9691-79848ed3c140.png)
And is the version

**Comment by jasonwilliams** [comment]
@alvarlagerlof do you have any errors in your "developer tools" in "Toggle Developer Tools"

**Comment by alvarlagerlof** [comment]
@jasonwilliams Nothing that comes up when I write colors to attempt to make the picker come up.

**Comment by nbar1** [comment]
> Is it working for anyone else?

Doesn't work for me at all - no errors either.

**Comment by jasonwilliams** [comment]
It’s working for some https://github.com/styled-components/vscode-styled-components/issues/242#issuecomment-715928332 so I don’t know what’s different in your settings. Is it a conflicting extension? All we can do is provide more verbose logging, I don’t know when I’ll get to this though we’re open for PRs

**Comment by tasesmuemils** [comment]
Updated vscode to 1.50.1 version, reinstalled extension - nothing changed.
Changed my Javascript file "Language mode" to JavaScript React. Color square shows before color text and picker shows up when clicking on color.
Thanks @jasonwilliams

**Comment by kyle-aoki** [comment]
bump

**Comment by jasonwilliams** [comment]
@kyle-aoki why are you bumping this thread?

**Comment by kotoyama** [comment]
bump

**Comment by alvarlagerlof** [comment]
> @kyle-aoki why are you bumping this thread?

Probably because it still isn't working for everyone

**Comment by jasonwilliams** [comment]
> > @kyle-aoki why are you bumping this thread?
> 
> Probably because it still isn't working for everyone

Then my suggestion would be to raise a new issue with up to date information. This issue is from 2018 and was fixed for many users here. Bumping this doesn’t really help the maintainers.

**Comment by ZaidKhan144** [comment]
@tasesmuemils Thank you so much, this worked for me.

**Comment by alekslario** [comment]
> Language mode

Where exactly can I find this setting?

**Comment by ZaidKhan144** [comment]
> > Language mode
> 
> Where exactly can I find this setting?
Ctrl + K + M
Also, you can find the language mode at the bottom of the VS code.

**Comment by jasonwilliams** [comment]
Worth pointing out that if your extension is .jsx or .tsx you shouldn’t have to manually set language. Those are the file extensions you should be using if you have styled components in there.

**Comment by ZaidKhan144** [comment]
> Worth pointing out that if your extension is .jsx or .tsx you shouldn’t have to manually set language. Those are the file extensions you should be using if you have styled components in there.

@jasonwilliams I lost my color picker when setting the file extension to .jsx. But got it back when changing Language Mode manually to JavaScript React 😕

**Comment by jasonwilliams** [comment]
> > Worth pointing out that if your extension is .jsx or .tsx you shouldn’t have to manually set language. Those are the file extensions you should be using if you have styled components in there.
> 
> @jasonwilliams I lost my color picker when setting the file extension to .jsx. But got it back when changing Language Mode manually to JavaScript React 😕

Ah shame, what did it default to out of interest? Was something else claiming .jsx? I would have thought the extension would have higher priority over “JavaScript”

**Comment by ZaidKhan144** [comment]
> Ah shame, what did it default to out of interest? Was something else claiming .jsx? I would have thought the extension would have higher priority over “JavaScript”

No idea, emmet, and IntelliSense working flawless though.

**Comment by emintokluu** [comment]
> Updated vscode to 1.50.1 version, reinstalled extension - nothing changed.
> Changed my Javascript file "Language mode" to JavaScript React. Color square shows before color text and picker shows up when clicking on color.
> Thanks @jasonwilliams

This method working. Thanks.

**Comment by PedroSSM2000** [comment]
Hi, was looking around for an answer to this and found this very useful extension: [vscode-color-picker](https://marketplace.visualstudio.com/items?itemName=AntiAntiSepticeye.vscode-color-picker)

It allows you to change color strings anywhere in any language using the native vscode color picker, perfect for what I was looking for.

**Comment by ZaidKhan144** [comment]
@PedroSSM2000 gods work!

**Comment by jasonwilliams** [comment]
> Hi, was looking around for an answer to this and found this very useful extension: [vscode-color-picker](https://marketplace.visualstudio.com/items?itemName=AntiAntiSepticeye.vscode-color-picker)
> 
> It allows you to change color strings anywhere in any language using the native vscode color picker, perfect for what I was looking for.

@PedroSSM2000 why do you need an extension? Is the Color picker not working in this?

**Comment by I2evard** [comment]
> > Where exactly can I find this setting?
> 
> @alekslario Ctrl + K + M, Also, you can find the language mode at the bottom of the VS code.

Thank you omg! Switching the language with that shortcut worked for me! Thanks a lot!

**Comment by Pavlenko-M** [comment]
> Hi, was looking around for an answer to this and found this very useful extension: [vscode-color-picker](https://marketplace.visualstudio.com/items?itemName=AntiAntiSepticeye.vscode-color-picker)
> 
> It allows you to change color strings anywhere in any language using the native vscode color picker, perfect for what I was looking for.

Thank you, this is what I've been looking for for so long
