### ISSUE TITLE
Support vue

### ISSUE THREAD

**Issue by hollandThomas** [styled-components/vscode-styled-components#96]
Is it possible to support [vue-styled-components](https://github.com/styled-components/vue-styled-components) or in other words files wih the `.vue` extension? Thanks!

**Comment by Cu3PO42** [comment]
I am not familiar with Vue myself. Would it really be sufficient to allow the ̀ .vue` file extension in addition to ̀ .[jt]sx?`?

If that is the case, that should be quite easy to do. If there are other things to do, I still think that supporting it might be a sensible thing to do, however then the feature would probably have to wait until someone decides to contribute it.
