### ISSUE TITLE
Highlighting and autocomplete broken when use const (VSCode)

### ISSUE THREAD

**Issue by nadam131** [styled-components/vscode-styled-components#97]
Strange things happening. Code highlighting and autocomplete breaks down when you using this with const %ComponentName% = styled.div {...}

![image](https://user-images.githubusercontent.com/13889241/41721328-41d02046-756e-11e8-9ae0-c6fc7003b4a7.png)

I have the latest version of VSCode. Using MacOs.

**Comment by ulshv** [comment]
The same for me. Latest VSCode, Mac OS

**Comment by sergiokopplin** [comment]
@ulshv same for me, thanks! Working!

**Comment by Cu3PO42** [comment]
Unfortunately incompatibilities with other plugins that modify the JS grammar significantly are virtually unavoidable.

**Comment by Cu3PO42** [comment]
We are still tracking all incompatibilities in #23.
